- week1/BOJ_1931/회의실배정_한의정.java
- 백준 1931 - 회의실 배정
1. 회의 **종료 시간 순** 오름차순 정렬한다.
2. **이전 회의 종료 시간 <= 현재 회의 시작 시간** 인 경우, 기준이 되는 종료 시간을 현재 회의의 종료 시간으로 변경하고, 정답을 +1한다.
정렬 기준을 찾는 데 생각보다 시간이 오래 걸렸다.
<br/>
없음
> [BOJ] 1931_회의실배정 / 실버1 / 45분 / O

- week2/BOJ_2800/괄호제거_한의정.java
- 백준 2800 - 괄호 제거
- 자료구조
- (여는 괄호 위치, 닫는 괄호 위치) 저장 객체
- 괄호 위치 객체 저장 리스트
- 괄호 제거해서 나오는 식 저장할 TreeSet
- 괄호 지울지 말지 판단용 boolean 배열
1. 여는 괄호인 경우, 스택에 시작 위치 인덱스를 넣는다.
2. 닫는 괄호인 경우, (스택의 여는 괄호 인덱스, 현재 인덱스)를 넣는다.
3. 백트래킹을 통해 괄호가 존재하는 모든 조합을 구한다.
- 스택에 괄호 넣을 생각만 했지, 위치 인덱스를 넣을 생각은 하지 못 했다...
- 백트래킹 쓸 생각은 했는데 어떻게 결과를 저장하고 출력할지를 잘 생각하지 못 했다.
`TreeSet` : 자동으로 중복 제거 & 사전 순 정렬
> [BOJ] 2800_괄호제거 / 골드5 / 60분 / X

- week3/BOJ_20546/기적의매매법_한의정.java
- 백준 20546 -  [🐜 기적의 매매법 🐜](https://www.acmicpc.net/problem/20546)
1. [준현] **그리디**를 활용해 남은 현금과 보유 주식 수를 구한다.
2. [성민]
- 3일 연속 가격이 전일 대비 상승 시, 그 다음 날에 다 판다. (전량 매수)
-  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; "&nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; &nbsp; 하락 시, 그 다음 날에 다 산다. (전량 매도)
3. 둘 중 누가 더 높은 수익률을 내는지 계산한다. <br/>→ `최종 보유 현금 + 1.14 주가 * 최종 보유 주식 수`
- 매도-매수 단어가 헷갈렸다,,
- 성민이가 `3일 연속 가격이 전일 대비 하락한다면, "즉시" 전량 매수`라고 해서 셋째 날에 바로 전량 매수를 했는데, 이러니까 틀렸다. 그래서 그 다음 날인 **넷째 날 거래**했더니 해결되었다.
- 집중을 빠짝했다면 더 빨리 풀 수 있었을 것 같다,,
X
> [BOJ] 20546_기적의매매법 / 실버5 / 70분 / O

- week3/BOJ_20207/달력_한의정.java
- 백준 20207 - [달력](https://www.acmicpc.net/problem/20207)
1. 구간을 입력받고, 해당 시작점부터 끝점까지 구간을 색칠한다. <br/> → **_카운트 배열 사용_**
2. 카운트 배열을 돌면서 해당 칸의 값이 0이 아니라면, 너비 + 1하고 높이는 최대 높이와 비교해 더 큰 값으로 갱신한다. / 해당 칸의 값이 0이라면, 여태까지 구한 너비와 최대 높이를 구해 넓이 값에 누적해 저장하고, 너비와 최대 높이는 0으로 초기화한다.
3. 마지막 구간 처리를 위해 마지막에 넓이들의 합에 `너비 * 최대 높이` 구한 값을 더해줘야 한다!!
- 입력 값 정렬이나 이럴 필요 없이 배열에 값을 누적해 저장하기만 하면 된다는 걸 생각해내는데 오래 걸렸다.
- 마지막 범위 처리를 놓쳐서 틀렸었다..
X
> [BOJ] 20207_달력 / 골드5 / 90분 / X

- week4/BOJ_2578/빙고_한의정.java
- 백준 2578 - [빙고](https://www.acmicpc.net/problem/2578)
> 시간 복잡도 : O(1)
1. 배열을 먼저 입력받는다.
2. 사회자가 부른 숫자를 입력받는다.
3. 사회자가 부른 숫자를 배열에서 찾고, 0으로 표시한다.
4. `행`, `열`, `왼쪽 위-오른쪽 아래 방향의 대각선1`, `오른쪽 위 - 왼쪽 아래 방향의 대각선2` 에서 총 빙고 갯수를 확인한다.
- 빙고 조건 : 해당 열/행/대각선에 대해 0의 갯수가 5개
5. 빙고 갯수가 3개 이상이면, 사회자가 현재까지 숫자를 부른 횟수(turn)를 출력하고 종료한다.
6. 빙고 갯수가 3개 미만이라면, 빙고 갯수를 0으로 출력하고, 사회자가 숫자를 부른 횟수 + 1한다.
빙고인지 확인할 때 숫자를 입력받을 때마다 확인해야 하는건가? 싶었다. (맞다.)
뭔가 숫자를 하나 불렀을 때, 여태까지의 빙고 갯수를 저장해두고 그 때 빙고 갯수가 3개가 초과하면 사회자가 현재까지 숫자를 부른 횟수를 출력하고 싶었는데 그게 안 됐다.
그냥 `숫자 하나 입력받고 > 행,열,대각선에서 빙고 갯수 확인 > 3개 안 되면 다시 숫자 입력 > 빙고 갯수 확인 > .. `이것의 연속이었다.
X
> [BOJ] 2578_빙고 / 실버4 / 90분 / X

- week5/BOJ_1325/효율적인해킹_한의정.java
- 백준 1325 - [효율적인 해킹](https://www.acmicpc.net/problem/1325)
<br/>
> BFS
사용 자료구조
> - 인접 리스트 배열
> - boolean형 방문 배열
> - int형 노드 별 해킹 가능한 컴퓨터 수 저장 배열
> - 최대 해킹 가능한 컴퓨터 수를 저장하는 int형 변수
1. 인접 리스트에 값을 입력 받는다. → `A[a].add(b)`
2. 1번부터 N번 노드까지 방문 배열을 매번 초기화하고 BFS를 수행한다.
- BFS 수행 시, 각 점과 연결된 점들을 방문하면서, **그와 연결된 노드들의 카운트를 올리고**, 연결된 노드를 방문처리하고, 큐에 저장한다.
<br/>
- 시간 초과가 자꾸 떠서 시간을 많이 잡아먹었다... 😭 
- Queue를 선언할 때 `LinkedList`로 했던 걸 `ArrayDeque`로 바꿨더니 다행히 정답이 되었다...
- 모든 점마다 매번 방문 배열을 새로 초기화하는 부분도 놓쳤었다. 이러는 이유는 아래와 같다고 한다.
- 노드 별 해킹 가능한 컴퓨터 수는 참고로 아래와 같다..
<br/>
X
> [BOJ] 1325_효율적인 해킹 / 실버1 / 50분 / X

- week5/BOJ_2178/미로탐색_한의정.java
- 백준 2178 - [미로 탐색](https://www.acmicpc.net/problem/2178)
<br/>
> BFS
1. 배열을 입력받고, (0, 0)에서부터 BFS를 수행한다.
2. 이동할 칸의 좌표값을 저장할 큐를 생성한다.
3. 현재 칸에서 4방향 탐색을 통해 이동 가능한 좌표를 찾아 추가하고 그 점에서 또 탐색한다. <br/> <br/> 이 때, 범위를 벗어나거나, 칸의 값이 0이거나, 방문한 적 있는 칸이라면 방문할 수 없다. <br/> <br/>그런 경우가 아니라면 방문 가능하므로 큐에 추가하고, **이동할 칸의 값을 `현재 칸의 값 + 1`을 해 방문한 칸의 수를 누적해 저장**한다.
4. 큐가 비어있을 때까지 과정 3을 반복한다.
5. (N, M) 좌표의 값을 출력한다.
<br/>
이동한 칸 수를 구할 때, 현재 칸 (nowX, nowY)의 값에 1을 더할 생각은 했는데  (x, y) 좌표로 잘못 작성해서 시간이 좀 더 걸렸다,,
<br/>
X
> [BOJ] 2178_미로 탐색 / 실버1 / 20분 / O

- week5/BOJ_11725/트리의부모찾기_강한주.java
- 백준 11725-트리의 부모찾기
<br/>
1. `ArrayList<ArrayList<Integer>> edges` 를 통해 두 노드가 연결된 것을 표시했다
2. DFS 알고리즘을 활용하여 `edges.get(node)` node에 연결된 다른 노드들의 번호 v를 구해
3. v를 방문하지 않았다면 `parent[v] = node`로 부모 표시를 하고 v와 연결된 다른 노드번호가 있는지 구하기 위해 dfs(v)를 사용했다 (재귀)
<br/>
처음엔 parent와 visited 두 배열만 사용해서 테스트케이스를 통과했다. 
내가 처음에 푼 방법은
1. 일단 처음 `visited[1] = true`; 로 원소1은 루트로 방문한걸로 체크했다
2. 다음에 node1,node2를 입력받으며 "둘 중 하나의 노드에 방문했다면 (`visited[node?] = true`), 방문하지 않은 노드는 방문한 노드의 자식이 된다(`parent[방문하지않은노드] = 방문한노드`) , 
`visited[방문하지않은노드] = true`이런식으로 풀었다.
4. 이렇게 풀면 테스트 케이스는 통과하지만 반례가 있었다. 바로 둘 다 방문하지 않은 노드가 주어질때이다( 예: 3 , 2 3, 1 2)
5. 이럴경우 어떤 노드를 부모로 둬야하는지 혼선이 생기므로 내 풀이는 틀리게 된다
반례를 알고 다시 풀라했으나 남은시간이 얼마 없어 다른 사람의 풀이를 보았다. 
`ArrayList<ArrayList<Integer>> edges` 자료구조를 활용해 노드의 연결을 표시하였고
DFS 알고리즘을 사용해서 부모를 구했다. 
<br/> …
> [BOJ] 11725_트리의부모찾기 / 실버2 / 40분 / X

- week5/BOJ_2178/미로탐색_강아현.py
- 백준 2178 - 미로 탐색
<br/>
> **BFS**
>
> 1. 처음 위치인 0, 0과 이동횟수인 1을 deque에 담는다.
> 2. 그래프에서 이동한 위치는 값을 0으로
> 3. 이동하면서 상하좌우를 탐색하고 그래프의 값이 1인 곳으로 이동하면 deque에 (x,y,이동횟수)를 추가한다.
> 4. deque가 빌 때까지 진행하며 꺼내진 값의 x, y가 도착위치면 이동횟수를 리턴한다.
<br/>
x
<br/>
x
> [BOJ] 2178_미로 탐색 / 실버1 / 20분 / X

- week5/PSG/택배배달과수거하기_강아현.py
- 프로그래머스 - 택배 배달과 수거하기
<br/>
1. 집별로 배달할 택배 수만큼 리스트에 집 번호를 모두 나타낸다.
2. 집별로 수거할 택배 수만큼 리스트에 집 번호를 모두 나타낸다.
3. 1,2에서 구한 리스트를 거꾸로 정렬한다.
4. 3에서 정렬한 리스트를 cap 수만큼 자른다.
5. 4에서 구한 리스트의 원소값을 비교하며 d와 p 중 더 큰 원소를 구하고 이들의 누적합을 구한다.
6. 5에서 구한 누적합에 2를 곱하여 정답값으로 리턴한다.
<br/>
문제에 접근하는 것부터가 어려웠다. 배달할 택배 혹은 수거할 택배가 하나 이상 있는 집들의 인덱스를 가지고 와서 뭔가를 해보려했지만 시간초과 문제를 해결하지 못했다. 이 풀이처럼 1번집에 배달할 택배 : 1개, 2번집에 배달할 택배 : 2개가 있을 때 리스트를 [1,2,2] 이런 식으로 전부 나열하는 방법은 생각하지 못했다.
<br/>
zip_longest는 zip을 할 때 리스트 중 길이가 가장 긴 리스트를 기준으로 묶는 것이다.
> [PSG] 택배 배달과 수거하기 / 90분 / X

- week7/BOJ_2839/설탕배달_한의정.java
- 백준 2839 - 설탕 배달
<br/>
1. 초기 dp 배열의 값을 모두 MAX (=Integer.MAX_VALUE) 값으로 채운다.
2. `dp[3]`과 `dp[5]`에는 1을 넣는다.
3. N이 5 이하인 경우, 해당 칸의 값이 MAX라면 -1을 출력하게 하고, 그게 아니라면 그 칸의 값을 그대로 출력하게 한다.
4. N이 6 이상인 경우, MAX가 아닌 `j`와 `(i - j)`로 i를 만들 수 있다면, `dp[i]`를 `dp[i]`와 `dp[i] + dp[i - j]` 中 더 작은 값으로 갱신하며 dp 배열을 채운다.
- 예 : dp[18]인 경우, `dp[3] + dp[15]`, `dp[5] + dp[13],` `dp[6] + dp[12]`, .... 中 가장 작은 값으로 dp[18]의 값을 갱신한다.
5. `dp[N]`이 MAX라면 -1을 출력하게 하고, 그게 아니라면 그 칸의 값을 그대로 출력하게 한다.
<br/>
n = 4일 때 그냥 MAX 출력하게 해서 계속 90퍼에서 틀렸었던 것이다,,,
[🌵  참고 링크](https://www.acmicpc.net/board/view/129517)
<br/>
찾아보니 꼭 DP가 아니더라도 그리디로도 풀 수 있더라,,,
> [BOJ] 2839_설탕 배달 / 실버4 / 40분 / O

- week7/BOJ_11053/가장긴증가하는부분수열_한의정.java
- 백준 11053 - [가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
<br/>
1. 최장 증가하는 부분 수열 크기를 나타내는 dp 배열을 만들고, 배열 내 모든 값을 1로 초기화한다.
2. 완전탐색으로 원본 배열의 시작부터 끝까지 돌면서 고른 칸 기준 앞쪽 칸에서 현재 값보다 작은 값을 갖고 있다면, dp 배열의 현재 칸 값과 이 앞쪽 칸의 값 + 1 중 더 큰 값을 비교해 현재 칸 값으로 갱신하면 현재 위치까지 가장 긴 부분 수열 길이를 구할 수 있다.
```
int max = 1;	 // 1로 해야 함,,, 0으로 했다가 틀림,,,,
for(int i = 0 ; i < N ; i++) {
for(int j = 0 ; j < i ; j++) {    // 현재 칸 기준 앞쪽 칸 탐색
if(A[i] > A[j]) {    // 앞쪽 칸의 값이 현재 칸의 값보다 작다면
dp[i] = Math.max(dp[i], dp[j] + 1);    // 현재 dp 배열의 값 vs 앞에서 나온 가장 긴 부분 수열의 길이 + 1 中 큰 값으로 갱신한다.
max = Math.max(max, dp[i]);
}
}
}
```
<br/>
- max의 초기값을 0으로 설정해 20분간 헤매다....
<br/>
X
> [BOJ] 11053_가장 긴 증가하는 부분 수열 / 실버2 / 40분 / O

- week7/PGS/두큐합같게만들기_한의정.java
- 백준 10164 - [두 큐 합 같게 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/118667)
<br/>
> 그리디
1. 큐 2개와, 각 큐의 합을 나타내는 변수 2개를 만든다.
2. 각 큐에 원소를 추가하고, 각 큐의 합을 구한다.
3. 두 큐의 합이 같아질 때까지 반복문을 수행한다.
- 덱을 최대 3번까지 순회(= 덱 길이 * 3)하며 합을 맞춘다. 왜냐하면 큐가 제자리에 돌아오는 횟수가 덱 길이 * 3이므로
- 두 큐 중 합이 큰 쪽에서 작은 쪽으로 숫자를 보내고, 횟수를 1 증가한다.
그래서 이렇게 풀었답니다!
<br/>
- 두 덱을 무한정 순회하면서 비교하는 게 아니라, 최대 덱 길이 *3번까지 순회할 수 있다는 것을 캐치하는 것
<br/>
- 두 덱의 합을 매번 반복문으로 구할 생각을 했었는데, 그럴 필요 없이 변수에서 뺐다 더했다 하면 된다는 것
> [PGS] 두 큐 합 같게 만들기 / level2 / 40분 / X

- week7/BOJ_11053/가장긴증가하는부분수열.java
- 백준 11053 -  가장긴증가하는부분수열
<br/>
1. `dp[i]`는 a[i]를 마지막으로 골랐을 때 최장 증가 부분 수열의 길이다
2. 모든 수의 가장 긴 증가하는 부분수열의 길이의 최소값은 1이므로 dp[i] = 1로 초기화한다
3. 2중  for문을 사용해서 마지막으로 뽑은 수인 a[i]보다 전에 있는 숫자들인 a[j]들을 비교하면서 
만약 a[i] > a[j] 라면 `dp[i] = Math.max(dp[i],dp[j]+1)` 이라는 점화식을 세워 dp[i]를 구한다
<br/>
코드트리에서 간단하게 개념만 봤을때는 오 ~ 쉽네 ~ 했는데 시간이 지나니 어떻게 푸는지 기억이 나질 않았다. 
dp배열의 정의까진 했지만 점화식을 세우는것에서 막혔다. 
<br/>
이러한 문제를 '최장 증가 부분 수열(LIS)' 라고 부른다.
> [BOJ] 11053_가장긴증가하는부분수열 / 실버2 / 40분 / X

- week7/BOJ_15486/퇴사2_강한주.java
- 백준 15486 - 퇴사2
<br/>
1. dp[i]를 i일까지 일했을 때 버는 최고수익이라고 했다
2. max 변수를 써서 현재 시점까지의 최대 수익을 기록했다
3. for문을써서 돌며 max값을 갱신하고 , 현재 날짜에서(i)  t[i]의 시간을 더해 다음 상담할 날짜를 구한다. 다음 상담할 날짜에 상담을 진행할 수 있다면 진행한다
4. 이때 '현재 날짜 까지의 최대 금액 + 현재 상담 금액'과 상담이 끝난 날짜의 최고수익과 비교해 dp를 갱신한다 
<br/>
max 라는 변수를 쓸 생각도 못했고 점화식을 어떻게 세워야 할지 감 자체를 못잡았다.. 다시 풀어봐야 할 것 같다
<br/>
> [BOJ] 15486_퇴사2 / 골드5 / 30분 / X

- week7/PGS/두큐합같게만들기_강아현.py
- 프로그래머스 - 두 큐 합 같게 만들기
<br/>
> **큐의 합을 이용**
> - queue1과 queue2의 초기 합을 이용하기 위해 각각의 sum()을 구한다.
1. queue1 == queue2인 경우 혹은 sum()값이 같은 경우 : return 0
2. sum(queue1) + sum(queue2)가 홀수인 경우는 합을 같게 만들 수 없다.
3. for문이 반복하는 횟수는 큐의 전체 원소가 다른 큐로 이동했다가 다시 원래 큐로 돌아오는 횟수인 (큐 * 3)으로 한다.
4. sum()의 값이 더 큰 쪽 큐의 맨 왼쪽 값을 sum()이 작은 쪽 큐에 추가한다.
5. 이때, 이동하는 원소값으로 처음에 구해놓은 sum값에 더하거나 빼준다. (큰 sum() - 원소값) , (작은 sum() - 원소값)
6. 큐 원소가 이동할 때 cnt += 1
7. sum() 값이 같아지면 cnt를 리턴하고, sum()값이 같아지지 않는다면 -1을 리턴한다.
<br/>
시간 초과 문제를 해결하는 게 생각보다 어려웠다.
<br/>
x
> [PGS] 두 큐 합 같게 만들기 / 30분 / O

- week8/BOJ_13549/숨바꼭질3_한의정.java
- 백준 13549 - [숨바꼭질 3](https://www.acmicpc.net/problem/13549)
<br/>
> 다익스트라
1. 시간 비용 배열 time을 시작점을 제외하고 모두 INF (100,000)으로 초기화한다.
2. 우선순위 큐를 생성해 (시작 지점, 걸린 시간)을 저장한다. 우선순위 큐는 시간 기준 오름차순으로 정렬되도록 한다.
3. 우선순위 큐가 비기 전까지 아래 과정을 반복한다.
- 비용이 작은 순으로 우선순위 큐에서 값을 꺼낸다. (단, 해당 지점의 시간 time[i]이 이미 갱신된 경우는 pass한다.)
- 꺼낸 노드의 위치에서 -1, +1, *2칸 3가지 위치에 대해 현재 노드 위치를 거쳐 다음 위치로 갈 때 거리가 더 적은 경우 time 배열에서 해당 칸의 값을 갱신하고 우선순위 큐에 값을 추가한다.
<br/>
- 저렇게 3가지 경우의 수를 다 큐에 추가하면서 최소 시간을 갱신 가능하다는 아이디어를 캐치하지 못 했다.
<br/>
그냥 BFS로 풀어도 된다고 한다.
🔗  [참고 링크](https://dy-coding.tistory.com/entry/%EB%B0%B1%EC%A4%80-13549%EB%B2%88-%EC%88%A8%EB%B0%94%EA%BC%AD%EC%A7%88-3-java)
> [BOJ] 13549_숨바꼭질3 / 골드5 / 60분 / X

- week9/BOJ_2615/오목_한의정.java
- 백준 2615 - [오목](https://www.acmicpc.net/problem/2615)
<br/>
1. 검은 돌 위치 저장 리스트와 흰 돌 위치 저장 리스트를 생성한다.
2. 검은 돌 리스트를 돌며 각 검은 돌을 기준으로 가로,세로,대각선1(\), 대각선2(/) 방향에서 오목인지 확인하고, 오목이라면 가장 왼쪽 위에 있는 값을 전역변수에 저장하고 검은 돌의 점수가 올라가도록 했다.
3. 흰 돌 리스트도 검은 돌 리스트와 같은 방식으로 진행하며 점수를 구했다.
4. 검은 돌 점수와 흰 돌 점수가 같으면 0을, 검은 돌 점수가 더 크면 1과 검은 돌의 행렬 위치를, 흰 돌 점수가 더 크면 2와 흰 돌의 행렬 위치를 출력하도록 했다.
<br/>
저번보다 더 중복되는 코드가 많아지게 푼 것 같다...
육목이 아닌지 확인할 때 뒤쪽은 확인했는데 앞쪽 이전 칸의 값을 고려하지 않아 13%에서 틀렸었다...
양쪽 한 칸 이전 값과 이후 값 다 고려하는 것을 잊지 말자!!
<br/>
X
> [BOJ] 2615_오목 / 실버1 / 90분 / O

- week9/BOJ_2503/숫자야구_강한주.java
- 백준 2503 - 숫자야구
<br/>
1. 중요하다고 생각하는 포인트는 123~987까지의 수와<h3>직접 비교</h3>하는 것이다... 이 포인트를 찾지 못했다
2. 물어본 숫자와 123~987까지의 수를 비교해서 strike와 ball이 같으면 후보로 count한다
<br/>
1번을 생각해내지 못했다. 
내가 생각한 후보의 풀이는 
1. 각 자리수 첫째 자리, 둘째 자리, 셋째 자리를 나눠서
각 자리에 1~9까지의 후보를 두고 제거해가야되나? 
2. 사람이 풀 땐 strike가 많은 수부터 보면서 숫자를 추론하니까, strike를 내림차순으로 정렬해서 숫자 후보를 찾을까?
였다. 하지만 두 방법 모두 풀이가 너무너무 복잡해져서 도저히 실버3의 문제라고는 생각되지 않았다.... 
그런데도 계속 저 풀이방법에 얽매여서 결국 다른 풀이를 참조했다
<br/>
그냥 직접 일일히 비교하는 포인트 ‼️
> [BOJ] 2503_숫자야구 / 실버3 / 30분 / X

- week9/BOJ_15661/링크와스타트_한의정.java
- 백준 105661 - [링크와 스타트](https://www.acmicpc.net/problem/15661)
<br/>
부분 집합
- 부분 집합을 활용해 팀을 나눈다. ⇒ 방문 배열에서 선택된 사람은 스타트 팀에, 선택되지 않은 사람은 링크 팀에 넣는다.
- N명만큼 사람을 뽑았을 때, 스타트 팀과 링크 팀의 능력치를 계산하고 그 차이를 비교해 최솟값으로 갱신한다.
<br/>
- 36번째 줄 j를 0부터 시작하게 했더니 틀렸던 것 같다...
- 방문 배열에서 i번째 값과 j번째 값이 동일하면 같은 팀에 속해있다고 인식하고 pass 해야 하는데 이 부분을 캐치하지 못 했다..
<br/>
**부분 집합** 개념
- boolean[] 배열을 통해 선택 여부만 확인하고 넘어가 배열의 원소가 true인 경우에만 결과 배열에 넣어도 된다. ([참고](https://velog.io/@albaneo0724/Algorithm%EC%88%9C%EC%97%B4-%EC%A1%B0%ED%95%A9-%EB%B6%80%EB%B6%84-%EC%A7%91%ED%95%A9))
> [BOJ] 15661_링크와 스타트 / 골드5 / 50분 / X

- week10/BOJ_15489/파스칼삼각형_한의정.java
- 백준 15489 - [파스칼 삼각형](https://www.acmicpc.net/problem/15489)
<br/>
> 시간 복잡도 :
1. dp 배열을 채운다.
- 행 번호 = 열 번호인 칸 or 1번째 열에 있는 칸 ⇒ 1로 채운다.
- 그 외 나머지 칸 ⇒ 현재 칸 (i,j) = 왼쪽 위 칸 (i-1, j-1) + 바로 위 칸 (i-1 ,j)
```java
dp[i][j] = dp[i-1][j-1] + dp[i-1][j]
```
2. 점 (R,C) 부터 길이가 W인 정삼각형 범위의 합을 구한다.
- int형 변수 `tmp` : 열 j의 범위를 (현재 행 i - 꼭짓점 R)한 길이만큼 설정해 삼각형 모양만큼만 값을 얻기 위한 변수
<br/>
삼각형 모양으로 제한하기 위해 j의 범위를 재설정해주는 부분에서 시간이 좀 오래 걸렸다..
<br/>
역시나 풀고 보니 내가 또 어렵게 생각한 것이었는데 😂
합을 구하는 부분의 dp식은 아래와 같이 작성하면 된다.
```java
for(int i = 0 ; i < W ; i++) {
for(int j = 0 ; j <= i ; j++) {
sum += dp[R + i][C + j];
}
}
```
> [BOJ] 파스칼 삼각형 / 실버4 / 30분 / O

- week10/PGS_92342/양궁대회_한의정.java
- 프로그래머스 92342 - [양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)
<br/>
> DFS
1. 백트래킹으로 각 점수의 과녁에 화살 n개를 쏘는 조합을 구한다.
2. 백트래킹의 반복문은 아래 2가지 조건이 맞을 때만 돌도록 한다.
- 과녁에 라이언이 맞춘 화살 수가 어피치가 맞춘 화살 수보다 작을 때 (arrows[i] <= inof[i])
- 과녁 i에 어피치가 화살을 더 많이 쏜 경우에만 진행하도록 한다. (가지치기) 
3. 화살 n개를 모두 쐈을 때, 어피치와 라이언의 점수 차이를 구하고, 이 값이 최댓값보다 크다면 최댓값으로 변경하고, 이 때의 과녁 점수 배열 값을 정답 배열로 복사한다.
<br/>
- 가지치기 조건 생각해내기 ⇒ 조건을 반복문 안에 저렇게 넣지 않으면 시간초과가 발생하였다. (n=10이면 백트래킹에서 시간 초과가 발생하므로 사전에 미리 가지치기 하는 것)
- DFS인 것까지는 생각했는데 '_라이언이 가장 큰 점수 차이로 우승할 수 있는 방법이 여러 가지일 경우, 가장 낮은 점수를 더 많이 맞힌 경우를 return 해주세요_.' 이 조건을 어떻게 만족시켜야할지 고민이 되었다,,
<br/>
- **가지치기 조건** : 과녁 i에 라이언이 임의의 점수에서 어피치에게 점수를 따내기 전까지만 반복문이 돌게 하는 것!! 이미 라이언이 어피치보다 과녁을 많이 맞춰서 이겼는데 더 많이 쏴봤자 의미가 없기 때문이다.
- '_라이언이 가장 큰 점수 차이로 우승할 수 있는 방법이 여러 가지일 경우, 가장 낮은 …
> [PGS] 양궁대회 / level2 / 40분 / X

- week12/BOJ_9655/돌게임_한의정.java
- 백준 9655 - [돌 게임](https://www.acmicpc.net/problem/9655)
<br/>
돌 갯수 N이 홀수면 상근이가 이기고, 짝수면 창영이가 이긴다.
<br/>
X
<br/>
문제의 의도는 DP인 것 같아 [dp를 활용한 풀이](https://propercoding.tistory.com/21)도 찾아보았다.
> [BOJ] 9655_돌 게임 / 실버5 / 5분 / O

- week12/BOJ_1463/일로만들기_한의정.java
- 백준 1463 - [1로 만들기](https://www.acmicpc.net/problem/1463)
<br/>
> DP
`dp[i] : 숫자 i를 1로 만들기 위한 최소 횟수`
1. 크기가 N+1인 배열을 생성하고, 초기값을 설정한다. (`dp[1] = 0`)
2. 2부터 N까지 점화식을 채운다.
- 해당 칸을 먼저 이전 칸의 값+1 한 값으로 채운다. (`dp[i] = dp[i-1]+ 1`)
- 현재 숫자가 3의 배수라면, `dp[3으로 나눈 몫] +1`과 현재 칸의 값 中 작은 값으로 현재 칸을 갱신한다.
- 현재 숫자가 2의 배수라면, `dp[2로 나눈 몫] +1`과 현재 칸의 값 中 작은 값으로 현재 칸을 갱신한다.
3. dp[N]을 출력한다.
<br/>
점화식 찾기
<br/>
X
> [BOJ] 1463_1로 만들기 / 실버3 / 50분 / X

- week12/BOJ_9251/LCS_한의정.java
- 백준 9251 - LCS
<br/>
> DP
1. 크기가 [첫 번째 문자열 c1의 길이+1][두 번째 문자열 c2의 길이 +1]인 2차원 dp배열을 만든다.
2. 이 배열을 채운다.
- 만약 c1의 i번째 값 = c2의 j번째 값이 같다면, dp[i][j]의 값을 대각선 위쪽에 있는 값 +1한 값으로 채운다. →  `if(c1[i-1] == c2[j-1]) dp[i][j] = dp[i-1][j-1] + 1`
- 두 값이 다르다면, 왼쪽에 위치한 값과 위쪽에 위치한 값 중 큰 값으로 해당 칸을 채운다.
3. 마지막에 오른쪽 맨 아래 있는 칸의 값을 출력한다.
<br/>
- 점화식 규칙 찾기.. c1의 i번째 값과 c2의 j번째 값이 다르면 그냥 왼쪽에 있는 값 가져와쓰면 되는거 아닌가? 하고 했었다,,
<br/>
- [LCS 개념](https://loosie.tistory.com/379)
> [BOJ] 9251_LCS / 골드5 / 30분 / X

- week13/BOJ_13335/트럭_한의정.java
- 백준 13335 - [트럭](https://www.acmicpc.net/problem/13335)
<br/>
> 큐
1. 총 두 개의 큐
- 다리 위의 트럭들 저장용 큐 → 다리 길이 w만큼 0으로 채워두기
- 오른쪽에 위치한 트럭들 저장용 큐
2. 다리 위가 빌 때까지 해당 과정을 반복한다.
- 시간이 1초 소요되고
- 다리의 맨 앞에 있는 트럭을 내린다. 이 때, 큐에서 뽑은 트럭의 무게를 다리 위의 트럭들의 무게의 합에서 뺀다.
- 오른쪽에 트럭이 위치해 있다면, 해당 트럭의 무게와 현재 다리 위 트럭들의 무게의 합이 최대 하중보다 작거나 같을 때 해당 무게의 트럭을 다리 위로 올린다. 하지만 최대 하중보다 크다면, 다리 위에 아무 것도 안 올린다(=0 넣음)
<br/>
- 큐 사용할 아이디어를 생각하기까지 오래 걸린 듯
- 다리 위의 트럭들 저장할 큐를 길이가 w인 상태로 고정해둘 생각을 하지 못 했다.
<br/>
- 다리 위의 트럭들 저장할 큐를 길이가 w로 고정해두고, 비워두려면 0으로 채우는 것
> [BOJ] 13335_트럭 / 실버1 / 40분 / X

- week13/BOJ_1158/요세푸스문제_한의정.java
- 백준 1158 [요세푸스 문제](https://www.acmicpc.net/problem/1158)
<br/>
> 큐 (LinkedList로 큐를 선언해 idx 위치에 있는 값 제거할 수 있게 함)
1. 큐에 1부터 N까지 숫자를 넣는다.
2. 맨 처음 뽑을 K-1번째 원소를 출력한다.
3. 이후 큐가 빌 때까지 위치 인덱스를 `(현재 위치 인덱스 + K -1) % 큐의 크기` 한 값으로 변경하고, 변경한 해당 위치의 인덱스를 제거하고, 출력한다.
<br/>
X
<br/>
X
> [BOJ] 1158_요세푸스 문제 / 실버4 / 35분 / O

- week13/BOJ_13335/트럭_강아현.py
- 백준 13335 - 트럭
<br/>
- `cross_bridge` : w개의 트럭이 올라갈 수 있는 다리
- `weight` : 현재 다리 위에 있는 트럭들의 무게의 합
<br>
1. 다리를 다 지나간 트럭의 무게를 weight에서 뺀다.
2. 지나가지 않은 트럭이 다리에 올라갈 수 있는지 확인한다.
3. 2에서 올라갈 수 있으면, 다리에 트럭을 올린다.
4. 2에서 올라갈 수 없으면, 다리에 0을 추가한다.
5. 마지막 트럭이 다리를 건널 때까지의 시간을 추가하여 정답값을 출력한다.
<br/>
다리의 길이로 리스트를 활용하려고 생각을 했는데 구현하는 데까지 시간이 좀 걸렸다.
<br/>
x
> [BOJ]13335_트럭 / 실버1 / 50분 / O

- week14/BOJ_16234/인구이동_강아현.py
- 백준 16234 - 인구 이동
<br/>
> 시간 복잡도 : O(N^4)
> **bfs**
>
> - 현재 위치를 기준으로 상하좌우를 탐색하며 인구 차이가 L명 이상, R명 이하인 경우 q에 좌표를 추가한다.
>
> **update**
>
> - border는 연합을 이루고 있는 칸을 표시한 파라미터이다.
> - border == 1인 경우, 이 값을 문자열로 바꾸고 board의 값을 (연합의 인구수) / (연합을 이루고 있는 칸의 개수) 로 바꾼다.
1. visited, border를 매일 초기화한다.
2. end = 1로 초기화를 하며, 인구 이동이 있는 경우 이 값을 0으로 바꾼다. end == 1인 경우 인구 이동이 더이상 없는 경우이므로 while문을 탈출한다.
<br/>
x
<br/>
x
> [BOJ]16234_인구 이동 / 골드4 / 75분 / O

- week14/BOJ_16234/인구이동_한의정.java
- 백준 16234 - [인구 이동](https://www.acmicpc.net/problem/16234)
<br/>
> 시간 복잡도 : O(N^4) 
>  - move() 메소드 안의 2중 for문
>  - bfs() 메소드 안의 while루프
<br/>
인구 이동이 가능할 때까지 인구를 이동시켰다. (인구를 이동시킬 때마다 방문 배열은 매번 초기화)
<br/>
1. 인구 이동이 가능한지 판별하는 메소드
- 완전탐색을 통해 방문하지 않은 지점에 대해 4방향 탐색하며 국경선이 열렸는지 확인한다.
- _국경선 열림_ : 격자 범위 내에 있고, 두 나라 간 인구 차이가 L 이상 R 이하인 경우
- 국경선이 열렸다면 bfs로 이동하며 연합한다.
2. 인접한 국경선이 열린 나라끼리 이동하며 연합하는 메소드 (BFS)
- 리스트에 `연합한 나라의 x,y 좌표 & 인구 수`를 저장한다.
- 해당 위치에서 인접한 4방향 탐색 시 `방문한 적 없고, 두 나라 간 인구 차이가 L 이상 R 이하여서 이동 가능한 칸인 경우` 이동한다.
- 연합 국가가 2개 이상인 경우, 연합 이루는 각 칸의 인구 수를 갱신한다.
<br/>
X
<br/>
X
> [BOJ] 16234_인구 이동 / 골드4 / 60분 / O

- week16/BOJ_4963/섬의개수_한의정.java
- 백준 4963 - [섬의 개수](https://www.acmicpc.net/problem/4963)
<br/>
> BFS
w와 h가 0이 아닐 때 계속 아래 과정 1-3을 진행한다.
1. 격자를 입력받는다 (h: 행, w: 열)
2. 격자 내 모든 점을 돌면서, 방문한 적 없는 땅을 탐색하며 섬의 개수를 구한다. (BFS)
- 시작점에서부터 8방향 탐색하며 격자 범위를 벗어나지 않고, 방문한 적 없는 땅으로 이동하며 탐색한다.
3. 2에서 구한 섬의 개수를 출력한다.
<br/>
X
<br/>
X
> [BOJ] 4963_섬의 개수 / 실버2 / 30분 / O

- week16/BOJ_5547/일루미네이션_한의정.java
- 백준 5547 - [일루미네이션](https://www.acmicpc.net/problem/5547)
<br/>
> BFS
**벽이 아닌 칸을 기준으로 (0,0)부터 BFS탐색을 진행하며,
벽이 아닌 각 칸마다 맞닿은 6방향의 벽의 갯수를 저장하는 것이 포인트!!**
<br/>
그리고 이 때 맞닿은 6방향의 방향 좌표는 행이 [짝수/홀수]냐에 따라 다르게 설정해줘야 한다.
<br/>
각 칸마다 맞닿은 6방향(좌, 좌상, 우상, 우, 우하, 좌하)을 탐색하며
1) 격자 범위를 벗어나지 않는 인접한 칸이 벽인 경우, result 배열의 현재 칸의 값에 1을 더한다.
2) 격자 범위를 벗어나지 않는 인접한 칸이 방문한 적 없는 벽이 아닌 칸인 경우, 해당 칸으로 이동한다.
<br/>
- 벽이 있는 칸(1)을 기준으로 BFS 탐색을 수행할 생각을 했는데 이게 아니었다!
<br/>
- 벽이 없는 칸 기준으로 bfs 탐색 수행하며 각 칸에 인접한 벽 갯수 구하기
- 행이 홀수냐 짝수냐에 따라 인접한 칸 방향이 다르다는 것
> [BOJ] 5547_일루미네이션 / 골드4 / 30분 / X

- week16/BOJ_10711/모래성_한의정.java
- 백준 10711 - [모래성](https://www.acmicpc.net/problem/10711)
<br/>
> BFS (모래성이 **없는** 노드를 중심으로 탐색!)
1. 격자를 입력받을 때, 큐에 모래성이 **없는**(.) 위치를 저장한다.
2. BFS를 수행한다.
- 큐 사이즈만큼 큐에서 모래성이 없는 노드를 뽑고, 주변 8방향을 탐색한다.
- 8방향을 탐색했을 때, 인접한 칸이 모래성이라면 튼튼함을 -1한다.
- 튼튼함을 하나 뺐을 때 새롭게 모래성이 없어진 노드라면, 큐에 추가해 탐색한다.
<br/>
- BFS에서 왜 큐 사이즈만큼 원소 뽑아 8방향 탐색을 하는 거지?를 고민했다.. 이유는 **모든 모래성을 한 번에 처리하기 위함**이라고 한다.
- 모래성이 있는 위치를 큐에 저장해서 bfs를 할 생각을 했었다. (이런 풀이도 찾아보니 있긴 했다)
<br/>
- bfs에서 큐 사이즈만큼 모래성이 없는 노드를 뽑아서 주변 8방향을 탐색하고 하는 것
- 새롭게 모래성이 없어진 노드만 큐에 추가해 마저 탐색하는 아이디어,,
> [BOJ] 10711_모래성 / 골드2 / 60분 / X

- week17/BOJ_2217/로프_한의정.java
- 백준 2217 - [로프](https://www.acmicpc.net/problem/2217)
<br/>
> 그리디, 정렬
1. N개의 숫자들을 입력받고, 오름차순 정렬한다.
2. 정렬된 0~N-1개의 숫자를 사용하며, 본인 포함 뒷칸에 있는 원소들을 모두 사용해 병렬로 연결했을 때의 무게를 구한다. 이 값을 최댓값과 비교해 더 큰 값으로 갱신한다.
> 최대 무게 w = min(병렬 연결된 로프의 중량) * 병렬 연결된 로프 수→ rope[k] * (N - k)
<br/>
> 예) [12, 20, 30, 33, 35]
n = 0 일때 12 * 5 = 60 (12 20 30 33 35)
n = 1 일때 20 * 4 = 80 (20 30 33 35)
n = 2 일때 30 * 3 = 90 (30 33 35)
n = 3 일때 33 * 2 = 40 (33 35)
n = 4 일때 35 * 1 = 40 (35)
이 중 90이 제일 큰 값이므로, 이 값을 정답으로 출력한다.
<br/>
(가장 작은 값 * 배열의 크기)를 해서 최대 무게 w를 구할 수 있겠단 생각은 했는데 그 다음 원소부터는 어떻게 할지 생각을 하지 못 했다.
<br/>
w/k 식을 어디에 도대체 사용하는 거지? 했는데 `최대 무게(w) = 현재 위치의 로프에 걸리는 중량(arr[i]) * 현재부터 뒤까지 병렬 연결된 로프 수(N-k)` 이렇게 활용될 수 있군 했다.
> [BOJ] 2217_로프 / 실버4 / 30분 / X

- week17/BOJ_13305/주유소_한의정.java
- 백준 13305 - [주유소](https://www.acmicpc.net/problem/13305)
<br/>
> 그리디 (O(N))
1. 인접한 두 도시를 연결하는 도로의 길이를 입력받는다. (long형으로!)
2. 각 주유소의 리터 당 가격도 입력받는다. (얘도 long형으로)
3. 주유소 가격 배열을 반복문으로 돌면서 주유 가격을 비교하며 더 낮은 가격만큼 주유한다.
```
long sum = 0;
long min = gas[0];  // 낮은 주유 가격
for(int i = 0 ; i < dist.length ; i++) {
// 주유 가격 비교해 더 낮은 주유 가격만큼 주유
if(gas[i] < min) {
min = gas[i];
}
sum += min * dist[i];
}
```
<br/>
- 주유 가격을 최소로 하기 위해 주유소와 그에 따른 거리를 구하는 경우의 수를 모두 다 구해 보고 비교해야 하나?라고 생각했다.
(예를 들어 주유소가 3개 있다고 할 때 [1번 주유소 1번만 방문하는 경우, 1번 주유소와 2번 주유소 방문하는 경우, 1-3번 주유소 다 방문하고 가는 경우] 이렇게...)
<br/>
거리 값을 변경해서 사용할 생각을 하지 말자!
→ 그냥 주유 가격 배열을 돌면서 현재 주유 가격보다 낮을 때 주유 가격을 더 낮은 값으로 갱신하고, 그 가격으로 현재 도로의 길이만큼 이동시키면 되는 것이었다..
> [BOJ] 13305_주유소 / 실버3 / 60분 / X

- week17/BOJ_11000/강의실배정_한의정.java
- 백준 11000 - [강의실 배정](https://www.acmicpc.net/problem/11000)
<br/>
> 시간 복잡도 : O(N log N)
1. 시작 시간 s와 종료 시간 t를 저장할 2차원 배열을 만든다.
2. 2차원 배열을 정렬한다.
- 시작 시간이 같다면, 종료 시간 기준 오름차순 정렬한다.
- 시작 시간이 다르다면, 시작 시간 기준 오름차순 정렬한다.
3. 배열 내의 값을 종료 시간 기준 오름차순 정렬한다. 이를 위해 **_우선순위 큐_**를 사용한다.
4. 첫 번째 종료 시간 값을 넣고, 두 번째 원소부터 마지막 원소까지 아래 과정을 반복한다.
- 가장 빨리 끝나는 강의의 종료 시간(pq.peek())과 배정 안 된 강의의 시작 시간 (arr[i][0])을 비교해 뒷 값이 더 크다면, 가장 빨리 끝나는 강의를 제거한다.
- 배정되지 않은 강의의 종료 시간을 우선순위 큐에 넣는다.
5. 필요한 강의실 수 = 우선순위 큐에 남은 강의 수다.
<br/>
우선순위 큐를 사용해서 종료 시간 기준 오름차순 정렬을 계속하면서 값을 빼면서 사용할 생각을 하지 못 했다.
<br/>
계속 종료 시간을 오름차순 정렬하기 위해 우선순위 큐에 종료 시간 값을 저장하고 활용하는 아이디어 (제거하고 추가하는 아이디어)
> [BOJ] 11000_강의실 배정 / 골드5 / 60분 / X

- week18/BOJ_11054/가장긴바이토닉부분수열_한의정.java
- 백준 11054 - [가장 긴 바이토닉 부분 수열](https://www.acmicpc.net/problem/11054)
<br/>
> DP → 시간 복잡도 : O(N)
최장 증가 부분 수열의 최댓값과 최장 감소 부분 수열의 최댓값을 더한 후, 중복되는 값 1개를 뺀 값을 정답으로 한다.
1. 최장 증가 부분 수열 구하기
- 왼쪽(1)에서 오른쪽(N)으로 진행하며 최장 증가 부분 수열을 구한다.
```
private static void LIS() {
for(int i = 1 ; i <= N ; i++) {
for(int j = 1 ; j < i ; j++) {  // 비교 대상 : 1 ~ i-1번 원소
if(arr[i] <= arr[j])    continue;
if(dp1[i] < dp1[j] + 1)
dp1[i] = dp1[j] + 1;
}
}
}
```
2. 최장 감소 부분 수열 구하기
- 최장 증가 부분 수열을 오른쪽(N)에서 왼쪽(1)으로 진행하면서 구하면 된다.
```
private static void LDS() {
for(int i = N ; i >= 1; i--) {  // 맨 뒤에서부터 시작
for(int j = N ; j > i ; j--) {  // 맨 뒤에서 i 이전 원소들 탐색
if(arr[i] <= arr[j])    continue;
if(dp2[i] < dp2[j] + 1)
dp2[i] = dp2[j] + 1;
}
}
}
```
<br/>
- 최장 감소 부분 수열 인덱스를 적다가 헷갈렸다,,
<br/>
- dp를 양 옆에서 진행해서 두 값을 둘 다 사용할 줄 몰랐다,,
- …
> [BOJ] 11054_가장 긴 바이토닉 부분 수열 / 골드4 / 40분 / X

- week18/BOJ_12872/플레이리스트_한의정.java
- 백준 12872 - [플레이리스트](https://www.acmicpc.net/problem/12872)
<br/>
> 시간 복잡도 : O(NP)
```
dp[i][j] : i개의 음악을 플레이리스트에 넣고, j개의 음악 종류를 사용했을 때의 경우의 수
```
음악은 **플리에 넣었는지 여부**에 따라 2가지 종류로 나눌 수 있다.
 
1. 플리에 **넣지 않은** 음악인 경우
- 아직 플리에 넣지 않았으므로, 같은 노래 사이에 M개의 곡이 있어야 한다는 2번 조건은 고려할 필요가 없다.
- 대신 이전 모든 경우의 수들에 추가될 수 있으므로 아래와 같은 점화식이 도출된다.
```
dp[musicNum][savedMusicNum] += dp[musicNum - 1][savedMusicNum - 1] + (N - savedMusicNum + 1)
```
 
 
2. 플리에 **넣은** 음악인 경우
- 같은 노래 사이에 M개의 곡이 있어야 한다는 2번 조건을 만족해야 한다.
- 사용된 곡 종류가 M개를 초과하는 경우, 2번 조건을 충족해야 하므로 아래와 같은 점화식을 도출할 수 있다.
```
dp[musicNum][savedMusicNum] += dp[i-1][j] * (savedMusicNum - M)
```
<br/>
- 점화식 도출하기
<br/>
어떤 집합에서 아무거나 하나를 놓으면 된다
= 어떤 집합의 원소의 수를 곱한다
> [BOJ] 12872_플레이리스트 / 골드1 / 30분 / X

- week20/BOJ_17142/연구소3_한의정.java
- 백준 17142 - [연구소 3](https://www.acmicpc.net/problem/17142)
<br/>
> 조합(백트래킹) + BFS
<br/>
[필요 자료구조]
- 바이러스 객체 ⇒ (행,열, 거리 값) 저장
- 인접한 4방향 탐색할 dx/dy 배열
- 바이러스 위치 저장 리스트
- 초기 빈 칸 개수 zeroCnt
<br/>
1. 연구소의 상태를 입력받는다.
- `빈 칸(0)`인 경우, zeroCnt에 +1 한다.
- `바이러스(2)`인 경우, 해당 위치와 0을 리스트에 저장한다.
2. 빈 칸의 갯수가 0이라면, 0을 출력하고 종료한다. / 그게 아니라면, 바이러스 위치 중 M개를 뽑아 바이러스를 심고 퍼뜨리는 데 걸리는 최소 시간을 계산한다.
1) M개 바이러스 뽑기 > **_조합 (백트래킹)_**
2) 바이러스 퍼뜨리기 > **_BFS_**
- M개 바이러스를 뽑았으면, 해당 위치들은 방문 처리하고, 큐에 추가한다.
- `[이동 X인 경우]` 해당 칸에서 이동하려는 인접한 다음 칸이 (격자 범위를 벗어나거나, 방문한 적 있거나, 벽인 경우)
- `[이동 O인 경우]` 이동하려는 칸이 빈 칸(0)이면, 방문하러 갈 거니까 빈 칸 개수를 줄인다.
&nbsp; &nbsp; ▷ 빈 칸 갯수가 0이 된다면, 정답과 `퍼뜨리는 데 걸린 시간+1` 둘 중 더 작은 값으로 정답을 갱신한다.
&nbsp; &nbsp; ▷ 그게 아니라면, 이동할 칸의 위치를 방문 처리하고, 시간은 +1해서 큐에 추가해 탐색한다.
<br/>
- 왜 전역변수 zeroCnt를 그대로 사용하지 않고 BFS 함수에서 …
> [BOJ] 17142_연구소 3 / 골드3 / 60분 / x
