week1/BOJ_1931/회의실배정_강아현.py

- 백준 1931 - 회의실 배정
<br/>
1. 회의가 끝나는 시간을 기준으로 오름차순 정렬
2. 다음 회의 시작 시간이 현재 시간보다 크거나 같은 경우 cnt += 1 (현재 시간은 다음 회의 시작 시간으로 변경)
<br/>
X
<br/>
X

[BOJ] 1931_회의실 배정 / 실버1 / 20분 / O

---

week1/BOJ_1251/단어나누기_강아현.py
week1/BOJ_1449/수리공항승_강아현.py
week1/BOJ_1931/회의실배정_강아현.py
week1/BOJ_2470/두용액_강아현.py

- 백준 2470 - 두 용액
<br/>
1. 투 포인터를 쓰기 위해서 용액의 특성값을 오름차순으로 정렬한다.
2. 두 용액의 합을 interval_sum으로 지정하고
3. abs(interval_sum)이 현재 특성값 합보다 작은 경우 이 sum을 현재 특성값 합으로 변경
4. interval_sum이 0보다 작은 경우에는 start 포인터를 +1
5. 이외의 경우에는 end 포인터를 +1
<br/>
X
<br/>
투 포인터 알고리즘을 다시 공부하게 되었다. 이중 for문을 사용하지 않고 부분합을 찾을 수 있는 방법에 대해 생각할 수 있었다.

[BOJ] 2470_두 용액 / 골드5 / 50분 / O

---

week2/BOJ_10799/쇠막대기_한의정.java

- 백준 10799 - 쇠막대기
- 사용 자료구조 : 스택
1. 열린 괄호인 경우, 스택에 열린 괄호를 넣는다.
2. 닫힌 괄호인 경우, **직전 괄호를 확인하며** 아래 2가지 경우로 나눠 생각한다.
- 직전 괄호가 열린 괄호인 경우, 레이저를 의미한다. 이 때 정답에 열린 괄호 갯수 (= 현재 스택 크기)만큼 더한다.
- 직전 괄호가 닫힌 괄호인 경우, 쇠막대기를 의미한다. 이 때 정답 + 1한다.
레이저 처리와 쇠막대기 처리를 어떻게 할지 고민하다가 시간을 많이 소요했고, 결국 다른 풀이를 참고해 작성하였다. (https://delay100.tistory.com/3)
직전 괄호를 활용해 처리할 생각을 하지 못 했다.
X

[BOJ] 10799_쇠막대기 / 실버2 / 30분 / X

---

week2/BOJ_10828/스택_강아현.py

- 백준 10828 - 스택
<br/>
1. Stack Class 생성하여 사용
<br/>
X
<br/>
X

[BOJ] 10828_스택 / 실버4 / 10분 / O

---

week2/BOJ_10828/스택_한의정.java

- 백준 10828 - 스택
문제에서 하라는 대로 순서대로 작성했다.
- 스택 자료구조 활용
- **`stack.peek()`** : 맨 위 원소 출력만
- **`stack.pop()`** : 맨 위 원소 출력 + 제거
- **`stack.size()`** : 스택 크기 출력
- **`stack.isEmpty()`** : 스택이 비어있는지 boolean형으로 결과 나타냄 (비어있으면 true, 아니면 false)
- 스택이 비어있는지 확인할 때 삼항 연산자 사용
- **`stack.isEmpty() ? -1 : stack.peek()`**  → 스택이 비어있으면 -1 출력, 안 비어있으면 맨 위 원소 출력
- 출력할 때 StringBuilder 사용해서 한 번에 출력
X
X

[BOJ] 10828_스택 / 실버4 / 11분 / O

---

week2/BOJ_10828/스택_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 9012 - 괄호
<br/>
1. '('가 나오는 경우에는 리스트에 저장
2. ')'가 나오는 경우에는 left 리스트에서 마지막 원소 pop
3. ')'가 나오는 경우 left 리스트가 비어있는 경우 right 리스트에 append 후 break
4. left 리스트와 right 리스트 중 하나라도 비어있지 않다면 "NO"
<br/>
X
<br/>
X

[BOJ] 9012_괄호 / 실버4 / 10분 / O

---

week2/BOJ_10828/스택_강아현.py
week2/BOJ_1966/프린터큐_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 1966 - 프린터 큐
<br/>
1. 문서의 인덱스와 문서의 중요도 리스트를 각각 만들어 같이 돌린다.
2. 문서가 출력될 때 출력되는 문서의 인덱스와 알고자하는 문서 위치가 동일한 경우 프린트 순서 출력 후 break
<br/>
X
<br/>
인덱스를 리스트로 따로 만들어서 돌리는 것보다 `enumerate()`로 리스트를 만들면 중요도와 인덱스를 한번에 저장할 수 있다.

[BOJ] 1966_프린터 큐 / 실버3 / 10분 / O

---

week2/BOJ_10828/스택_강아현.py
week2/BOJ_1966/프린터큐_강아현.py
week2/BOJ_2346/풍선터뜨리기_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 2346 - 풍선 터뜨리기
<br/>
1. 풍선의 인덱스와 풍선 안 종이의 값을 enumerate로 리스트에 같이 저장한다.
2. 풍선을 터뜨릴 때 리스트를 회전해서 popleft()로 터뜨린다.
3. 풍선 안 종이의 값이 양수인 경우, 시계방향으로 (값-1)만큼 회전한다.
4. 풍선 안 종이의 값이 음수인 경우, 반시계방향으로 (값)만큼 회전한다.
<br/>
X
<br/>
X

[BOJ] 2346_풍선 터뜨리기 / 실버3 / 10분 / O

---

week2/BOJ_10799/쇠막대기_강아현.py
week2/BOJ_10828/스택_강아현.py
week2/BOJ_1966/프린터큐_강아현.py
week2/BOJ_2346/풍선터뜨리기_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 10799 - 쇠막대기
<br/>
1. '('로 쇠막대기가 쌓여있는 개수를 확인했다.
2. i == ')'일 때 i-1 == '('인 경우는 레이저가 있는 부분이기 때문에 pipes pop 후 pipes의 length를 정답값에 더해준다.
<br/>
레이저와 파이프의 수를 동시에 처리할 수 있는 방법에 대한 고민을 하는데 시간을 많이 소요했다. 
<br/>
X

[BOJ] 10799_쇠막대기 / 실버2 / 30분 / O

---

week2/BOJ_1966/프린터큐_한의정.java

- 백준 1966 - 프린터 큐
1. (위치, 중요도)를 저장할 객체를 생성하고, 입력 받아 큐에 값을 저장한다.
→ 자바는 Queue에 get 메소드가 없어 **LinkedList**로 선언해 get 메소드 활용😂
2. 전체 큐를 돌면서, 맨 앞 원소의 중요도가 가장 큰지 boolean 변수를 활용해 판단한다.
→ 맨 앞 원소를 일단 뽑는다.
┕ 1) 만약 뒤쪽에 더 큰 중요도를 가진 원소가 있다면, 맨 앞 원소와 그 위치 이전까지의 원소들을 모두 뒤로 보낸다.
┕ 2) 맨 앞 원소의 중요도가 가장 크다면, 출력 위치 + 1하고, 이 때의 위치가 M이라면 반복문을 종료하고 정답을 출력한다.
- Queue는 get 메소드가 없다는 사실을 간간이 잊는다...
- 이전까지의 원소들을 어떻게 뒤로 보낼지 고민하는 시간이 오래 걸렸다. → 입력 크기가 크지 않아서 완전탐색으로 그냥 이전까지의 값들을 모두 뒤로 보내도 되는 것이었다..
X

[BOJ] 1966_프린터큐 / 실버3 / 50분 / O

---

week2/BOJ_2346/풍선터뜨리기_한의정.java

- 백준 2346 - 풍선 터뜨리기
> 시간 복잡도 : 
- 필요 자료구조 : **Deque**
1. 덱에 위치와 적힌 값을 저장한다.
2. 덱을 순회하며, 덱 맨 앞에 있는 풍선 번호를 저장하고, 뽑고, 꺼내서 적힌 값 next만큼 이동한다.
- 만약, 덱이 빈 상태가 된다면, 남아있는 풍선이 없으므로 종료한다.
- 종이에 적힌 값이 양수라면, 맨 앞에 있는 값을 뽑아 뒤쪽으로 넣는다.
- 종이에 적힌 값이 음수라면, 맨 뒤에 있는 값을 가져와 앞쪽으로 넣는다.
- 덱을 LinkedList로 선언해서 하려고 했는데 잘 안 됐다. (메모리 초과 발생)
- LinkedList로 풀려고 할 때, 음수 값만큼 이동 시 리스트 크기만큼 더해주려고 했는데, 변경 전 리스트 사이즈를 더해줘야 맞는데 변경 후 리스트 사이즈 크기만큼 더해서 틀렸다.
X

[BOJ] 2346_풍선터뜨리기 / 실버3 / 50분 / X

---

week2/BOJ_10799/쇠막대기_강아현.py
week2/BOJ_10828/스택_강아현.py
week2/BOJ_1966/프린터큐_강아현.py
week2/BOJ_2346/풍선터뜨리기_강아현.py
week2/BOJ_2800/괄호제거_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 2800 - 괄호 제거
<br/>
> 시간 복잡도 :
> **핵심**
- 괄호의 인덱스
- Combinations
1. 올바른 괄호인 경우, 괄호의 인덱스를 리스트에 저장한다.
2. 1부터 괄호의 개수만큼 괄호를 제거할 수 있는 모든 경우의 수를 combinations로 구한다.
3. combinations에 대해 원본 string 리스트의 값을 수정한 후 join하여 문자열로 만든 후 정답에 추가한다.
<br/>
괄호를 제거할 수 있는 모든 경우의 수를 combinations로 구해야겠다는 아이디어는 도출.
_괄호의 인덱스를 활용하여 조합을 적용하는 방법은 생각해내지 못했다._
<br/>
X

[BOJ] 2800_괄호 제거 / 골드5 / 120분 / X

---

week2/BOJ_10828/스택_강한주.java

- 백준 10828 스택
<br/>
> 시간 복잡도 : 모르겠어요 O(N)...?
1. 스택을 만들었다
2. 자바에 있는 스택메서드 push,peek,pop,isEmpty,size등을 통해 풀었다
<br/>
함수를 다 따로 만들어서 풀까 했는데 귀찮아서 조건문을 많이 썼더니 코드가 더러워 보인다. 앞으로는 메서드를 작성하도록 노력해 보겠다!
<br/>
내용

[BOJ] 10828_스택/실버4/20분/O

---

week2/BOJ_9012/괄호_강한주.java

- 백준 9012 괄호
<br/>
> 시간 복잡도 :O(N)
1. String을 하나씩 읽으면서 '('면 스택에 push하고  ')'면 스택에서 pop을 했다
2. 이떄 주의점은 pop을 할때 스택이 비어있는지 미리 체크를 하는 것이다
<br/>
<br/>

[BOJ] 9012_괄호/실버4/10분/O

---

week2/BOJ_1966/프린터큐_강한주.java

- 백준 1966 프린터
<br/>
1. 프린트큐(queue), 문서의 순서를 저장하는 큐(docQueue), 문서의 중요도 정렬을 하기 위한 배열(arr), 내가 찾는 m번째 문서가 언제 출력되는지 알기위해 쓴 answerQueue
2. 현재 프린터큐의 맨 앞에 들어있는 수와 문서의 중요도를 정렬한 배열 arr을 비교하면서 
가장 큰 중요도를 찾으면 queue,docQueue 에서poll()해서 큐에서 수를 없애고 만약  없앤 문서가 내가 찾고있는 m번째 문서라면 비교를 종료한다
<br/>
1. 프린터큐에서 가장 큰 수를 찾는걸 어떻게 하지?
2. 프린터큐에는 문서의 중요도밖에 안써있는데(예:1,3,2,4) push,pop과정을 하면 문서의 순서가 뒤죽박죽으로 섞여서 뭐가 몇번째 문서였는지 어떻게 알지?( 큐가 3,2,4,1로  바뀌었을때 0번째 문서인 1이 현재 4번째에 있다는걸 기록해야하나?) 
라는 크게 두가지 의문이 있었다. 
첫번째는 그냥 **배열 arr**을 선언해서 프린터큐에 있는 수를 그대로 넣고 정렬해서 찾았다
두번째는 **프린터큐 외에 문서들의 순서가 저장되어 있는 큐를 선언**(docQueue)해서 프린터큐의 맨앞의 숫자가 pop()되면 docQueue의 맨앞 숫자도 pop해서 순서를 맞춰줬다 
아무리 생각해도 너무 복잡하게 푼 것 같다. 다른 풀이를 찾아보고 내일 스터디시간에 말해야겠다 
<br/>
1. Queue를 생성하려면 LinkedList를 써야한다

[BOJ] 1966_프린터큐/실버3/30분/O

---

week2/BOJ_2346/풍선터뜨리기_강한주.java

- 백준 =2346 풍선터뜨리기
<br/>
> 시간 복잡도 :O(N^2)
1. 큐 2개(ballon,paper)을 이용했다
2. 처음에 나온 종이값이 양수면 종이값-1만큼  poll해서 다시 add하고 , 음수면 paper.size()+종이값 만큼 poll해서 다시 add했다 (-3 2 1 4 5의 -3에서 왼쪽으로 3칸갈때 5-3=2, 2번 poll해서 add하면 된다)
<br/>
계속 메모리 초과가 떠서 결국 해결을 못했다. 
다른 사람의 풀이를 보니 Deque(ArrayDeque)를 사용했던데 나는 Queue(LinkedList)를 2개를 사용한 차이점이 있었다.
Queue하나를 더 사용해서 메모리 초과가 발생한건가? 
ArrayDeque가 LinkedList에 비해 훨씬 더 적은 메모리를 사용하는건가?  
<br/>

[BOJ] 2346_풍선터뜨리기/실버3/50분/X

---

week2/BOJ_10799/쇠막대기_강한주.java

- 백준 10799 쇠막대기
<br/>
1. 스택을 만들어서 '('가 나오면 push
2. ')'가 나왔을때 일단 pop을 하고  ')' 바로 전에 '('가 나왔다면 
레이저이기 때문에 지금까지 스택에 쌓인 stk.size()를 더한다.
[ '('가 나오면 새 막대기가 있다는 뜻이므로 만약 '('가 3번 나온후 레이저가 나왔을때 3개의 막대기는 잘린다. 따라서  stk.size()를  더해야한다. ]
')' 바로 전에 ')'가 나왔다면 단순히 하나의 막대기를 나타내므로 +1한다.
<br/>
')'가 나왔을때 pop을 하는것까진 알겠는데, 
')'의 전에 어떤 괄호가 나왔는지에 따라  분기되는걸 생각하지 못했다. 
<br/>
먼저 레이저가 나왔을때,  잘린 막대기의 수 변화를 관측해보자. 안 풀릴 것이다.
그러면 더 나아가서 ')'가 나왔을때마다 막대기의 수가 어떻게 변하는지 생각해보자

[BOJ] 10799_쇠막대기/실버2/40분/X

---

week2/BOJ_2504/괄호의값_강한주.java

- 백준 2504 괄호제거
<br/>
> 시간 복잡도 :O(N)
1. 분배법칙을 활용
2.이걸 어떻게 설명할지 좀 더 고민한 후에 쓰겠다  
<br/>
분배법칙을 활용할 생각을 못헀다 또한 처음에 3중조건문이 쓰여서 당연히 이렇게 복잡하게 안풀겠지... 했는데 그렇게 푸는것도 정답이 됐다.  일단시도해보자....
근데 분배법칙으로 풀 생각은 도대체 어떻게 하는지 궁금하다
<br/>
괄호를 다 숫자로 바꿔가며 무슨 법칙이 있나 관찰해봐야겠다

[BOJ] 2504_괄호의값/골드5/90분/X

---

week2/BOJ_2504/괄호의값_한의정.java

- 백준 2504 - 괄호의 값
1. 여는 괄호('(', '[')일 경우, 스택에 여는 괄호를 넣는다.
2. 닫는 괄호인 경우, **현재 위치 바로 전 위치의 문자를 확인**해 결과를 갱신한다.
- 현재 위치 바로 전 위치의 문자가 여는 괄호인 경우, 결과값에 더하고, 2 또는 3으로 나눈다.
- 그게 아니라면, 그냥 2 또는 3으로 나누기만 한다.
- 분기 조건이 많아서 헷갈렸다.
- 숫자가 나란히 있을 때 어떻게 해야 좋을지 고민했다..
- 스택이나 큐 문제는 닫는 괄호일 때, 분기를 나누고 **이전 idx의 문자열까지 확인해 결과를 갱신**하는 경우가 많은 듯하다..

[BOJ] 2504_괄호의값 / 골드5 / 60분 / X

---

week2/BOJ_10799/쇠막대기_강아현.py
week2/BOJ_10828/스택_강아현.py
week2/BOJ_1966/프린터큐_강아현.py
week2/BOJ_2346/풍선터뜨리기_강아현.py
week2/BOJ_2504/괄호의값_강아현.py
week2/BOJ_2800/괄호제거_강아현.py
week2/BOJ_9012/괄호_강아현.py

- 백준 2504 - 괄호의 값
<br/>
> 시간 복잡도 :
**올바른 괄호인지 판단 + 괄호에 따라 계산**
1. 여는 괄호( ( , [ )의 경우에는 (인 경우 누적값에 x2를 해주고, [인 경우 누적값에 x3을 해준다.
2. 닫는괄호(  ),  ] )의 경우에는 )인 경우 정답값에 누적값을 더해주고 누적값을 2로 나눈다.
3. ]인 경우 정답값에 누적값을 더해주고 누적값을 3으로 나눈다.
4. 올바른 괄호가 아니라면 정답값을 0으로 바꾼다.
<br/>
누적되는 값을 처리하는 것에 시간을 많이 썼다. 괄호가 누적될 때 곱해지는 것을 괄호가 닫힐 때 나눠줘야 한다는 부분에 대한 생각을 해내는 것이 어려웠다.
<br/>
X

[BOJ] 2504_괄호의 값 / 골드5 / 90분 / O

---

week2/BOJ_2800/괄호제거_강한주.java

- 백준 2800-괄호제거 
<br/>
1. class Pair와 stack을 이용해서 '(' 와 ')'쌍이 나올때의 인덱스를 기록했다
2. backtracking 알고리즘을 이용해 괄호를 제거하고 출력한다
<br/>
왜 Backtracking 알고리즘을 쓰는지 아직 모르겠다 !.... 공부하고 이 부분은 더 보충하도록 하겠다 !
<br/>

[BOJ] 2800_괄호제거 / 골드5 / 100분 / X

---

week3/BOJ_4396/지뢰찾기_한의정.java

- 백준 4396 - [지뢰 찾기](https://www.acmicpc.net/problem/4396)
- 사용 자료구조
- char형 2차원 격자 배열
- boolean형 2차원 방문 배열
- 지뢰 갯수 저장할 int형 2차원 배열
1. 지뢰 위치를 2차원 char형 배열로 입력받는다.
2. 열린 칸과 안 열린 칸을 입력 받는다.
- 해당 칸이 열렸을 경우, 해당 칸은 방문 처리한다.
- 지뢰가 아닌 칸이 열린 경우, 8방향을 돌며 주변 지뢰 갯수를 센다.
```java//현재 위치 주변의 지뢰 갯수 세는 함수
private static void countBombs(int x, int y) {
for(int d = 0 ; d < 8 ; d++) {
int nx = x + dx[d];
int ny = y + dy[d];
if(!inRange(nx, ny))    continue;   // 격자 범위 벗어나면 pass
if(board[nx][ny] == '*') {
ans[x][y]++;
}
}
}
```
- 지뢰인 칸이 열린 경우, 입력받을 때 지뢰였던 칸은 '*'로 출력하게 한다. → boolean 변수 활용해 지뢰인 칸 열렸는지 판별
3. 출력한다.
- 지뢰 안 건드린 경우, 방문 안 한 모든 칸을 '.'으로 출력한다.
- 지뢰를 건드린 경우, 방문 안 한 칸 中 지뢰인 칸은 '*'으로 출력한다.
<br/>
- 지뢰인 칸이 열린 경우, 바로 break을 했더니 15%에서 틀리고 결과가 제대로 나오지 않았다. 그래서 break를 없앴더니 바로 맞았다,,
[(반례 …

[BOJ] 4396_지뢰찾기 / 실버4 / 60분 / O

---

week3/BOJ_1913/달팽이_한의정.java

- 백준 1913 - [달팽이](https://www.acmicpc.net/problem/1913)
- 맨 왼쪽 위 (0,0) 위치에서부터 반시계 방향으로 격자를 돌며 칸을 채운다.
- 격자 이동 방향은 (0,0)부터 시작해 이미 방문한 칸이거나 격자 범위를 벗어난 칸인 경우 **아래 → 오른쪽 → 위쪽 → 왼쪽 순으로 방향 전환**하게 했다.
┕ `dir = (dir + 1) % 4`
- 자꾸 범위 벗어났다고 에러 떠서 (ArrayIndexOutOfBoundsException) 시간이 좀 더 걸렸다.
- 코드 앞뒤나 위아래 순서에 따라 틀릴 수 있어서 잘 생각해봐야했다,,,
X

[BOJ] 1913_달팽이 / 실버3 / 70분 / O

---

week3/BOJ_20546/기적의매매법_강한주.java

- 백준 20546 기적의 매매법
<br/>
> 시간 복잡도 :
1. 준현이는 첫날부터 주식을 살 수 있는만큼 구매하므로 살 수 있는지 없는지 여부를 먼저 따지고 , 살 수 있으면 산다.
2. 성민이는 주식이 오를때를 기록하는 변수up과 주식이 떨어질때 기록하는 변수 down을 선언하였다. 
3. 반복문을 돌며 up>=3 일 경우 성민이는 가지고 있는 주식을 다 판다. 반면 down <= -3일 경우 주식을 전량매수한다. 
4. 이때 준현이와 성민이 모두 주식을 살 떄 , 그 날 산 주식의 양을 기록하는 변수 buyStock이 필요하다. 이 변수를 안쓰고 그냥 jun -= stock[i]*junNum(준현이가 지금까지 산 주식의 양) 라고 하면 junNum이 누적이 되므로 틀린 답이 된다. 
<br/>
성민이가 투자할때 3일간 주가가 오르거나 내릴때 변수를 어떻게 설정해야할지 고민에 빠졌다. 원래 int continous = 0; 이라는 변수를 설정하여 주가가 오르면 ++ 주가가 떨어지면 --를 하고 
contious==3 , continous ==-3 일때 전량매도,전량매수를 하고 continous = 0;으로 했다. 
하지만 그럴경우 
연속으로 4,5... 일째 주가가 오르거나 떨어지면 풀 수가 없게 된다.
<br/>
변수 설정을 잘 해보자 ,, ,다른사람풀이도 봐야할 듯

[BOJ] 20546_기적의매매법/실버5/55분/O

---

week3/BOJ_4396/지뢰찾기_강한주.java

- 백준 4396 - 지뢰찾기
<br/>
> 시간 복잡도 :O(N^3)
1. 처음입력한 지뢰가 있는 배열 arr과 내가 뽑기를 한 배열 checked를 사용한다
2. arr과 checked 배열을 비교해가며 
(1) 내가 뽑았는데 지뢰가 없는 경우 
(2) 내가 뽑았는데 지뢰가 있는 경우
(3) 내가 뽑지 않은 경우 
로 나눠가며 푼다
3. 내가 뽑았는데 지뢰가 있으면 flag = true; 로 하고 지뢰가 없으면 내 주위 8방향에 지뢰가 몇 개 있는지 체크해야 한다
4. dx,dy배열을 선언해서 현재 위치에서 **_8방향으로 각각 움직이는 시뮬레이션을 돌려본다_**
5. **_시뮬레이션을 돌릴때 행과 열의 위치가 0보다 크거나 같고 arr.length보다 작아야한다._**
6. 시뮬레이션 결과 주위에 지뢰가 카운트되면 coun++해서 결과를 return 한다
<br/>
1. 문제에서 "지뢰가 있는 칸이 열렸다면 지뢰가 있는 모든 칸이 별표(*)로 표시되어야 한다. 다른 모든 지점은 온점(.)이어야 한다" 
이 부분을 다른 모든 지점은 온점이라길래 주변에 count한 지뢰의 수 결과를 무시하고  지뢰를 제외한 모든 부분을 온점(.) 으로 표시 해야하는 줄 알았다... . **문제 그림을 보면 알 수 있는건데 !!!!!** 계속 답이 안나와서 결국 다른 풀이를 찾아봤다
2. 지뢰의 수를 count한 결과는 int 형인데 어떻게 char형으로 반환할지 고민했다. 
(char)(count + '0') 을 쓰는 걸 잊지 말자 
3. 배열을 입력 받을 때 8줄씩 입력 받는 건데 처음에 2중 for문을써서 총 64번 …

[BOJ] 4396_지뢰찾기 / 실버4 / 60분 / X

---

week3/BOJ_1913/달팽이_강한주.java

- 백준 1913 - 달팽이
<br/>
> 시간 복잡도 :O(N^2)
1. 끝번호 n*n부터 시작해서 1까지 숫자를 적는걸 목표로 했다
2. 방향이 아래->오른쪽->위->왼쪽->아래->오른쪽.... 이렇게 반복되므로 그에 맞는 배열 dx,dy를 선언했다
3. 현재 나의 위치와 방향을 저장할 변수 curX,curY,dir을 사용하였다
4. 시뮬레이션을 돌려 내가 다음에 갈 칸이 유효하지 않으면(isValid 사용) 방향을 바꾼다
<br/>
또 Scanner을 사용하다 시간초과가 났다 .  이번엔 정말 자바입출력에 대해 공부하고 자도록하겠다...
<br/>

[BOJ] 1913_달팽이 / 실버3 / 40분 / O

---

week3/BOJ_20207/달력_강한주.java

- 백준 20207 - 달력
<br/>
> 시간 복잡도 :O(N^3)
1. 백준 1주차 강의실 문제랑 비슷하게 Schedule 클래스를 만들고 compareTo를 override해서 정렬 기준을 세웠다. 
2. 달력의 첫 행이 start날부터 end날까지 비워져 있으면 그대로 달력에 체크를 하고
첫 행이 채워져있다면 start날부터 end날까지 다 체크를 할 수 있을 때까지 for문을 이용해 행을 넘어가 체크한다.
3. height 배열을 이용해서 1일부터 365일까지의 높이를 다 기록한다
4. 높이가 0보다 크면 일정이 있다는 뜻이다. 따라서 width++하고 h = Math.max(height[i],h)로 최대 높이를 기록한다
5. 높이가 0이면 일정이 없다는 뜻이다. 따라서 지금까지의 width와 height로 직사각형 면적을 계산한다 
<br/>
배열에 일정을 다 체크하긴 했는데 코팅을 어떻게 해야할지 감을 못잡았다. 코팅할 직사각형이 여러개라면 그 직사각형 각각의 높이가 다를텐데 이걸 어떻게 기록해야하지? 에서 막힌 것 같다. 
더 좋은 풀이가 있을 듯한 느낌,,, 코드가 너무 긴 것 같다 
<br/>
배열 height[]를 이용해 날짜별로 가장 큰 높이를 기록하는 아이디어.

[BOJ] 20207_달력 / 골드5 / 90분 / X

---

week3/BOJ_15787/기차가어둠을헤치고은하수를_강한주.java

- 백준 15787-기차가 어둠을 헤치고 은하수를
<br/>
> 시간 복잡도 :O(N^2)
1. 명령이 3,4번일때 자리를 옮기는 과정에서 뒤로 옮길때는 j=20부터 시작을해서 한칸씩 뒤로 옮긴다. 앞으로 옮길때는 j=1부터 시작해서 한칸씩 앞으로 옮긴다 
2. Set를 이용하여 i 번 train에 승객이 있으면 1 없으면 0으로 표시하여 하나의 문자열을 만든다. 
3. 만들어진 문자열을 set에 add한다. 문자열이 똑같다면 이미 목록에 존재하는 기록이므로 해당 기차는 은하수를 건널 수 없다는 뜻이다. 
4. set.size()를 반환
<br/>
마지막에 "승객이 앉은 상태를 목록에 기록하며 이미 목록에 존재하는 기록이라면 해당 기차는 은하수를 건널 수 없다" 이 부분을 어떻게 해야할지 몰랐다
일일히 비교를 하면 3중 for문이 필요한데 그렇게 하니 시간초과 됐다.
다른 사람들은 비트마스크로 풀었던데 비트마스크도 공부해 봐야 겠다
<br/>
Set를 이용하여 중복을 비교하는 아이디어를 새로 배웠다

[BOJ] 15787_기차가어둠을헤치고은하수를 / 실버2 / 90분 / X

---

week3/BOJ_16926/배열돌리기1_강한주.java

- 백준 16926 -배열 돌리기1
<br/>
1. 레이어 별로 회전을 해야한다. 변수 layer, rotateNum 사용
2. 회전할때 유효값을 확인해가며 방향을 바꾼다. 이때 변수 temp,value 를 사용 
<br/>
1. 레이어 별로 회전을 해야하는데 처음에 정사각형만 나오는 줄 알고 layer = m/2로 단순하게 생각해서 틀렸다.
2. isValid()메서드로 들어온 x와 y를 검사 할때 x와 y 모두 
> x >= i(레이어) && x < n - i(레이어) 의 범위를  만족해야 한다. 그래야 해당 레이어 안에서만 회전할 수 있다. 다른 레이어 범위를 침범하면 안된다!! 
3. 회전을 할 떄
arr[curX][curY] = 회전하기전 숫자 ;      로 해서 숫자가 회전되는게 아니라, 한 숫자만 계속 복사가 되는 문제가 있었다. 이때 어떤 변수를 설정해야 이 문제를 해결할지에 대한 고민이 많았다. 
그래서 변수 temp 는 회전할때 (예: 1->5) 숫자 5를 저장하는 변수,  회전시 첫 시작값을 저장하는 변수.
변수 value는 회전할때 숫자 1을 저장하는 변수. 로 두었더니 해결됐다 . 
4. moveX,moveY로 이동한 자리가 유효하지 않았을때,  방향이 유효할때까지 방향을 계속 바꿔야 하는데(반복문을 써야함) 방향을 딱 한 번만 바꿨기 때문에 과정이 엉키게 됐다. 
<br/>
1. 변수의 유효 범위를 잘 생각해보자. 이 문제의 경우 레이어가 변함에 따라 변수(x,y)의 유효범위가 달라졌다.
2. 계속 안 풀릴땐 한번 시뮬레이션을 직접 돌려보며 어디서 틀린건지 찾아내보자

[BOJ] 16926_배열돌리기1 / 실버1 / 160분 / O

---

week3/BOJ_16719/ZOAC_강한주.java

- 백준 16719-ZOAC
<br/>
1. 재귀함수를 이용했다. 이 메서드는 start ~ end 까지 알파벳 중 사전상 가장 앞에 나오는 알파벳을 찾아준다.
2. 재귀함수에서 중요한 종료 조건은 start > end면 return;을 하는 것이다. 
범위는 start <= end 로 , start > end가 되어버리면 탐색 자체를 못하므로 종료해야한다. 
3. 또 다른 포인트는 visited[] 배열을 이용했다는 것이다. 해당 범위에서 가장 앞에 나오는 알파벳을 찾으면 , 출력을 순서대로 하기 위해서  visited[idx] = true로 기록을 해준다.
4. 
>  "아직 보여주지 않은 문자 중 추가했을 때의 문자열이 사전 순으로 가장 앞에 오도록 " 
이므로 idx+1 ~ end 범위로 zoac() 재귀함수를 실행한다 
5. idx+1 ~ end  범위에서 알파벳을 찾고 문자열이 정리가 됐다면 start ~ idx-1 범위의 문자열을 정리해야 하므로 다시 재귀함수를 실행한다 
<br/>
DFS 알고리즘을 재귀함수를 이용해 구현한 문제였다. 
재귀함수의 대략적인 알고리즘까진 생각해냈는데 , 
출력을 위한 배열( visited)  만들 생각을 못해서 막혔다 . 
재귀함수를 쓰니 머리가 핑핑돈다....😢 재귀함수와 DFS에 익숙해질때까지 공부해야할 필요성을 느꼈다. 
<br/>
DFS 구현 : 스택 / 재귀함수
더 이상 방문할 정점이 없을 때 마지막 분기점으로 돌아오는 로직은 스택을 이용하거나 재귀함수를 이용해 구현할 수 있다.
이 경우에도 BFS와 같이 한 정점을 두 번 방문하는 일이 없도록 방문 …

[BOJ] 16719_ZOAC / 골드5 / 90분 / X

---

week3/BOJ_16926/배열돌리기1_한의정.java

- 백준 10164 - 격자상의 경로
1. 대각선 위치를 시작점으로 잡는다. (범위는 행과 열 中 작은 값 / 2까지)
2. 마지막에 넣을 값을 미리 빼놓는다. (`int lastVal = map[i][i]`)
3. 방향 배열을 한 바퀴 다 돌기 전까지 회전시킨다.
- 끌어온 값이 범위 내에 있으면, 이동시킨다.
- 범위 내에 없으면, 방향을 전환시킨다.
4. 빼놓은 마지막 값을 넣는다. (`map[i + 1][i] = lastVal;`)
- 반시계 방향이래서 **남동북서 방향**으로 dx/dy배열을 선언했는데, **서북동남 방향**으로 선언하길래 뭔가 싶었다.
- 내가 밀고 나가면서 값을 이동시키려고 했는데, 그게 아니라 **해당 위치에서 값을 끌고 오는** 것이기 때문에 시계 방향으로 배열을 작성해 사용한 것이라는 생각이 들었다.

[BOJ] 16926_배열돌리기1 / 실버1 / 90분 / X

---

week3/BOJ_16719/ZOAC_한의정.java

- 백준 16719 - [ZOAC](https://www.acmicpc.net/problem/16719)
**재귀** 문제
1. 해당 구간에 있는 문자들 중 사전식 순서가 가장 빠른 글자를 찾고 방문처리한다.
```
int idx = left;  // idx : 사전식 순서가 가장 낮은 문자 위치
for(int i = left ; i <= right ; i++) {
if(str.charAt(idx) > str.charAt(i)) {
idx = i;
}
}
visited[idx] = true;
```
2. 배열을 돌면서 방문 표시된 문자열들을 출력한다.
```
for(int i = 0 ; i < str.length() ; i++) {
if(visited[i]) {
sb.append(str.charAt(i));
}
}
```
3. 현재 문자보다 뒤에 있는 문자열을 탐색한다.
```
zoac(idx + 1, right);
```
4. 현재 문자보다 앞에 있는 문자열을 탐색한다.
```
zoac(left, idx - 1);
```
- 재귀로 푸는 문제인 것은 알았는데 구현을 어떻게 해야할지 모르겠어서 다른 분 코드를 참고해 작성했다.
- 뒤쪽부터 비교하고 그 다음에 앞쪽 문자열을 비교해야하는 걸 어떻게 해야할지 몰랐다.
```
zoac(idx + 1, right);   // 현재 문자보다 뒤에 있는 문자열 탐색
zoac(left, idx - 1);    // 현재 문자보다 앞에 있는 문자열 탐색
```
- 재귀 문제를 많이 풀어봐야겠다고 느꼈다ㅠ
X

[BOJ] 16719_ZOAC / 골드5 / 60분 / X

---

week3/BOJ_20546/기적의매매법_강아현.py

- 백준 20546 - 기적의 매매법
<br/>
> **준현이의 방식 : BNP**
- 주어진 주식의 가격을 순서대로 준현이가 가진 돈으로 살 수 있는 만큼 구매
- 살 때마다 주식의 수와 준현이의 돈을 업데이트
- 주식의 최종 가격에 준현이가 보유한 주식의 수를 곱해준 후, 준현이가 현재 가지고 있는 돈을 더해서 리턴
> **성민이의 방식 : Timing**
>> **주식의 가격이 상승하는 경우**
>> - up에 +1을 하고, down은 0으로 초기화
>> - up이 3 이상인 경우, 주식의 가격이 3일 이상 연속으로 상승한 경우이므로
>> - 모든 주식을 매도
>> 
>> **주식의 가격이 하강하는 경우**
>> - down에 +1을 하고, up은 0으로 초기화
>> - down이 3 이상인 경우, 주식의 가격이 3일 이상 연속으로 하강한 경우이므로
>> - 보유한 돈의 범위에서 최대로 매수
>>
>> **최종 리턴값은 준현이와 동일하게 연산**
<br/>
성민이의 방식에서 주식의 가격이 연속으로 상승하거나 하강하는 경우 up, down 값을 어떻게 처리할 지에 대한 고민이 필요했다.
<br/>
내용

[BOJ] 20546_기적의 매매법 / 실버5 / 30분 / O

---

week3/BOJ_20546/기적의매매법_강아현.py
week3/BOJ_4396/지뢰찾기_강아현.py

- 백준 4396 - 지뢰 찾기
<br/>
> **bomb(board, i, j)**
>> board : 지뢰게임 판
>> i, j는 현재 위치
>> bomb_cnt : 지뢰의 개수
>> 
>> - 현재 위치를 기준으로 상하좌우대각선 총 9개의 방향에 지뢰가 있다면 bomb_cnt +1
>> - 현재 위치에 지뢰가 있다면 '*'를 리턴
>> - bomb_cnt를 리턴하는 함수
1. 열린 보드의 위치에 지뢰가 있는지 확인하기 위해 bomb 함수를 사용한다.
2. 1을 진행하며 지뢰가 있는 위치를 여는 경우를 따로 카운트 한다.
3. 지뢰가 있는 칸이 하나라도 열린 경우, 지뢰의 모든 위치를 표시한다.
<br/>
X
<br/>
X

[BOJ] 4396_지뢰 찾기 / 실버4 / 20분 / O

---

week3/BOJ_1913/달팽이_강아현.py
week3/BOJ_20546/기적의매매법_강아현.py
week3/BOJ_4396/지뢰찾기_강아현.py

- 백준 1913_달팽이
<br/>
1. 달팽이는 항상 board의 가운데 위치에서 시작한다.
2. 이동 상태를 표시하여 이동 방향을 정한다.
3. 처음 이동 시, 항상 위쪽 방향으로 이동하기 때문에 이동 상태는 'up'으로 초기화한다.
> **이동 상태에 따른 이동 방향 설정**
> - 방향은 보드 위를 움직이며 이동하는 경우를 기준으로 표시하였다.
>
> **1. 이동 상태 : 'up'**
>> - **위쪽**으로 이동중이며 이동한 위치의 오른쪽에 있는 숫자가 0인 경우
>> - 방문하지 않은 경우이므로 방향을 오른쪽으로 꺾은 후 이동.
>> - 방향을 'right'으로 전환한다. (이동 상태 : 'up' -> 'right')
>
> 2. 이동 상태 : 'right'
>> - **오른쪽**으로 이동중이며 이동한 위치의 오른쪽에 있는 숫자가 0인 경우
>> - 방문하지 않은 경우이므로 방향을 오른쪽으로 꺾은 후 이동.
>> - 방향을 'down'으로 전환한다. (이동 상태 : 'right' -> 'down')
>
> 3. 이동 상태 : 'down'
>> - **아래쪽**으로 이동중이며 이동한 위치의 오른쪽에 있는 숫자가 0인 경우
>> - 방문하지 않은 경우이므로 방향을 오른쪽으로 꺾은 후 이동.
>> - 방향을 'left'으로 전환한다. (이동 상태 : 'down' -> 'left')
>
> 4. 이동 상태 : 'left'
>> - **왼쪽**으로 이동중이며 이동한 위치의 오른쪽에 있는 숫자가 0인 경우
>> - 방문하지 않은 경우이므로 방향을 오른쪽으로 꺾은 후 이동.
>> - 방향을 'up'으로 …

[BOJ] 1913_달팽이 / 실버3 / 20분 / O

---

week3/BOJ_1913/달팽이_강아현.py
week3/BOJ_20207/달력_강아현.py
week3/BOJ_20546/기적의매매법_강아현.py
week3/BOJ_4396/지뢰찾기_강아현.py

- 백준 20207-달력 
<br/>
1. 일정 중 날짜가 제일 빠른 날(min_day)과 제일 늦은 날(max_day)을 범위로 달력을 생성한다.
2. 모든 일정을 달력에 표시한다.
```
달력에 표시하는 방법은 다음과 같다.
- 예 ) 일정: 2일 ~ 4일
- 달력 리스트에서 2일, 3일, 4일에 해당하는 인덱스인 2-min_day, 3-min_day, 4-min_day에 +1을 해준다.
```
3. 코팅지의 가로의 길이는 달력 리스트에서 0이상인 값이 연속해서 있는 길이에 해당한다.
4. 코팅지의 세로의 길이는 달력 리스트에서 구한 코팅지 가로의 길이 범위에 있는 값 중 가장 큰 값에 해당한다.
<br/>
X
<br/>
X

[BOJ] 20207_달력 / 골드5 / 20분 / O

---

week3/BOJ_15787/기차가어둠을헤치고은하수를_강아현.py
week3/BOJ_1913/달팽이_강아현.py
week3/BOJ_20546/기적의매매법_강아현.py
week3/BOJ_4396/지뢰찾기_강아현.py

- 백준 15787-기차가 어둠을 헤치고 은하수를
<br/>
> **문제에서 주어진 명령대로 승객 이동**
>> **1 i x**
>> - i번째 기차의 x번째 승객 탑승
>>
>> **2 i x**
>> i번째 기차의 x번째 승객 하차
>>
>> **3 i**
>> - i번째 기차의 승객 위치 한칸씩 뒤로
>> - 마지막 좌석에 승객이 있다면 하차시킨 후 rotate로 오른쪽으로 밀기
>>
>> **4 i**
>> - i번째 기차의 승객 위치 한칸씩 앞으로
>> - 처음 좌석에 승객이 있다면 하차시킨 후 rotate로 왼쪽으로 밀기
<br/>
X
<br/>
X

[BOJ] 15787_기차가 어둠을 헤치고 은하수를 / 실버2 / 10분 / O

---

week3/BOJ_15787/기차가어둠을헤치고은하수를_강아현.py
week3/BOJ_16926/배열돌리기1_강아현.py
week3/BOJ_1913/달팽이_강아현.py
week3/BOJ_20546/기적의매매법_강아현.py
week3/BOJ_4396/지뢰찾기_강아현.py

- 백준 16926-배열 돌리기1
<br/>
1. 보드의 가장 바깥부터 한 줄씩 들어가면서 회전을 한다.
2. 상단, 우측, 하단, 좌측 순으로 한 줄씩 가져와서 회전시킨 값을 저장한다.
3. 상 -> 우 -> 하 -> 좌 순으로 리스트를 붙여준다.
4. 이때, 좌측을 붙일 때는 제일 위에 있는 원소를 제외하고 나머지만 붙인다.
<br/>
X
<br/>
X

[BOJ] 16926_배열 돌리기1 / 실버1 / 40분 / O

---

week4/BOJ_20436/ZOAC3_한의정.java

- 백준 20436 - [ZOAC3](https://www.acmicpc.net/problem/20436)
1. 키보드 객체 배열을 만든다.
> Keyboard(키보드 문자, 어떤 손인지, 행 위치, 열 위치)
2. 두 문자를 입력받는다.
> 😱주의할 점!
입력받은 두 문자가 무조건 (왼쪽 자판에 있는 값, 오른쪽 자판에 있는 값) 순서로 있는 게 아니므로, **어느 쪽에 있는 문자인지 확인해 두 검지의 위치값을 저장**한다.
3. 입력받은 문자열을 돌며 택시 거리를 찾는다.
- 왼쪽 자판에 있는 문자인 경우, 현재까지 걸린 시간에  `택시 거리 + 1`을 더해 걸린 시간을 갱신한다. 왼쪽 검지 위치도 찾은 문자열 위치로 갱신한다.
- 오른쪽 자판도 동일하다.
<br/>
- 너무 노가다로 푼 것 같아서 하면서 이게 맞나 싶었다,,,, 더 적합한 방법을 찾아보겠다,,,
- 자꾸 초반에 틀려서 반례를 찾아보았다. 이걸 보고 코드를 수정했더니 정답이 되었다🫠
- 찾아보니 [Map을 사용한 풀이](https://j-jayce.tistory.com/166)도 있었다. 좀 더 효율적인 듯 하다.

[BOJ] 20436_ZOAC3 / 실버4 / 110분 / X

---

week4/BOJ_2578/빙고_강아현.py

- 백준 2578-빙고
<br/>
1. 사회자가 부르는 수 5개의 배열을 for문으로 돌리면서 빙고판에서 지운다.
2. 숫자 하나 하나를 확인할 때 answer 값에 +1을 해준다.
3. bingo 함수로 빙고판에 그어진 선의 개수를 구한다.
4. 그어진 선의 개수인 cnt가 3 이상인 경우 빙고이므로 stop = 1로 하여 for문에서 나간다.
<br/>
X
<br/>
X

[BOJ] 2578_빙고 / 실버4 / 30분 / O

---

week4/BOJ_20436/ZOAC3_강아현.py

- 백준 20436-ZOAC 3
<br/>
1. 키보드 자판은 2차원 리스트로 선언
2. 손가락 좌표는 `enumerate` 함수로 구했다. _(코드 9-10줄 참고)_
3. 입력받은 문자열을 순차적으로 돌면서 문자가 한글 자음 쪽 자판인지 모음 쪽 자판인지 확인
4. `한글 자음 쪽 자판`인 경우, 2번 방법으로 `왼손 좌표` 업데이트
5. `한글 모음 쪽 자판`인 경우, 2번 방법으로 `오른손 좌표` 업데이트
6. 소요되는 시간에 `|왼손/오른손 좌표[0] - 문자 인덱스[0]| + |왼손/오른손 좌표[1] - 문자 인덱스[1]| + 1`을 누적해서 더해준다.
<br/>
X
<br/>
X

[BOJ] 20436_ZOAC 3 / 실버4 / 30분 / O

---

week4/BOJ_21608/상어초등학교_강아현.py

- 백준 21608-상어 초등학교
<br/>
**Point**
- N\*N의 최대가 20\*20이기 때문에 이중for문으로도 충분히 구현할 수 있을 것 같다고 생각했다.
> **1. "학생의 번호와 학생이 좋아하는 학생의 번호를 담은 리스트"와 "앉아있는 학생의 번호를 담은 리스트"를 생성했다.**
>
> **2. 앉아있는 학생들 중 학생이 좋아하는 학생의 번호가 있는지 확인하기 위한 함수**
>> 좋아하는 학생이 있다면, `좋아하는 학생의 번호`를 리스트로 담아서 리턴
>> 좋아하는 학생이 아직 앉아있지 않다면, `빈 리스트` 리턴
>
> **3. 처음에 앉는 학생은 항상 [2][2] 위치에 앉게 된다.**
>> 학생이 앉을 때 앉아있는 학생의 번호를 담은 리스트에 학생 번호를 추가한다.
>
> **4. 학생이 좋아하는 학생이 한명이라도 앉아있는 경우**
>> `인접해있는 좋아하는 학생이 최대인 수(max_like)`, `주변의 빈칸이 최대인 수(max_empty)`, `학생이 앉게 될 자리(seat_i, seat_j)`를 이중 for문을 돌면서 업데이트 한다.
>> - 상하좌우로 좋아하는 학생이 있다면 like + 1
>> - 상하좌우로 빈자리가 있다면 empty + 1
>> 
>>  **4-1.** 비어있는 칸 중에서 좋아하는 학생이 인접한 칸에 가장 많은 칸으로 자리를 정한다.
>> - `max_like, max_empty, seat_i, seat_j`를 업데이트
>>
>> **4-2.** 4-1을 만족하는 칸 중 인접한 칸 중에 비어있는 칸이 가장 많은 칸으로 자리를 정한다.
>> - …

[BOJ] 21608_상어 초등학교 / 골드5 / 90분 / O

---

week4/BOJ_12933/오리_강아현.py

- 백준 12933 - 오리
<br/>
> 1. 입력받은 문자열을 여러번 돌면서 오리가 올바르게 우는 소리인 "quack"을 확인했다.
>
> 2. 처음 입력받은 문자열에서 오리는 최대로 "q"의 개수만큼 존재한다고 생각되어 이 개수만큼 1을 진행했다.
>
> 3. 입력받은 문자열에서 "quack"에 해당하는 문자는 소리를 내는 오리의 번호로 바꾼다.
>
> 4. 오리의 소리를 체크하기 위한 인덱스가 0인 상태로 끝났다.
>> - 입력받은 문자열에서 이 오리가 올바르게 우는 소리는 문자열이 끝나기 전에 이미 끝났다는 것이다.
>> - 따라서, 이 경우에는 오리의 번호가 문자열에 들어가고 문자열의 마지막과 오리의 번호가 다를 경우 오리를 `ducks 리스트`에 추가한다.
>
> 5. 오리의 소리를 체크하기 위한 인덱스가 5인 상태로 끝났다.
>> - 입력받은 문자열에서 이 오리가 올바르게 우는 소리는 문자열의 마지막 문자에서 끝났다는 것이다.
>> - 따라서, 이 경우에는 오리의 번호를 ducks 리스트에 추가한다.
>
> 6. `ducks의 원소`와 문자를 오리의 번호로 바꾼 `sound의 원소`를 set로 중복 제거 했을 때 같아야 모든 오리가 올바르게 소리를 낸 것이다.
<br/>
처음에 단순히 올바른 quack의 개수만 센다고 생각했었다. 한 오리가 올바른 소리를 1번이상 낼 수 있다는 것을 어떻게 처리할 지에 대한 고민을 하는 것에 시간을 썼던 것 같다. 이것도 다른 사람들의 풀이를 찾아보며 공부를 더 해봐야 할 것 같다.
<br/>
X

[BOJ] 12933_오리 / 실버3 / 60분 / O

---

week4/BOJ_21608/상어초등학교_한의정.java

- 백준 21608 - [상어 초등학교](https://www.acmicpc.net/problem/21608)
> 시간 복잡도 : O(N^4)
1. 2차원 배열로 학생 번호(**`arr[i][0]`**)와, 그 학생이 좋아하는 학생들(**`arr[i][1] ~ arr[i][4]`**)을 기록했다.
<br/>
2. 완전탐색으로 배열을 돌며 조건에 맞게 올바른 위치를 탐색해 해당 위치에 값을 넣는다.
- 조건1 만족 시) 이 위치에 숫자를 두고, 주변에 **좋아하는 학생 수와 비어있는 칸 갯수**를 현재 칸에서 계산한 값으로 갱신한다.
- 조건2 만족 시) 이 위치에 숫자를 두고, **주변에 비어있는 칸 갯수**를 현재 칸에서 계산한 값으로 갱신한다.
- 조건 3 만족 시) 이 위치에 숫자를 둔다.
<br/>
3. 학생 만족도를 계산한다.
- 1부터 N*N번 학생까지를 쭉 돌며 교실에서 해당 학생의 자리를 찾고, 이 학생 주변의 좋아하는 학생 수를 계산하고 그에 따라 만족도 값을 저장한다.
<br/>
- 처음에 자리 배치할 때 위치 배열의 초기값을 제일 작은 값(X)으로 잘못 설정했었다. > **가장 끝 값(O)**
- 조건1을 만족했을 때, 주변에 좋아하는 학생 수랑 **주변의 빈 칸 수도 함께 갱신**해줘야 했다.
- 조건 3 작성할 때 좀 헷갈렸다.
if(a < pos[0] || (a == pos[0] && b < pos[1])) {
pos = new int[] {a, b};
}
<br/>
X

[BOJ] 21608_상어 초등학교 / 골드5 / 130분 / O

---

week4/BOJ_12933/오리_한의정.java

- 백준 12933 - [오리](https://www.acmicpc.net/problem/12933)
그리디
- 2중 for문으로 미방문한 입력값이 quack 문자열의 순서가 맞는지 하나하나 확인한다. 순서를 지켰으면 맞게 운 것이므로 리스트에 값을 추가한다.
- 매번 for문이 종료하고 나서 리스트의 마지막 값이 k가 아니면 제대로 울었다고 할 수 없으므로 -1을 출력한다.
<br/>
한 번 앞에서부터 연달아 quack을 찾고 다시 앞으로 어떻게 되돌아와서 처음부터 어떻게 확인하지? 이 문제에 빠졌던 것 같다. 아이디어를 생각하지 못 할 것 같아 다른 분 코드를 보고 작성했다.
<br/>
X

[BOJ] 12933_오리 / 실버3 / 50분 / X

---

week4/BOJ_2578/빙고.java

- 백준 2578-빙고
<br/>
> 시간 복잡도 :O(N^4)
1. 사회자에게 숫자를 입력받으면 맵에 그 숫자를 0으로 변경한다
2.  0으로 변경한 후 빙고가 있는지 행,열,대각선 2개를 탐색해서 찾는다
3. 빙고가 3개이상이라면 turn을 print하고 종료한다
<br/>
설마 for문을 4개나 쓰겠어,, 하고 다른 방법을 찾다가 끝내 못풀었다.. 
빙고가 3개일때 조건문을 거는게 아니라 3개 이상일때를 조건으로 설정해야한다! 
또한 빙고를 탐색한후 bingo = 0 으로 설정해줘야 한다 !
<br/>
문제를 풀 때 
1. 일단 내가 생각한 풀이대로 풀어보고
2. 그 다음 메모리 효율/시간초과를 고려해 코드를 개선하는 방법으로 푸는게 아직은 나에게 맞는 것 같다 👍

[BOJ] 2578_빙고 / 실버4 / 90분 / X

---

week4/BOJ_20436/ZOAC3_강한주.java

- 백준 20436 - ZOAC3
<br/>
> 시간 복잡도 :O(N^3)
1. 키보드 배열을 만들었다 , 총 시간을 다루는 변수인 time을 선언했다, 현재 왼손의 좌표와 오른손의 좌표를 기억할 변수 leftX,leftY,rightX,rightY 변수를 선언했다 
2. getIndex(String alpha)메서드를 이용해서 aplha의 x좌표와 y좌표를 구했다.
3. 입력받은 String의 알파벳의 좌표가 오른손을 사용하는거라면 getDistance(int x,int x2,int y1,int y2)메서드를 이용해서 거리를 구한다
4. 거리를 time에 더하고 클릭까지 해야하니 time++;를 해줬다. 
5. 오른손의 좌표는 옮겨졌으므로 rightX ,rightY를 알파벳의 좌표로 바꿔준다.
6. 왼손의 경우도 마찬가지다
<br/>
키보드에서 한글의 자음쪽은 왼손이 , 모음쪽은 오른손이 담당하는건데  그 부분을 잘못이해해서 문제를 푸는데 시간이 조금 걸렸다.
일일히 객체를 생성해서 메모리를 너무 많이 쓰는 것 같다. 다른 좋은 풀이를 찾아봐야겠다 
<br/>

[BOJ] 20436_ZOAC3 / 실버4 / 35분 / O

---

week4/BOJ_2615/오목_한의정.java

- 백준 2615 - [오목](https://www.acmicpc.net/problem/2615)
1. 각 점마다 오목인지 가로,세로, 왼쪽 위 > 오른쪽 아래 대각선, 오른쪽 위 > 왼쪽 아래 대각선 방향으로 탐색했다. 이를 통해 오목 갯수와, 어느 쪽 색의 돌인지, 가장 왼쪽 위 좌표는 무엇인지 저장하게 했다.
2. 입력받은 검은 돌, 흰 돌 좌표 리스트에서 가장 왼쪽 위에 있는 값이 나오도록 정렬하였다.
3. 검은 돌 오목 수가 많다면 검은 돌의 가장 왼쪽 위 좌표를, 흰 돌 오목 수가 많다면 흰돌의 가장 왼쪽 위 좌표를, 둘이 같다면 0을 출력하도록 했다.
육목이 되는 경우를 잘 생각해주어야 했다.
- [반례 참고1](https://www.acmicpc.net/board/view/110822), [반례 참고2](https://www.acmicpc.net/board/view/83278)
너무 무식하게 푼 것 같아서 다른 분들 풀이를 찾아보았는데 dx/dy로 풀면 되는 것이었다....ㅎㅎ

[BOJ] 2615_오목 / 실버1 / 90분 / O

---

week4/BOJ_21608/상어초등학교_강한주.java

- 백준 21608 - 상어초등학교
<br/>
1. HashMap을 이용해 좋아하는 친구들 4명을 저장했다 
2. 포인트는 인접한 4군데에서 좋아하는 친구들 수를 세서 비교 -> 빈 칸을 세서 비교 -> 행 비교 -> 열 비교를 **compare** 을 이용한 것이다
<br/>
처음에 인접한 칸에 좋아하는 친구들 수를 세고, 빈칸수도 구했는데 이걸 어떻게 비교하지? 에서 막혔다.  
ArrayList<Integer[]> 을 이용해서 friendCount,emptyCount,행,열을 한 번에 저장하고 
compare메서드를 쓰는 포인트를 잊지말자!!
<br/>
compare메서드 작성에 미숙하다,,,, 저번에도 이랬던 것 같은데 꼭 정리해서 내것으로 만들어야겠다

[BOJ] 21608_상어초등학교 / 골드5 / 60분 / X

---

week4/BOJ_2615/오목_강한주.java

- 백준 2615 - 오목
<br/>
1. 배열을 돌며 1,2가 저장된 곳의 x,y좌표 바둑알의 갯수 cnt 변수를 이용해 탐색을 진행한다
2. 탐색은 가로,세로,대각선1,대각선2 로 총 4가지 루트가 있다
3. 이때 배열 int[][] d를 이용해서 _**양방향**_ 모두 탐색을 진행한다
4. cnt == 5이면 종료한다
<br/>
바둑을 둔 방향에서 8방향으로 돌며 같은 방향에 같은 색의 바둑이 있으면 재귀함수를 통해 계속 탐색을 진행하려고 했다. 
하지만 그렇게 풀면 한 방향으로만 계속 탐색을 하게되어서 바둑이 6개가 나오는 경우 , 2번째 바둑 ~ 6번째 바둑까지 탐색한걸  바둑이 5개 놓여있어 정답이라고 처리하기 때문에 틀리게 된다. 
즉, 양방향으로 탐색을 해야하는데 한방향으로만 깊이 파고들어서 막혔다. 다시 처음부터 풀자니 시간이 오래걸릴것같아 포기했다 
<br/>
또한 문제에서 왼쪽,위에 있는 바둑을 먼저 출력하려고 했으므로 반복문은 i=0부터가 아닌 **j=0** 으로 설정해야한다. 
특정 조건이 주어졌을때 주의하자 !

[BOJ] 2615_오목 / 실버1 / 80분 / X

---

week4/BOJ_22858/원상복구_강한주.java

- 백준 22858-원상복구
<br/>
1. 먼저 arr 빈 배열을 만든다
2. 포인트는 주어진 D배열과 S배열을 이해하는 것이다. D배열에서  {4,3,1,2,5}는 1번째 카드는 4번째로 옮겨야하고, 2번째 카드는 3번째로 옮겨야하고, 3번째 카드는 1번째로 옮겨야 하는거고,,,,,
3. j번째 카드는 S[j] 고 이 카드를 D[j]-1 위치로 옮겨준다. 즉 arr[index]  = moveCard
4.  카드를 1번 다 섞으면 arr 배열을 copy해서 S 배열에 넣어준다. 
넣어주지 않으면 S배열은 섞지 않은 카드세트이므로 의미가 없다.  
두 배열을 활용해서 문제를 풀었다 .
그래서 이렇게 풀었답니다!
<br/>
문제 이해하는데만 20분을 소요했다
<br/>
intellij의 메서드완성기능을 쓰지 않았다면 **Arrays.copyOf(int[], length)** 메서드를 제대로 못썼을것같다. 실전에 대비하기 위해 이렇게 쓰이는 메서드는 암기하자 !!!

[BOJ] 22858_원상복구 / 실버3 / 30분 / O

---

week4/BOJ_22858/원상복구_한의정.java

- 백준 22858 - [원상 복구 (small)](https://www.acmicpc.net/problem/22858)
> 시간 복잡도 : O(NK)
1. 총 **3개의 배열**을 생성한다.
1. K번 카드 섞은 결과의 배열 arr
2. D 배열
3. 결과 얻기 위한 매번 새로 생성하는 배열 tmp
2. arr(Di)의 값을 i로 옮기고, 이 과정을 반대로 수행한다. [(참고)](https://dingdingmin-back-end-developer.tistory.com/entry/%EB%B0%B1%EC%A4%80-22858%EC%9E%90%EB%B0%94-java-%EC%9B%90%EC%83%81-%EB%B3%B5%EA%B5%AC-small)
3. 반대로 수행한 결과를 원래의 배열에 넣는다.
4. 과정 2,3을 K번 수행하고, 결과를 출력한다.
문제 자체를 이해하는 것과 진행과정에 대해 이해하는 것이 어려웠다. 무슨 소리인지 모르겠어서 다른 사람들 코드와 풀이를 보고 조금이나마 이해할 수 있었다. 😢 직접 그림을 그려보며 파악해봐야겠다.
X

[BOJ] 22858_원상복구 / 실버3 / 30분 / X

---

week4/BOJ_14719/빗물_한의정.java

- 백준 14719 - [빗물](https://www.acmicpc.net/problem/14719)
> 시간 복잡도 : O(W^2)
1. 1차원 배열 arr를 만들어 빗물의 높이를 입력받는다.
2. 1번째 칸부터 해당 칸의 왼쪽에서 최대벽 높이를 탐색하고 → 오른쪽 최대벽 높이를 탐색하고 → 현재 벽보다 높은 벽이 양쪽에 있을 때는 두 벽 中 낮은 높이 기준으로 빗물을 채운다.
해당 칸의 양쪽에서 왼쪽 값과 오른쪽을 비교할 생각까지는 했었다. 이 때 while문이랑 투 포인터로 찾을 생각을 했었는데 구현은 제대로 하지 못 했다. 
<br/> → 해당 칸의 왼쪽 벽 탐색하는 변수와 for문 하나, 오른쪽 벽 탐색하는 변수와 for문 하나 입력해서 찾고, 두 변수의 값을 비교한 결과를 활용해 채우면 되는 것이었다,,
X

[BOJ] 14719_빗물 / 골드5 / 60분 / X

---

week4/BOJ_14719/빗물_강한주.java

- 백준 14719 - 빗물
<br/>
1. edit later
2. 
그래서 이렇게 풀었답니다!
<br/>
내용
<br/>
내용

[BOJ] 14719_빗물 / 골드5 / 90분 / X

---

week5/BOJ_2606/바이러스_한의정.java

- 백준 2606 - [바이러스](https://www.acmicpc.net/problem/2606)
> 시간 복잡도 : O(M)
**사용 자료 구조**
> - 인접 리스트
> - 방문 배열
> - 갯수 세는 int형 변수
- 인접 리스트에 값을 **양방향으로** 입력받아 두 번호가 연결되어 있음을 기록한다.
```
A[a].add(b);
A[b].add(a);
```
- 컴퓨터 갯수 크기만큼의 방문 배열을 생성하고, 1과 연결된 컴퓨터의 갯수를 센다.
- 1과 연결된 모든 번호를 dfs로 탐색한다. 방문한 적 없는 번호만 탐색하고, 이 때 방문한 갯수도 1 더해준다.
```
private static void dfs(int num) {
visited[num] = true;
for(int x : A[num]) {  // 인접 리스트에서 num과 연결된 값 모두 가져와 탐색
if(visited[x])  continue;
cnt++;
dfs(x);
}
}
```
<br/>
X
X

[BOJ] 2606_바이러스 / 실버3 / 15분 / O

---

week5/BOJ_1260/DFS와BFS_한의정.java

- 백준 1260 - [DFS와 BFS](https://www.acmicpc.net/problem/1260)
1. 입력을 통해 해당 정점과 연결된 정점을 **양방향 인접 리스트 배열**로 받고, 초기화한다. [(참고)](https://freestrokes.tistory.com/87)
ArrayList<Integer>[] A = new ArrayList[N + 1];  // 인접 리스트 배열 생성
for(int i = 1 ; i <= N ; i++) {  // 인접 리스트 초기화
A[i] = new ArrayList<>();
}
2. 정점 번호가 작은 것부터 방문하도록 인접 리스트를 오름차순 정렬한다.
for(int i = 1 ; i <= N ; i++) {
Collections.sort(A[i]);
}
3. V 정점과 연결된 정점 리스트를 돌며 방문하지 않은 정점을 탐색한다.
→ DFS : 재귀함수 사용 / BFS : 큐 사용
<br/>
X
<br/>
X

[BOJ] 1260_DFS와 BFS / 실버2 / 35분 / O

---

week5/BOJ_2606/바이러스_강아현.py

- 백준 2606 - 바이러스
<br/>
1. 입력받은 네트워크 상 연결되어 있는 컴퓨터의 쌍으로 computers라는 graph를 생성한다.
2. bfs로 1번 컴퓨터에 연결된 컴퓨터를 찾는다.
3. 1번 컴퓨터에 연결된 컴퓨터 리스트에 1도 포함이 되어 있으므로 1을 제외한 값을 출력한다.
<br/>
X
<br/>
X

[BOJ] 2606_바이러스 / 실버3 / 20분 / O

---

week5/BOJ_1260/DFS와BFS_강아현.py

- 백준 1260 - DFS와 BFS
<br/>
1. 입력받은 간선이 연결하는 두 정점의 번호로 graph를 생성한다.
2. 방문할 수 있는 정점이 여러 개인 경우 정점 번호가 작은 것을 먼저 방문한다.
- graph에서 연결된 정점을 오름차순으로 정렬한다.
3. visited_dfs와 visited_bfs로 방문을 확인하는 리스트를 각각 생성한다.
4. dfs와 bfs로 탐색한 결과를 출력한다.
<br/>
내용
<br/>
내용

[BOJ] 1260_DFS와 BFS / 실버2 / 15분 / O

---

week5/BOJ_11725/트리의부모찾기_강아현.py

- 백준 11725 - 트리의 부모 찾기
<br/>
> **DFS**
>> - 기존의 visited 리스트로 방문을 확인한 것처럼 parent 리스트를 만들어서 부모 노드를 저장한다.
>> - 연결된 노드의 부모노드가 0인 경우 부모노드의 값을 해당 노드의 값으로 지정한다.
>> - parent 리스트에서 노드 2인 값부터 부모노드의 값을 차례로 출력한다.
<br/>
120분을 소요하고도 생각하지 못한 부분이 있다. 
- visited 대신 부모노드의 값을 저장할 생각을 전혀 하지 못했다.
- dfs, bfs 등 트리구조를 더 공부해봐야할 필요성을 느꼈다..
<br/>
X

[BOJ] 11725_트리의 부모 찾기 / 실버2 / 120분 / X

---

week5/BOJ_11725/트리의부모찾기_한의정.java

- 백준 11725 - [트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
>사용 자료구조
> - 인접 리스트
> - boolean형 방문 표시 배열
> - int형 부모 노드 저장 배열 ✔️ 
<br/>
처음에 '2번부터 N번까지 가장 처음 방문한 정점을 출력하면 되는 거 아닌가?'라는 생각을 했었고 틀렸었다.
그림 상으로는 이해가 가는데 코드로는 부모 노드를 어떻게 저장해야 할지 생각하지 못 했다.
→ 그냥 1번부터 각 정점과 연결된 정점들을 돌면서, 이 때 여태 방문한 적 없는 다음 방문할 정점의 부모를 현재 정점이라고 기록해두면 되는 것이었다...
Queue<Integer> q = new LinkedList<>();
q.add(num);
while(!q.isEmpty()) {
int now = q.poll();
for(int next : tree[now]) { // 현재 정점과 연결된 정점 리스트 돌기
if(!visited[next]) {
visited[next] = true;
parent[next] = now;     // 부모 노드를 배열에 저장 ✅
q.add(next);
}
}
}
X

[BOJ] 11725_트리의 부모 찾기 / 실버2 / 40분 / X

---

week5/BOJ_2606/바이러스_강한주.java

- 백준 2606-바이러스
<br/>
1. computer 2차원 배열을 통해 어떤 컴퓨터끼리 연결됐는지 표시했다 
2. 재귀함수를 이용해 만약 컴퓨터가 연결되어 있는데 연결된 컴퓨터가 감염이 안됐다면 감염시킨다
<br/>
1. 먼저 컴퓨터가 서로 연결된걸 표현할 자료형을 생각해내는데 시간이 꽤 걸렸다. Map을 쓰려다 복잡해질 것 같아서 그만두고 List도 염두해 뒀다가 2차원 배열이 생각나서 그걸로 풀었다
2. `computer[computer2][computer1] = 1;` 이 부분을 작성안해서 계속 5%에서 틀렸다. 
컴퓨터를 연결할때 배열에서 양쪽에 표시해야하는데 한 쪽에만 표시해서 그런거였다.
이 부분을 생각해내지 못해서 반례를 찾아보았다
반례) 
4 3
1 2
3 4
2 4
<br/>
컴퓨터가 한 방향, 즉 A -> B로만 감염된다는 조건이 있었다면 내 풀이처럼 풀어도 됐을텐데
컴퓨터가 양 방향, 즉 A <-> B 는 A가 감염되면 B도 감염되고, B가 감염되면 A도 감염되는 것이므로 배열의 양방향에 표시를 해서 풀어야 한다 !

[BOJ] 2606_바이러스 / 실버3 / 50분 / X

---

week5/BOJ_1260/DFS와BFS_강한주.java

- 백준 1260 - DFS와BFS
<br/>
1. 이차원 배열 arr을 만들어서 서로 연결되어 있다는 표시를 해주었다
2. 방문한 노드와 방문하지 않은 노드를 나누기 위해 visited 배열을 사용했다
3. dfs메서드는 재귀함수를 통해 구현했다
4. bfs 함수는 queue를 통해 구현했다 isEmpty(), poll(),add()를 이용하는게 힌트다 ! 
<br/>
BFS메서드를 구현할때 큐를 쓸 생각을 못했다. 
계속 반복문으로만 주어진 문제를 풀려고 했는데(주석으로 잘못쓴 코드를 표시해 두었다)
내가 잘못쓴 코드대로 푼다면 **첫 정점의 자식 노드들만 ** 너비 우선 탐색을 진행하게 되고 , 그 다음은 진행을 못하게 된다(진행하려면 매우 복잡하게 코드를 작성해야 할 것 같다)
큐를 사용하면 간단하게 문제를 풀 수 있다
DFS는 재귀함수, BFS는 큐를 써서 풀어보자 ! 
그리고 이차원 배열을 선언하는 것 말고도 다른 방법으로 풀 수 있는지 찾아봐야겠다 
<br/>
BFS를 구현할때 큐를 사용하자 ‼️

[BOJ] 1260_DFS와BFS / 실버2 / 60분 / X

---

week5/BOJ_7576/토마토_한의정.java

- 백준 7576 - [토마토](https://www.acmicpc.net/problem/7576)
<br/>
> BFS
1. 큐를 생성해 입력받은 칸의 값이 1일 때 해당 좌표를 큐에 추가한다.
2. 큐가 빌 때까지 해당 큐의 맨 앞 값을 뽑고 인접한 4곳을 탐색한다.
<br/>인접한 칸이 격자 내 범위에 있고, 익지 않은 상태(0)일 때 해당 칸의 값을 현재 칸의 값 + 1해 누적해 계산 겸 방문 처리하고, 큐에 다음 이동할 좌표의 값을 추가한다.
3. 완전탐색을 통해
- 토마토가 익지 않은 칸 (= 0인 칸)이 있다면, `-1` 출력하고 종료한다.
- 격자 내 최댓값 (= 토마토를 익히는 데 걸리는 최소 날짜)을 구한다.
4. 격자 내 최댓값이 1이라면, 초기 저장상태부터 모두 익어있었던 것이므로 `0`을 출력한다. / 격자 내 최댓값이 0도 아니고 1도 아닌 값이라면, `구한 날짜 - 1` 해 출력한다.
<br/>
마지막에 **저장될 때부터 모든 토마토가 익어있는 경우**를 어떻게 처리해야 할지 고민하다가 다른 풀이를 참고했다..<br/> → 완전탐색을 통해 **`0인 칸이 없고, 격자 내 최댓값이 1인 경우`**
<br/>
X

[BOJ] 7576_토마토 / 골드5 / 40분 / X

---

week5/BOJ_1325/효율적인해킹_강한주.java

- 백준 1325-효율적인해킹
<br/>
1. `static List<Integer>[] arr;` 자료구조 즉, 리스트 안의 리스트를 통해 컴퓨터의 해킹 경로를 표시했다
2. <h3>이때 주의 점은 "A가 B를 신뢰하는 경우에는 B를 해킹하면, A도 해킹할 수 있다는 소리"</h3>지 A를 해킹하면 B도 해킹할 수 있다는게 아니다 !!
3. 큐를 이용해서 BFS를 통해 풀었다
<br/>
일단 <h1>또</h1> 문제를 잘못이해했다. A가 해킹되면 B도 해킹되는줄 알았다. 만약 그러면 아무컴퓨터나 해킹하면 모든컴퓨터가 해킹되기 때문에 답이 안나오게 된다. 
그래서 큐를 통해 풀었는데 계속 시간초과가 나서 다른사람의 여러 풀이를 봤다. 
사실 왜 시간초과가 난지 모르겠다. `List<Integer>[]`과 `ArrayList<ArrayList<Integer>>` 은 같은거 아닌가? 
<br/>
의정언니는 LinkedList를 ArrayDeque로 바꿔서 맞았다는데 이 둘의 시간차이를 찾아봐야겠다.
저번에 찾아봤는데 이유를 까먹었다... 정리를 해봐야곘다

[BOJ] 1325_효율적인해킹 / 실버1 / 50분 / X

---

week5/BOJ_2178/미로탐색_강한주.java

- 백준 2178 - 미로탐색
<br/>
1. 간단히 말하자면 BFS와 dx,dy배열을 만드는 방법으로 풀었다
2. `Queue<int[]> q =  new LinkedList<>()` 로 이동할 수 있는 좌표를 표시했다
3. BFS함수를 시작해서 4방향중에 갈 수 있는 방향으로 가고, 간 좌표는 visited에 표시한다. 또한 칸을 이동할때마다 이동한 거리를 표시하기 위해 `map[nextX][nextY] = map[nowX][nowY]+1; ` 코드를 작성했다 
<br/>
2. `Queue<int[]> q =  new LinkedList<>()` 로 이동할 수 있는 좌표를 표시했다
이 부분을 생각해내기 어려웠다. 
node가 아닌 2차원 배열로 보니까 (이번주 주제가 DFS/BFS가 아니였다면) 어떤 알고리즘을 써야할지도 감이 안잡혔을것같다. 
<br/>
큐에 좌표를 저장하는 방법

[BOJ] 2178_미로탐색 / 실버1 / 20분 / X

---

week5/BOJ_7576/토마토_강한주.java

- 백준 7576 - 토마토
<br/>
일단 BFS를 사용해 푸는 문제다!
1.` Queue<int[]> queue = new LinkedList<>();` 토마토가 있는 좌표를 표현하기 위한 큐, 익은 토마토가 있다면 그 좌표를 넣는다
2. `int cnt` 익지 않은 토마토의 개수를 세고 나중에 검증하기 위한 변수
3. `int days` 총 며칠이 걸리는지 세는 변수
(자세한건 코드 <h4>34~52</h4> 를 읽으면 알수 있다 )
4. 익지않은토마토의 개수 > 0 && 큐가 비어있지 않으면
5. 익은 토마토에서 인근4방향을 탐색해 
5-1. 익지 않은 토마토가 있다면 익은 토마토로 바꿔주고, 큐에 좌표를 추가한다
5-2. 익지 않은 토마토가 익었으므로 cnt--
6. days++
그래서 이렇게 풀었답니다!
<br/>
처음 막혔던 부분은 _**익은 토마토가 여러개일때 어떻게 동시에 주변 토마토를 익게할 것인지?**_였다. (익은 토마토가 3개라면 각각 주변에 있는 총 12개의 토마토를 어떻게 확인하지?)
그래서 잠깐 익은 토마토의 개수만큼 큐를 생성해서 풀어야하나? 고민했는데 딱봐도 안풀릴것같았다. 시간이 많지 않아서 다른 사람들의 풀이를 봤다
‼️ 중요한점
1. 35번째 줄에 써있는 것처럼 while문 안에 _**for문의 반복 횟수를 큐의 사이즈만큼 설정하는 것이다.**_
-> 이렇게 설정하면 토마토가 주변의 토마토를 익게만들어서 큐에 추가해도, 전 큐의 사이즈만큼 반복하고  `poll`을 하기 때문에 동시에 토마토를 익게 만들 수 있다( = 즉 익은 토마토가 3개라면 그 3개의 토마토 주변을 …

[BOJ] 7576_토마토 / 골드5 / 20분 / X

---

week5/BOJ_1325/효율적인해킹_강아현.py

- 백준 1325 - 효율적인 해킹
<br/>
> **Key point**
>
> "A가 B를 신뢰하는 경우, B를 해킹하면 A도 해킹이 가능하다."
>
> - 노드 A는 노드 B를 부모 노드로 갖는다.
> - graph를 만들 때, 노드 B 리스트에 노드 A를 추가하는 방법으로 트리를 생성했다.
1. 그래프를 생성한 뒤에는 bfs로 1부터 N까지 진행하여 이어져있는 노드의 개수를 구한다.
2. bfs 결과로 연결되어있는 컴퓨터가 가장 많은 컴퓨터 번호를 찾는다.
<br/>
x
<br/>
x

[BOJ] 1325_효율적인 해킹 / 실버1 / 90분 / O

---

week5/PSG/택배배달과수거하기_한의정.java

- 프로그래머스 level2 - [택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369)
<br/>
> 제일 먼 거리부터 배달과 수거를 진행한다.
맨 끝 인덱스부터 for문을 돌리면서 그 인덱스 위치에 트럭이 몇 번 오는지 센 후, 거리 계산해 더한다.
<br/>
- 가장 먼 거리부터 할 생각은 했는데 시간초과가 떠서 (아무래도 구현 상 문제로 예상) 다른 사람 풀이를 보고 제출하였다,,,, ([참고1](https://stritegdc.tistory.com/317), [참고2](https://leeeehhjj.tistory.com/204))
- 문제 길이에 비해 짧은 코드라니,,,, 괘씸했다(?)
<br/>
X

[PSG] 택배 배달과 수거하기 / level2 / 60분 / X

---

week5/BOJ_7576/토마토_강아현.py

- 백준 7576 - 토마토
<br/>
> **BFS**
1. q에 익은 토마토의 모든 위치를 넣는다.
2. 익은 토마토의 좌표를 기준으로 bfs로 탐색한다.
3. graph[i][j]의 값은 토마토가 익는 날의 수로 채워진다.
4. q가 모두 비워진 후, 그래프에서 최대값을 정답값으로 리턴한다.
<br/>
이 문제를 토마토의 좌표값으로 bfs 탐색을 할 생각을 전혀 하지 못했다........
<br/>
x

[BOJ] 7576_토마토 / 골드5 / 90분 / X

---

week5/PSG/택배배달과수거하기_강한주.java

- 프로그래머스  - 택배배달과수거하기
<br/>
1. 한 집에 배달할 상자의 개수를 나타내는 변수 `deliver`과 한 집에서 수거할 상자의 개수를 나타내는 변수 `pickup`을 선언했다, 또한 총 거리를 나타내는 변수인 `answer`선언
2. ‼️ 가장 먼 집 부터‼️ 탐색을 하며 탐색된 집에 배송해야할 상자와 수거해야할 상자를 deliver, pickup 변수에 대입한다
2-1. 반복문을 사용해 만약 배송해야할 상자나 , 픽업해야할 상자의 수가 0개를 넘는다면 
배달해야할 상자나 수거해야할 상자수에서  '최대 허용량'을 빼준다
2-2. 반복문을 돈 횟수 = 트럭이 왕복한 횟수이므로, `answer += (i+1)*2` 총 거리를 계산해준다
<br/>
처음에는 우선 **거리가 먼 집부터 방문**을 하면 상자를 처리해야겠다는 생각이 들어서 **DFS**메서드를 사용해 풀려고 했다. 
하지만 재귀함수로 풀려고 하니 막히는 부분이 있었다
🤔가장 끝 집에 상자를 배달해야하는데, 배달하고 나서 아직 트럭에 배달할 수 있는 상자가 있다면 어떻게 처리하지? 다시 '끝집 바로 앞에 있는 집'에가서 배달을 해야하나? 이건 코드로 어떻게 작성하지?
내가 지금까지 푼 DFS 문제들은 다 첫번째 노드부터 시작해서 깊게 파고드는 문제들이어서 무조건 <h4>"첫 집에서 부터 출발해야지" 라는 생각에 얽매어있었다</h4> 
하지만 끝 집에서 부터 시작한다면 문제가 상당히 간단해진다. 
끝부터 반복문을 돌며 deliver, pickup 변수를 활용하면 간단히 문제를 풀 수 있다. 
또한 …

[PSG] 택배배달과수거하기 / level2 / 30분 / X

---

week6/BOJ_1244/스위치켜고끄기_한의정.java

- 백준 1244 - [스위치 켜고 끄기](https://www.acmicpc.net/problem/1244)
<br/>
> 구현, 투 포인터
<br/>
- 스위치 배열 `switches` 에서 인덱스가 입력받은 수의 배수인 칸의 상태를 변경한다.
<br/>
1. 현재 칸은 무조건 상태를 변경한다.
2. 현재 칸의 왼쪽 위치 l과 현재 칸의 오른쪽 위치 r을 잡는다. (**_투 포인터_**)
3. l과 r이 배열의 크기를 벗어나지 않는 동안 반복문을 수행한다. (while문 사용)
- 만약 좌우 두 칸이 대칭인 경우 (`swithces[l] == switches[r]`), 좌우 두 칸을 모두 상태 변경하고, l은 왼쪽으로 한 칸, r은 오른쪽으로 한 칸 이동시킨다.
- 좌우 대칭이 아닌 경우, 루프를 종료한다.
4. 스위치 배열을 출력한다.
<br/>
양 옆 범위 확장하고 마지막으로 한 번에 left부터 right 범위까지 상태 변경하려고 했는데 그게 잘 적용이 안 되었다.ㅠ
그래서 다른 풀이를 참고해서 그냥 **_즉각적으로_** 좌우 대칭인 칸은 상태 변경하고, 왼쪽 위치와 오른쪽 좌표 이동하도록 했다..
<details>
<summary>틀렸던 코드</summary>
<div markdown="1">
```
private static void solve(int gender, int cnt) {
if(gender == 1) {   // 남자인 경우
for(int i = 1 ; i <= N ; i++) {
if(i % cnt == 0) {
switches[i] = (switches[i] == 0) ? 1 : …
```

[BOJ] 1244_스위치 켜고 끄기 / 실버4 / 60분 / X

---

week6/BOJ_1244/스위치켜고끄기_강한주.java

- 백준 1244 - 스위치켜고끄기
<br/>
1. 스위치의 상태를 저장하는 배열인 swtichSts을 선언하고 학생의 성별과 받은 숫자를 'info'라는 이차원 배열에 저장했다
2. 남자일 경우 스위치의 수 만큼 반복문을 돌며 배수인 번호의 스위치를 바꿔줬다
3. 여자일 경우 `cnt` 변수를 이용하여 뽑은 숫자의 좌,우를 탐색했다. 만약 범위를 벗어나거나 둘의 숫자가 같지 않다면 반복문을 `break;`로 나갔다.  cnt++를 해주고 반복문을 벗어나면 여자가 뽑은 숫자의 스위치를 바꿔줬다
4. 첫번째 스위치부터 마지막 스위치까지 탐색하다 `스위치%20==0`이 되면 한줄을 개행해주고 , 그렇지 않은 경우 한칸만 띄워줬다
<br/>
버퍼를 많이 써봤는데도 아직도 익숙하지 않나보다.... 계속 에러가 나서 숫자를 입력받는 코드를 여러번 바꿨다 (st = new StringTokenize(br.readLine()) 계속써도 되는건가유??...
또한 마지막에 <h4>"스위치를 20개씩 출력하고 넘으면 다음줄부터 다시 작성한다"</h4> 이 조건을 만족하는 코드를 쓰는데 20분 정도 잡아먹었다.... 갑자기 뇌가 이상해진건가⁉️  치킨에 뭔가 들어간것이 분명하다 !!!
<br/>
X

[BOJ] 1244_스위치켜고끄기 / 실버4 / 65분 / O

---

week6/BOJ_10994/별찍기19_강한주.java

- 백준 10994 - 별찍기19
<br/>
1. 일단 별 그림을 char형 2차원 배열로 선언한 후 빈칸으로 채웠다.
2. 여기서 포인트는  _**재귀함수**_를 쓰는 것이다.  이 함수는 하나의 테두리(네변)를 그린다고 생각하면 된다
3. 재귀함수의 파라미터는 왼쪽위 꼭짓점의 좌표(어차피 왼쪽위 꼭짓점의 행과 열 좌표는 같다), 그 꼭짓점의 한 변의 별의 개수이다.
4.  재귀함수 내의 반복문을 이용해 테두리 별표를 채워준다
5. 왼쪽 꼭짓점의 좌표가 테두리 한 변 별의 개수보다 크거나 같으면 종료한다
<br/>
<h2>하....일단 문제를 완전 잘못이해하고 있었다....🥹</h2> 
[문제 10994](https://www.acmicpc.net/problem/10994)
나는 이 그림이 행이 9칸, 열이 5칸 인줄 알았다.........즉 행과열이 짝수일때 개행을 해야하는 줄 알았다.  그렇게 문제를 잘못이해한채로 끙끙대다 못풀었다 (⁉️ 그런데 해답코드에 `System.out.println();` 한 줄만 더 쓰면 됨....)
<내가 한 생각의 흐름>
1. 일단 가로,세로길이 만큼 배열선언
2. 0행 0열부터 ~ 0행 끝열, 1행 0열 ~... 순으로 별을 채우려고 했다 -> 이건 진짜 무리수... 어떠한 규칙이 보일리가 없다 ‼️‼️‼️
3. 2번이 아닌것 같다. 뭔가 1번의 반복문에 1개의 테두리(4변)를 그려야 할 것 같다. 는 생각까지 왔다
4. 재귀함수로 풀어야하나? 의심시작 🤔
5. 하지만 배열을 n=2일때 `arr[9][5]` , n=3일때 `arr[17][9]` 처럼 생각하니 재귀함수를 …

[BOJ] 10994_별찍기19 / 실버4 / 60분 / X

---

week6/BOJ_17413/단어뒤집기2_한의정.java

- 백준 17413 - [단어 뒤집기 2](https://www.acmicpc.net/problem/17413)
<br/>
> **스택** &  여는 꺽새가 있는지 판단하는 boolean형 변수 **check**
: 여태 스택에 저장해둔 문자열을 거꾸로 출력하고,  여는 꺽새가 있으니 boolean형 변수를 `true`로 바꾼다. 그리고 현재 위치의 문자 `<`도 출력한다.
<br/>
: 여는 꺽새가 없으니 boolean형 변수를 `false`로 바꾸고, 현재 위치의 문자  `>`도 출력한다.
<br/>
: 괄호 안의 글자는 뒤집지 않고 그대로 출력되어야 하므로, 현재 위치의 문자를 그대로 출력한다.
<br/>
1) 현재 위치의 문자가 띄어쓰기인 경우,
-  스택에 쌓인 문자를 뒤집어 출력하고, 띄어쓰기도 출력한다.
2) 현재 위치의 문자가 띄어쓰기가 아닌 경우,
- 스택에 현재 위치의 문자를 넣는다. (나중에 거꾸로 출력되도록)
<br/>
마지막으로 스택에 남은 값을 탈탈 털어 출력한다.
<br/>
스택을 사용할 생각까지는 했는데 괄호 처리와 띄어쓰기가 나왔을 때 어떻게 처리할지 생각하지 못 해서 다른 사람 풀이를 참고해 제출했다..
많이 복잡하진 않은 것 같긴 한데 조건문을 잘 생각해야 하는 것 같다ㅠ
<br/>
X

[BOJ] 17413_단어 뒤집기 2 / 실버3 / 40분 / X

---

week6/BOJ_17276/배열돌리기_한의정.java

- 백준 17276 - [배열 돌리기](https://www.acmicpc.net/problem/17276)
<br/>
> 시간 복잡도 : O(Nd)
문제에서 알려준대로 그대로 구현하면 된다,,,
회전은 무조건 시계 방향으로만 시킨다. (반시계 방향 회전도 +360해서 시계 방향 회전 시킬 수 있으므로)
이를 위해 입력받은 각도 d가 음수인 경우, 360을 더해 값을 조정하고,
(각도 d/ 45도) 번 회전시킨다.
<br/>
1. 주대각선 \ `(i, i)`을 가운데 열 - `(i, n/2)`로 옮긴다.
2. 가운데 열 | `(i, n/2)`을 부대각선 / `(n - i, i)`으로 옮긴다.
3. 부대각선 / `(n - i, i)`을 가운데 행 - `(n/2, i)`으로 옮긴다.
4. 가운데 행 - `(n/2, i)`을 주대각선 \ `(i, i)`으로 옮긴다.
<br/>
매번 45도씩 회전한 결과를 반영하며 d/45번 회전시켜야 한다.
그러므로 변경된 결과를 저장한 copy 배열을 원본 배열로 복사해 결과를 반영한다.
<br/>
처음에 테두리만 홀수 행과 열만 먼저 회전하고, 그 다음에 내부를 시계 방향으로 회전시키려고 했는데 그게 아니었다..
격자 크기가 5일 때만 가능한 일이었고, 격자 크기가 3만 되어도 이 방법은 틀렸었다,,, (이걸 빨리 알아차리고 이 방법을 버렸어야 했는데)
그래서 다른 분 풀이를 보았다,,
<br/>
신기한(?) 방법도 찾아 공유한다,,
🔗 참고 : https://nkt-docs.tistory.com/20

[BOJ] 17276_배열 돌리기 / 실버2 / 90분 / X

---

week6/BOJ_10994/별찍기19_한의정.java

- 백준 10994 - [별 찍기 - 19](https://www.acmicpc.net/problem/10994)
<br/>
> 재귀
재귀로 별을 찍는다.
- 재귀함수의 인자로는 (시작 행 위치, 가로줄 길이)를 가져간다.
- 반복문을 통해 **시작 위치부터 가로줄 길이까지** 사각형 위치에 있는 칸 (맨 위 가로줄, 맨 아래 가로줄, 왼쪽 세로줄, 오른쪽 세로줄)을 별로 채운다.
- 반복문이 끝나면, 시작하는 행의 위치는 2 더하고, 가로줄의 길이는 2씩 줄여 재귀함수를 돌린다. (그래야 안쪽에 줄어들면서 별을 생성할 수 있다.)
<br/>
- 최장 길이를 구하는 식을 찾지 못 했다. → `4 * N - 3`
- 한 행씩 연달아가며 채울 생각을 했는데 저렇게 반복문으로 사각형 위치를 별로 채울 생각은 하지 못 했다.
<br/>
X

[BOJ] 10994_별 찍기 - 19 / 실버4 / 60분 / X

---

week6/BOJ_17276/배열돌리기_강한주.java

- 백준 17276-배열돌리기
<br/>
1. 회전각도 `d`는 -360~360 사이의 수이며 |d|는 45의 배수이다. d에 360을 더해주면 음수도 양수로 처리할 수 있기 때문에 360을 더했다. 또한 총 몇번 회전할지를 구해야 해서 `d/=45`를 했다
2. 원본배열 arr과 원본배열 arr의 복사본인 copy 배열을 사용했다
3. 이 문제의 포인트는 <h4>대각선,가로행,가로열,부대각선을 45도씩 회전하는 것이다 . </h4>
4. 회전 수 만큼 rotate를 반복한다
5. 4번의 주의점은 copy배열에 회전한 결과를 할당하고나서 _**copy배열 결과를 arr배열에 넣어줘야 한다는 것이다 !!!!!**_ (이걸 생각못해서 시간 50분은 날렸다.... 진짜 어이없다)
<br/>
처음에는 각도를 -360,360,45,-315도 ....등 이렇게 여러가지의 각도를 다 '조건문'을 사용해서 대각선,부대각선,가운데열,가운데행을 옮기려고 했다.... 그러다 보니 당연히 코드 줄이 엄청 길어지고 
내가 봐도 "이렇게 푸는거 절대아닌것 같은데.... 중복 코드가 너무너무 많다 생각했다. " 
결국 다른 사람의 코드를 봤는데 기본적인 접근법은 나랑 비슷했다(?) 
하지만 나는 d에 +360을 해서 45도로 나눠줘서 '회전수 만큼 회전할 생각'을 못했다. 너무 노가다 식으로 풀려고 한것이다.....
또한 5번에도 썼지만 copy에 할당한 결과를 arr에 대입해주지 않아 계속 답이 틀렸다....
`arr을 45도씩` d번 회전해야하는데 그럴려면 한번 45도씩 회전해줄때마다 그 결과를 arr에 옮겨야한다...
하지만 …

[BOJ] 17276_배열돌리기 / 실버2 / 80분 / X

---

week6/BOJ_20164/홀수홀릭호석_한의정.java

- 백준 20164 - [홀수 홀릭 호석](https://www.acmicpc.net/problem/20164)
<br/>
> 재귀, 브루트포스
1. 한 자리 숫자인 경우, 여태 나온 홀수의 갯수와 최솟값 최댓값을 비교해 갱신한다.
2. 두 자리 숫자인 경우, 두 숫자를 분해하고 현재 숫자와 홀수 갯수를 갱신한다. (재귀 함수 사용)
3. 세 자리 이상 숫자인 경우, 2중 for문 완전탐색으로 숫자를 3등분할 인덱스를 정하고, 한 자리 숫자가 될 때까지 분해하며 홀수 갯수를 구한다.
<br/>
- 재귀 쓸 생각은 했는데 저 홀수 갯수 인자를 어떻게 가져가야 할까라는 고민을 하였고 구현하지 못 했다,,
- 숫자를 3등분할 위치 2개를 구할 때, 조합으로 구하려고 했는데 그냥 2중 for문으로 해도 되었다,,
- getOdd 메소드를 만들어서 매번 홀수 갯수를 구할 생각을 하지 못 했다.
<br/>
X

[BOJ] 20164_홀수 홀릭 호석 / 골드5 / 80분 / X

---

week6/BOJ_17413/단어뒤집기2_강한주.java

- 백준 17413 -단어뒤집기2
<br/>
1. 먼저 스택을 2개 이용해야겠다는 아이디어를 얻었다(1개 이용한 풀이도 있지 않을까?)
2. stk1 스택은 '단어'를 넣고 빼는 스택 , 즉 출력을 반대로 하는 스택
3. stk2 스택은 '태그'를 넣고 빼는 스택, 즉 출력을 그대로 한다
4. '<'가 나오면 stk2를 사용하도록 설정, stk2를 사용하다가 '>'가 나오면 stk1을 사용하기로 설정
5. stk1 스택을 사용하다 '공백'이 나오거나 '반복문이 끝까지 돌면' stk1.pop()을 실행해 출력 
6. stk2 스택을 사용하다 '>'가 나오면 `stk2.remove(0)`을 통해 스택의 맨 밑부터 출력 <span style="color:olivedrab">(큐를 썼어도 괜찮았을 것 같다)</span>
7. stk2 스택을 사용하다 '<'가 나오면 stk1에 쌓인 단어를 pop()을 통해 출력한다. 
그래서 이렇게 풀었답니다!
<br/>
뭔가 더 간단하게 풀 수 있는 방법이 있을 것 같다
<br/>

[BOJ] 17413_단어뒤집기2 / 실버3 / 50분 / O

---

week6/BOJ_20164/홀수홀릭호석_강한주.java

- 백준 20164 - 홀수홀릭호석
<br/>
1. cut재귀함수(숫자,홀수가 총 몇 번 나왔는지)를 이용했다 
2. odd(숫자)함수를 이용해 숫자에 홀수가 몇 번 나왔는지 cut의 2번째 매개변수로 전달해준
<br/>
하... 일단 지금까지 골드5문제는 손도 못댔는데 이건 풀줄알았다... 하지만 끝내 19/102란 처참한 정답률과 함께 다른 사람의 풀이를 참고하게 됐다
<비슷했던점>
- 재귀 함수 이용 ,글자수에 따라서 분기를 줬다
- 3자리 이상일때 String을 써서 합 구하는 것 까진 비슷하게 풀었다
- 2자리,1자리일때도 똑같이 풀었다
<달랐던점>
- 일단 나는 모든걸 `String` 으로 접근했다. 즉 처음 입력받을때도 int로 받지않고 String으로 받았다. 따라서 숫자를 더하거나, 홀수의 개수를 세는 작업을할때 일일히 `Character`형으로 바꾸고 `-'0'`을 해서 코드가 엄청 길어졌다
- '총 홀수의 개수'를 전역변수로 설정했다... 내 생각엔 이것때문에 오류가 많이 발생한 것 같다. cut()재귀함수에 총 홀수의 개수도 같이 매개변수로 줘야할 것 같다
- odd() 메서드를 따로 쓰지 않았다. 따라서 자리수가 3개이상일때,2개일때,1개일때 모두 중복된 코드를 사용해서 코드가 길어졌다
근데 사실 초기에 쓴 내코드 (정답률 19/102) 왜 틀린건지 아직도 못찾겠다.. 어느 부분때문에 막힌거지
<br/>
`String.valueOf(int)` 와 `Integer.toString(int)` 의 차이를 알아보자

[BOJ] 20164_홀수홀릭호석 / 골드5 / 120분 / X

---

week6/BOJ_3085/사탕게임_한의정.java

- 백준 3085 - [사탕 게임](https://www.acmicpc.net/problem/3085)
<br/>
> 브루트포스
(1) 두 점의 값을 swap한다.
(2) 값을 바꾼 배열에서 행과 열에서 최대 사탕 갯수를 찾는다.
(3) 바꿨던 두 점의 값을 원상복구하고자 또 swap한다.
<br/>
- 매 행마다 연속된 사탕 갯수는 1에서 시작한다.
- 두 점 `arr[i][j]`와 `arr[i][j + 1]`이 같다면, `연속된 사탕 갯수 + 1`하고, 최댓값을 비교해 갱신한다.
- 둘이 같지 않다면, 연속된 사탕 갯수는 `1`로 초기화한다.
<br/>
- 매 열마다 연속된 사탕 갯수는 1에서 시작한다.
- 두 점 `arr[j][i]`와 `arr[j + 1][i]`이 같다면, `연속된 사탕 갯수 + 1`하고, 최댓값을 비교해 갱신한다.
- 둘이 같지 않다면, 연속된 사탕 갯수는 `1`로 초기화한다
<br/>
분명 로직 다 맞게 썼는데 어디서 틀렸나 하고 다른 분 코드 보니까
"**열 기준**"으로 swap하고 연속된 부분 갯수 확인할 때 **`arr[j][i]`** 이렇게 했어야 했는데 **`arr[i][j]`** 로 작성해서 틀렸었다.
<br/>
행과 열의 인덱스를 사용할 때, 순서에 따라 올바르게 지정하자,,,
특히 **열**!!!! 🤕

[BOJ] 3085_사탕 게임 / 실버2 / 60분 / X

---

week6/BOJ_3085/사탕게임_강한주.java

- 백준 3085 - 사탕게임
<br/>
1. swap을 하기 전에 모든 행과 열을 탐색하며 가장 긴 길이를 찾는다 
2.  사탕을 교환하면 그 행과 열이 바뀌는데, 행과 열에서 가장 긴 연속 부분을 탐색하고, swap 전으로 다시 되돌리면서 최대값을 찾는다
<br/>
문제를 읽고나서 일단 '인접'한 두 요소를 swap하라 했는데 인접이 상,하,좌,우 인건지 오른쪽만 해당되는지 좀 헷갈렸다
또한 처음에 "이걸 일일히 다 교환을 해서 풀어야하나?" 에서 생각이 막혔다. 풀 시간이 많지 않아서 다른 분의 풀이를 참고했다 
일일히 탐색하고나서 swap한 자리의 행과 열을 다 탐색하는 아이디어를 사용했다 
<br/>
시간을 좀 썼으면 풀만한 문제였는데 아쉽다 !!...

[BOJ] 3085_사탕게임 / 실버2 / 20분 / X

---

week6/BOJ_1244/스위치켜고끄기_강아현.py

- 백준 1244 - 스위치 켜고 끄기
<br/>
> **남학생의 경우**
> - 번호의 배수에 해당하는 스위치의 상태를 변경한다.
>
> **여학생의 경우**
> - 여학생이 뽑은 번호의 스위치 상태를 변경한다.
> - 번호의 양쪽 스위치의 상태가 같은지 확인하고 상태가 같으면 두 스위치의 상태를 모두 변경한다.
<br/>
- 스위치 번호를 리스트의 인덱스로 그대로 쓰려고 [0] + 스위치 리스트로 스위치 리스트를 구현해놨다.
- 여학생이 스위치 번호를 받았을 때 대칭을 확인하는 경우에 while문 조건을 스위치 리스트의 인덱스 0까지 포함해서.. 계속 틀렸다.
- 이것만 10분정도 고민한듯..
<br/>
x

[BOJ] 1244_스위치 켜고 끄기 / 실버4 / 40분 / O

---

week6/BOJ_10994/별찍기19_강아현.py

- 백준 10994 - 별 찍기 - 19
<br/>
규칙을 찾아야만 했다.
1. n에 따른 전체 별의 개수 : n x 2 + ( 2 x ( n - 2 ) + 1 )
2. 총 출력되는 줄 수 : 1과 동일
3. 홀수 줄
- 처음과 끝을 제외하고 전체 별에서 양쪽 좌우의 별을 하나씩 빼며 출력한다.
- 별을 뺄 위치는 left, right 변수를 쓴다.
- left는 왼쪽 -> 오른쪽 / right는 오른쪽 -> 왼쪽
- left와 right가 같아지면 left는 다시 왼쪽 방향으로 right는 오른쪽 방향으로 이동한다.
4. 짝수 줄
- 양쪽 끝에서부터 별을 찍기 시작한다.
- 안쪽으로 하나씩 건너 뛰면서 별을 출력한다.
- 가운데 별은 찍지 않고 가운데 찍을 차례가 되면 이전에 찍었던 별을 다시 바깥쪽으로 양쪽 하나씩 지우면서 찍는다.
텍스트로는 풀이 방식이 제대로 전달되지 않는 느낌이다..
<br/>
x
<br/>
x

[BOJ] 10994_별 찍기 - 19 / 실버4 / 60분 / O

---

week6/BOJ_17276/배열돌리기_강아현.py

- 백준 17276 - 배열 돌리기
<br/>
> **각도에 따른 규칙 찾기**
> - 반시계 방향으로 회전했을 때를 기준으로 rotate 함수 구현
> - 처음 그래프에서 left, col, right, row 리스트 구하기
>   - left : [1][1] -> [n][n]
>   - col : [1][n//2] -> [n][n//2]
>   - right : [1][n] -> [n][1]
>   - row : [n//2][1] -> [n//2][n]
>> 1. **rotate_45_225** : 반시계 45˚ (시계 315˚)일 때
>>  - 반시계 225˚ (시계 135˚)일 때는 left, col, right, row가 들어갈 자리는 동일하며 배열만 거꾸로 넣어주면 된다.
>> 
>> 2. **rotate_90_270** : 반시계 90˚ (시계 270˚)일 때
>>  - 반시계 270˚ (시계 90˚)일 때는 1과 동일한 내용이다.
>>
>> 3. **rotate_135_315** :  반시계 135˚ (시계 225˚)일 때
>>  - 반시계 315˚ (시계 45˚)일 때는 1과 동일한 내용이다.
>> 4. **rotate_180** : 반시계 180˚ (시계 180˚)일 때
>>  - 원본 그래프에서 left, col, right, row가 들어갈 자리는 동일하며 배열만 거꾸로 넣어주면 된다.
**아래 이미지 참고**
<br/>
x
<br/>
x

[BOJ] 17276_배열 돌리기 / 실버2 / 60분 / O

---

week6/BOJ_17413/단어뒤집기2_강아현.py

- 백준 17413_단어 뒤집기2
<br/>
> **"<" 인 경우**
> - tag에 <를 추가한다.
> - 태그 사이에 단어가 있는 경우에는 이 단어를 뒤집어서 리턴값에 더해준다. (리턴값에 더해주고 나서 이 값은 ""로 초기화)
> 
> **">" 인 경우**
> - tag에 있는 <를 pop한다.
> - 리턴값에 >를 더해준다.
>
> **기호가 아닌 경우**
> - tag가 비어있는 경우에는 뒤집어야하는 단어이기 때문에 reverse에 문자열을 더해준다.
> - tag가 비어있고 마지막 문자열인 경우에는 reverse를 공백을 기준으로 나눈 후 각 단어를 뒤집은 후 리턴값에 더해준다.
> - tag가 비어있지 않은 경우에는 태그 괄호 안에 있는 단어인 경우로 리턴값에 바로 더해준다.
<br/>
x
<br/>
x

[BOJ] 17413_단어 뒤집기2 / 골드5 / 25분 / O

---

week6/BOJ_3085/사탕게임_강아현.py

- 백준 3085 - 사탕 게임
<br/>
> **인접한 사탕 확인**
>
>> - 가로 방향 확인 (좌우로 인접한 사탕이 같은 종류인지)
>> - 세로 방향 확인 (상하로 인접한 사탕이 같은 종류인지)
>> - 같은 종류의 사탕이 아니라면 인접한 사탕을 바꾼다.
>> - 사탕을 바꾸고 난 후, 보드에서 먹을 수 있는 최대 사탕 수를 구한다.
>
> **사탕 개수 확인하는 함수**
>
>> - 가로 혹은 세로 방향으로 이어져있는 동일한 사탕 종류 최대 개수를 구한다.
<br/>
너무 복잡하게 코드를 작성한 것 같다.. 좀 더 효율적으로 풀 수 있는 방법을 생각해봐야 할 것 같다. 복습할 때 다른 사람들의 풀이도 참고해서 공부를 해야할 것 같다.
<br/>
x

[BOJ] 3085_사탕 게임 / 실버2 / 60분 / O

---

week7/BOJ_1010/다리놓기_한의정.java

- 백준 1010 - [다리 놓기](https://www.acmicpc.net/problem/1010)
<br/>
> 조합 (파스칼의 삼각형)
1. 조합 값을 저장할 2차원 배열 bridges을 생성한다.
2. 조합 배열에서 채울 수 있는 초기값은 미리 채워둔다다.
- i개 중 0개 뽑는 경우의 수 → `dp[i][0] = 1`
- i개 중 1개 뽑는 경우의 수 → `dp[i][1] = i`
- i개 중 i개 뽑는 경우의 수  → `dp[i][i] = 1`
3. 입력한 초기값을 기반으로 나머지 조합 칸을 채운다. (**_파스칼의 삼각형_** 이용)
```
bridge[i][j] = bridge[i - 1][j] + bridge[i - 1][j - 1]
```
4. T번 동안 입력받은 n과 m에 대해 조합 **mCn**의 결과를 가진 **`bridge[m][n]`** 칸을 출력한다.
<br/>
- 조합 문제인 것은 알았는데 조합을 어떻게 코드로 표현하지?의 문제
- 조합 공식을 까먹음의 문제
<br/>
조합(파스칼의 삼각형) 공식
🔗 참고 링크 :  [1](https://ko.wikipedia.org/wiki/%ED%8C%8C%EC%8A%A4%EC%B9%BC%EC%9D%98_%EC%82%BC%EA%B0%81%ED%98%95)  &nbsp; [2](https://velog.io/@baekgom/%EC%A1%B0%ED%95%A9-%EA%B3%B5%EC%8B%9D) &nbsp; [3](https://wootool.tistory.com/53)

[BOJ] 1010_다리 놓기 / 실버5 / 30분 / X

---

week7/BOJ_17626/FourSquares_한의정.java

- 백준 17626 - [Four Squares](https://www.acmicpc.net/problem/17626)
<br/>
> 시간 복잡도 :  O(N * sqrt(N))
1. int형 dp배열을 생성해 배열 값을 초기화한다.
- dp[0] = 0, dp[1] = 1, 나머지 칸은 단 최대한 큰 값으로 설정)
2. 2부터 N까지 dp배열을 채운다.
- i 범위 : 2~N까지
- j 범위 : 1 ~ i의 제곱근까지
- **i에서 i보다 작은 제곱근에서 뺀 값 +1 한 값 중 최소를 선택한다.**
> dp[i] = Math.min(dp[i] , **dp[i - j * j] +1**);
예) i가 4인 경우
dp[4 - 1*1] + 1 = dp[3] + 1 = 4
dp[4 - 2*2] + 1 = dp[0] + 1 = 1
이 중 최솟값인 1이 dp[4]의 값이 된다.
3. dp[N]의 값을 출력한다.
<br/>
패턴을 찾아 점화식을 세우는 것이 어려웠다,,
점화식을 다르게 세우고 삽질하다가 결국 다른 분 풀이를 보고 제출하였다..
<details>
<summary>초기 생각했던 점화식</summary>
&nbsp; (i 범위 : 2 ~ N / j 범위 : 1 ~ i의 제곱근)
```
dp[i] = Math.min(dp[i], dp[j] + dp[i - j]
```
</details>
<br/>
패턴.. 점화식..

[BOJ] 17626_Four Squares / 실버3 / 30분 / X

---

week7/BOJ_9465/스티커_한의정.java

- 백준 9465 - [스티커](https://www.acmicpc.net/problem/9465)
<br/>
> 시간 복잡도 : O(TN)?
1. dp 배열을 만든다. (dp[i][j] : 해당 칸 (i, j)까지 구한 최댓값)
2. 0번 열은 본인이 최대이므로 본인으로 초기화한다.
3. 1번 열은 특수처리한다.
- [0][1]은 왼쪽 아래 값과 본인 칸 값 더하기
- [1][1]은 왼쪽 위쪽 값과 본인 칸 값 더하기
4.  2번 열부터 뒤쪽까지는 아래와 같이 채운다..
6. 마지막 열의 두 값 중 큰 값을 구해 출력한다.
<br/>
- dp 규칙 찾고 점화식 세우기
<br/>
X

[BOJ] 9465_스티커 / 실버1 / 40분 / X

---

week7/BOJ_1010/다리놓기_강한주.java

- [백준 1010 - 다리놓기](https://www.acmicpc.net/problem/1010) 
<br/>
1. 서로다른m개 중에 n개를 뽑는 조합문제
2. 1번을 배열 dp[m][n]으로 설정한다
3. '조합 재귀함수'를 만들어서 풀었다. 이때 중요한건 이미 계산 이력을 dp에 표시해서 계산한 적이 있다면 표시된 값을 그대로 갖다써서 계산횟수를 줄이는 것이다 ‼️
<br/>
조합을 쓸 생각을 해서 (이것도 생각해내는데 좀 걸림) 함수를 사용했는데 `29!` 가 `long` 범위를 벗어났다. 이걸 어떻게 해결해야하나? 하다가 다른분의 풀이를 참고했다
<h3>메모이제이션!!!!</h3> 기억하도록 하겠다.... 
[참고](https://blog.itcode.dev/posts/2021/06/09/a1010)
<br/>
수학 문제를 너무 못푼다.... ㅎ 중등수학 개념인 조합을 다시 공부해보자

[BOJ] 1010_다리놓기 / 실버5 / 30분 / X

---

week7/BOJ_2839/설탕배달_강한주.java

- [백준 2839 - 설탕배달](https://www.acmicpc.net/problem/2839)
<br/>
1. dp[i] : 무게가 i일때 최소 설탕 봉지 수를 기록하는 배열을 선언했다
2. dp[0]~dp[7]까지 초기화
3. 
- 3kg&&5kg 모두 배달 가능한 경우 
- 3kg으로만 배달 가능한 경우
- 5kg으로만 배달 가능한 경우
- 둘 다 배달 불가능한 경우
로 케이스를 나눠서 풀었다.
<br/>
dp를  '무게가 i일때 최소 설탕 봉지 수'를 기록하는 배열로 선언해야겠다는 포인트는 빨리 생각해냈지만 코드를 어떻게 작성해야할지 고민을 많이했다.
결국 하드코딩을 해서 d[0]~d[7]까지 초기화를 다 해버리고 말았다. 이것 보다 더 깔끔하게 푼 풀이를 찾아봐야겠다....
다이나믹 프로그래밍은 나에게 너무 어렵다 ㅠㅠ.... 수학적 사고를 기르려면 한참인것같다
<br/>

[BOJ] 2839_설탕배달 / 실버4 / 40분 / O

---

week7/BOJ_15486/퇴사2_한의정.java

- 백준 15486 - [퇴사2](https://www.acmicpc.net/problem/15486)
<br/>
> DP
1. 크기가 **N+2**인 시간 배열 T, 금액 배열 P, dp 배열 DP를 만든다.
> dp[i] = i일까지 받을 수 있는 최대 상담 금액
<details>
<summary>배열 크기가 N + 2인 이유</summary>
: 배열 인덱스를 1부터 사용할 거니까 +1,  i번째까지 일한 돈은 i+1번째 날에 받기 때문에 또 +1하므로
</details>
3. N번 동안 T와 P 배열의 값을 입력받는다.
4. DP 배열을 채운다. 
- 현재 날짜 (=현재 인덱스) i 와 해당 인덱스에서 걸리는 날짜 T[i]의 값을 더한 값` i + T[i] `이 N  + 2 내에 있다면, `DP[i + T[i]]`의 값을 `DP[i + T[i]]`의 값과 `(최댓값 + 걸린 기간)` 中 더 큰 값으로 갱신한다.
```
int day = i + T[i];
if(day < N + 2)
DP[day] = Math.max(DP[day], max + P[i]);
```
6. max값을 출력한다.
<br/>
- dp 점화식을 잘못 세웠었고, dp 배열을 뒤에서부터 채워보았었다.. (5번째 테스트케이스에서 틀렸지만)
<details>
<summary>잘못 작성한 코드</summary>
```
import java.util.*;
import java.io.*;
public class Main {
static int N;
static int[] T, P, dp;
static int max = 0;
public …
```

[BOJ] 15486_퇴사2 / 골드5 / 40분 / X

---

week7/BOJ_17626/FourSquares_강한주.java

- 백준 17626 - FourSquares
<br/>
1. `dp[i]` 를  i를 제곱수 합으로 표현할 때 쓴 최소의 수(4이하의 자연수) 로 설정했다
2. 2 i와 dp[i] 의 관계를 찾아 점화식을 세운다. 
```
int min = 0;
for(int i = 2; i <= n; i++){
min = Integer.MAX_VALUE;
for(int j = 1; j*j <= i; j++){//i보다 작거나 같은 제곱수는 j가 있다 예)i=4면 제곱수 1,2가 있다
int temp = i - j*j;
min = Math.min(min,dp[temp]);
}
dp[i] = min + 1;//dp[i] = min(dp[i-j*j])+1 이라는 점화식을 세울 줄 알아야 한다
}
```
<br/>
처음 접근이 어려워 dp를 정의하고 숫자 1부터 16까지 직접 써보면서 규칙을 찾아보았다. 
그러다가 12 = 2^2 + 2^2 + 2^2 로 답이 3인데 12 = 3^2 + 1^2 +1^2 + 1^2 로 4인줄 알고 
"아 😀 1 2 3 1 2  3 4 2 1 2 3 4 2 3 4 1 로  1~4까지 증가하는데 4가 나오면 2로 돌아가구나 ! 1,4,9,16 같은게 나오면 1로 처리하면 되구나 ~ " 라는 실수를 했다
위와 같은 생각으로 푸니 당연히 풀릴리가 없었다... 다시 규칙을보니 dp[12]는 3이라는걸 알고 다시 식을 세워보려했지만 도저히 점화식을 떠올릴수가 없어서 다른 사람의 코드를 참고했다. 
점화식을 세우기가 참 어렵도다 
<br/>
2중 for문을 사용해 점화식 세우기 , 제곱수 찾기

[BOJ] 17626_FourSquares / 실버3 / 40분 / X

---

week7/BOJ_9465/스티커_강한주.java

- 백준 9465 - 스티커
<br/>
풀이가 이해가 안갑니다 !!!
1. 이렇게 했다.
2. 저렇게 했다.
그래서 이렇게 풀었답니다!
<br/>
내용
<br/>
내용

[BOJ] 9465_스티커 / 실버1 / 50분 / X

---

week7/PGS/두큐합같게만들기_강한주.java

- 프로그래머스 level2 - 두큐합같게만들기 
<br/>
1. 두 큐에 수를 추가하면서 두큐의 합인 total변수를 구한다
2. 1번큐의 합과 2번큐의 합이 같아야하는데 , 이때 1번큐의 합만 구하면 toal-1번큐의합=2번큐의 합이기 때문에 1번큐의합인 변수 queue1Sum을 선언한다
3. 두큐의 합인 toal이 홀수라면 두 큐의 합은 같을 수 없으므로 -1을 return 한다. 
4. 1번큐의 합이 target보다 크면 1번큐에서 숫자를 빼서 2번큐에 넣고, 그 반대의 경우 2번큐에서 숫자를 빼서 1번큐에 넣는다. 
5. 이때 while문을 빠져나갈 조건 설정을 잘 하는게 중요하다 
<br/>
시간이 좀 더 있었으면 풀수도 있었을것같다. 이번주 문제중에서 난이도가 괜찮은 편인 문제였던 것 같다....
<br/>

[PGS] 두큐합같게만들기 / level2 / 20분 / X

---

week7/BOJ_1010/다리놓기_강아현.py

- 백준 1010-다리 놓기
<br/>
> **중복조합** -> aCb 계산
- 사이트가 많은 쪽의 사이트 수: a
- 사이트가 적은 쪽의 사이트 수: b
<br/>
x
<br/>
x

[BOJ] 1010_다리 놓기 / 실버5 / 5분 / O

---

week7/BOJ_2839/설탕배달_강아현.py

- 백준 2839 - 설탕 배달
<br/>
> **일차방정식의 해**
- i의 범위 : 0 ~ x절편
- y = (N - (5*x)) / 3
- y가 정수인 경우, 현재 정답값보다 x+y의 값이 작다면 정답값을 x+y로
- 연산 후, 정답값이 초기 임의값과 같다면 -1을 출력(정확하게 N킬로그램을 만들 수 없는 상황)
<br/>
x
<br/>
x

[BOJ] 2839_설탕 배달 / 실버4 / 40분 / O

---

week7/BOJ_17626/FourSquares_강아현.py

- 백준 17626 - Four Squares
<br/>
1. dp[n]은 n을 표현하기 위한 최소 개수의 제곱수 합이다.<br> 0과 1의 최소 개수의 제곱수 합은 0과 1이므로 dp 배열에 설정한다.
2. 이중for문으로 i를 2부터 n+1까지의 범위를 설정하고(0과 1을 제외하고 n까지의 숫자를 모두 봐야 하기 때문에 +1), j를 1부터 i의 제곱근+1으로 설정한다. (1부터 i까지의 제곱근을 모두 봐야하기 때문에 +1)
3. 최소 개수의 제곱수 합을 구하기 위해서 min함수를 사용한다.<br> minValue값과 현재 dp배열 안에 값을 비교해서, 최소 개수의 제곱수 합을 구해 minValue에 넣어준다.
4. for문을 통해 구한 minValue을 해당 값의 인덱스에 넣어주고, 모든 반복문이 끝나면 마지막으로 구해진 n값을 출력하면 된다.
[풀이 참고 링크](https://kau-algorithm.tistory.com/564)
<br/>
- 풀이를 봤지만 온전히 이해를 하지는 못했다. dp를 자유자재로 사용할 수 있는 능력을 길러야 할 것 같다.
<br/>
x

[BOJ] 17626_Four Squares / 실버3 / 60분 / X

---

week7/BOJ_11053/가장긴증가하는부분수열_강아현.py

- 백준 11053 - 가장 긴 증가하는 부분 수열
<br/>
> **DP**
> 
> A를 순차적으로 돌면서 각 원소값을 마지막 값으로 하며<br>이전에 이 원소값보다 작은 원소가 몇개가 있는지 확인하는 방식.
>
>> 예시 : 1 2 4 3
>> - A[1] = 2의 경우, 1 2이므로 dp[1] = 2
>> - A[2] = 4의 경우, 1 2 4이므로 dp[2] = 3
>> - A[3] = 3의 경우, 1 2 3이므로 dp[3] = 3
<br/>
dp를 활용하여 문제를 풀고자 했으나 어떻게 적용시켜 봐야할지 감이 안왔다. <br> max(dp[i], dp[j]+1) 이부분을 생각해내지 못했다.
<br/>
x

[BOJ] 11053_가장 긴 증가하는 부분 수열 / 실버2 / 60분 / X

---

week7/BOJ_9465/스티커_강아현.py

- 백준 9465 - 스티커
<br/>
> **DP**
> 
> ( index, 위(0) / 아래(1) )
>
>> ( 0, 0 ) + ( 1, 1 ) / ( 1, 0 ) + ( 0, 1 )
>> - 제일 왼쪽 스티커는 무조건 떼기 때문에 위 조합을 먼저 생각한다.
>> - 제일 왼쪽 스티커는 위와 같은 조합으로 뜯을 수 있다.
>> - 좌, 우, 아래(or위)는 같이 떨어져 나가므로 대각선 스티커들의 조합만 가능하다.
>>
>> ( 2, 0 )를 뜯을 때,
>> 1. ( 1, 1 ) 선택하면 ( 0, 0 )도 자동 선택
>> 2. ( 0, 1 ) 선택하면 ( 1, 0 )도 자동 선택
>> 1, 2 중에 더 큰 값을 선택
>> - 2 이후 값에도 위 로직대로 반복하면 최대값 구할 수 있다.
<br/>
x
<br/>
문제에 dp를 적용해서 푸는 방법을 조금은 익힌 것 같다.

[BOJ] 9465_스티커 / 실버1 / 30분 / O

---

week7/BOJ_15486/퇴사2_강아현.py

- 백준 15486 - 퇴사 2
<br/>
> **DP**
>
- i일의 이익은 i-1일에 얻은 이익보다 크거나 같을 수 있다.
- 상담은 당일날 끝나는 경우도 있으므로 day -1을 해서 당일도 포함한다.
- i일에 일이 끝나는 시점인 day가 근무 종료일 이하이면 i일에 일을 할 수 있다.<br>day일에 영향을 주기 때문에 dp[day]에 이 부분을 정의하였다.
<br/>
dp와 다시 멀어지기.<br> 문제를 잘못 생각했던 것 같다. i일에 일을 했을 때, 일이 진행되는 기간이 끝나는 시점에만 일을 할지말지 결정한다고 생각했다. 일이 끝나는 날에 바로 일을 하지 않고 하루 건너 뛰는 등의 생각은 하지 못했다.
<br/>
x

[BOJ] 15486_퇴사 2 / 골드5 / 60분 / X

---

week8/BOJ_18352/특정거리의도시찾기_한의정.java

- 백준 18352 - [특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
<br/>
> 시간 복잡도 : O(N+M)
**필요 변수**
```
1) 정점 정보 저장할 인접 리스트
2) bfs 위한 큐
3) 출발점 X로부터의 거리 정보 저장 & 방문 표시하는 int형 배열 (초기값은 모두 -1로 설정)
```
1. 인접 리스트에 단방향으로 정점 정보를 추가한다.
2. 시작점 X에서부터 BFS를 수행한다. 이 때 distance[시작점]의 값은 0으로 설정한다.
- 해당 정점 now와 연결된 정점 中 방문한 적 없는 점 next에 대해 거리 정보를 갱신하고, 큐에 해당 정점 next를 추가하며 마저 탐색을 진행한다.
```
// 방문 표시 겸 출발점부터 정점 next까지의 거리 갱신
distance[next] = distance[now] + 1;  
```
3. bfs 탐색이 끝난 후, distance 배열을 돌며 값이 K인 값들을 출력한다. 만약 존재하지 않는다면, -1을 출력하고 종료하게 한다.
<br/>
거리 업데이트를 무지성으로 전역 변수 cnt를 활용해 0에서부터 +1하려고 했다. 이러면 각 출발점으로부터 각 점까지의 거리를 제대로 구할 수 없는데..
<br/>
다익스트라를 통해 출발점으로부터 각 정점까지의 최단 거리 계산할 수 있다!

[BOJ] 18352_특정 거리의 도시 찾기 / 실버2 / 30분 / X

---

week8/BOJ_11403/경로찾기_한의정.java

- 백준 11403 - [경로 찾기](https://www.acmicpc.net/problem/11403)
<br/>
> 시간 복잡도 : O(N^3)
i에서 j로 가는 길이가 양수인 경로가 있는지 없는지 구하기 위해
**중간 지점 k**를 잡는다.
그래서 시작점 i에서 중간 지점 k까지 경로가 있고,
중간 지점 k부터 도착 지점 j까지 가는 경로가 존재한다면,
시작점 i부터 도착점 j까지 이동 가능하므로 둘을 연결한다.
<br/>
- 어떻게 연결이 되는지 확인하나 → 중간 지점 잡고 (시작점-중간 지점)과 (중간 지점-도착점)이 연결되어있는지 확인 후 연결
<br/>
**플로이드-워셜 알고리즘**
- 모든 최단 경로를 구하는 알고리즘
- 두 노드를 잇고자 중간 노드를 선정해 (시작 노드 - 중간 노드)가 연결되어 있고, (중간 노드 - 도착 노드)가 연결되어 있다면, (시작 노드 - 도착 노드) 연결

[BOJ] 11403_경로 찾기 / 실버1 / 30분 / X

---

week8/BOJ_18352/특정거리의도시찾기_강아현.py

- 백준 18352 - 특정 거리의 도시 찾기
<br/>
> **BFS**
- bfs를 쓰는데 거리 리스트를 활용한다.
- X가 방문하는 위치까지의 거리를 리스트로 구하고 K와 같으면 출력한다.
<br/>
dist라는 거리 리스트를 활용할 생각을 하지 못했다.
<br/>
x

[BOJ] 18352_특정 거리의 도시 찾기 / 실버2 / 60분 / X

---

week8/BOJ_11403/경로찾기_강아현.py

- 백준 11403 - 경로 찾기
<br/>
> **BFS**
>> graph 생성
>> - 입력받은 그래프(in_graph)에서 행을 기준 노드로, 열을 단방향 이동 노드로 그래프(graph)를 생성한다.
>> bfs 함수
>> - 방문한 노드를 connect 리스트에 담아 리턴한다.
>> **Main**
>> - 1번 노드부터 N번 노드까지 돌면서 bfs 함수 실행한다.
>> - connect[0]은 bfs를 하는 기준 노드이므로 이를 out_graph의 행 인덱스로 한다.
>> - connect[1:]의 원소를 열 인덱스로 하여 해당 인덱스를 1로 바꾼다.
<br/>
처음에 문제가 이해가 안가서 헤맸다.. 책을 많이 읽어야겠다.
<br/>
x

[BOJ] 11403_경로 찾기 / 실버1 / 15분 / O

---

week8/BOJ_1058/친구_한의정.java

- 백준 1058 - [친구](https://www.acmicpc.net/problem/1058)
<br/>
> 시간 복잡도 : O(N^3)
1. N*N크기의 2차원 배열을 생성해 값을 입력받을 때 Y면 1을, N이면 INF (=9999) 값을 저장한다.
2. 플로이드-워셜을 통해 연결된 친구 수를 구한다.
- `출발지→경유지까지의 거리 A`와 `경유지 → 도착지까지의 거리 B`를 더한 값과 `출발지→도착지까지 가는 거리 C`를 비교해 `출발지 → 도착지까지의 거리`를 더 작은 값으로 갱신한다. (단, 세 사람 모두 다른 사람일 경우에만!)
3. 각 사람마다  다른 사람과 2-친구인 경우 (= 2차원 배열의 값이 2 이하인 경우)의 수를 구하고, 이를 최댓값과 비교해 갱신한다.
<br/>
- 플로이드-워셜을 사용할 생각을 떠올리는 것
- 2차원 거리 값 저장 배열을 (i,j)까지의 거리를 0이 아닌 큰 값으로 초기화해두고, 다른 점을 경유해 구한 거리와 비교해 작은 값으로 갱신하는 것
- 플로이드-워셜을 복습하자..
<br/>
X

[BOJ] 1058_친구 / 실버2 / 40분 / X

---

week8/BOJ_18352/특정거리의도시찾기_강한주.java

- 백준 18352 특정거리의도시찾기
<br/>
1. `ArrayList<Integer>[] Arr`을 사용
2. 도시의 개수만큼 배열을 만들었다
3. `Arr[a].add(b)`를 통해 a번 집에서 b번 집으로 갈 수 있는 단방향 도로를 추가했다
4. `visited`배열을 사용해 방문한 집인지/아닌지 판단
5. BFS 알고리즘을 사용해  visited에 방문거리를 기록했다
6. 정렬 후 조건에 맞는 결과 출력
<br/>
이번주 문제가 그래프 문제인데 이렇게 BFS로 풀어도 되는건가? 
일단 처음에 DFS로 풀려고 시도했는데 풀리지 않아 다른 사람의 코드를 참고했다. 
결국 풀지는 못한 문제지만 BFS에서 큐를 사용하는 아이디어를 제외한 나머지 코드는 그나마 비슷하게 적었다고 나 자신을 위로했다...ㅎ.... 
<br/>

[BOJ] 18352_특정거리의도시찾기 / 실버2 / 50분 / X

---

week8/BOJ_1446/지름길_한의정.java

- 백준 1446 - [지름길](https://www.acmicpc.net/problem/1446)
<br/>
> 다익스트라
- (시작점,도착점,지름길 길이)를 저장하는 객체 Road를 생성한다.
- Road형 배열에 객체 정보를 저장하고, 객체 배열은 지름길 길이 오름차순으로 정렬한다.
- 0부터 다익스트라를 진행한다.
<br/>
- 다....다익스트라
- 최단 거리 갱신하는 식
```
while(!pq.isEmpty()) {
    Road cur = pq.poll();
    int nowPos = cur.e; // 현재 위치
    
    // 현재 위치에서 도달 가능한 도로들 확인
    for(Road r : graph) { 
        if(r.s >= nowPos) { // 시작 위치가 현재 위치보다 뒤쪽에 있을 때
            if(r.e > D) continue; // 고속도로 길이 벗어나면 pass
                                
// ❗최단 거리 갱신 ❗
            if(dist[r.e] > dist[nowPos] + r.v + (r.s - nowPos)) { 
                dist[r.e] = dist[nowPos] + r.v + (r.s - nowPos);
                pq.offer(new Road(nowPos, r.e, dist[r.e]));
            }                    
        }
    }
    
// ❗ 현재 위치에서 고속도로 길이까지의 거리 고려해 …
```

[BOJ] 1446_지름길 / 실버1 / 40분 / X

---

week8/BOJ_18243/SmallWorldNetwork_한의정.java

- 백준 18243 - [Small World Network](https://www.acmicpc.net/problem/18243)
<br/>
> 시간 복잡도 : O(N^3)
- 2차원 최단 경로 배열을 만들어 모두 큰 값으로 초기화한다. (단, 행과 열이 같은 경우는 0으로 설정)
- 입력받은 두 점 간 거리를 1로 설정한다. (양방향)
- **플로이드-워셜**을 통해 모든 사람 간의 최소 거리를 구한다.
```
dist[i][j] = Math.min(dist[i][j], dist[i][k] + dist[k][j]);
```
- 7단계 이상인 단계가 존재하는 경우, Big World를 출력하고, 그게 아니면 Small World를 출력하게 한다.
<br/>
X
<br/>
X

[BOJ] 18243_Small World Network / 실버1 / 40분 / O

---

week8/PGS/k진수에서소수개수구하기_한의정.java

- 프로그래머스 [k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
<br/>
1. 입력받은 숫자를 k진수 문자열로 변환하고, 0 기준으로 분리해 배열에 저장한다.
```
String[] str = Integer.toString(n, k).split("0");
```
2. 1에서 만든 문자열 배열을 돌면서 해당 문자열이 비어있다면 pass하고, 그게 아니라면 long형으로 변환해 소수인지 판별하고 정답 갯수를 갱신한다.
<br/>
- 오버플로우 방지를 위해 int형이 아니라 long형으로 숫자를 입력받아야 한다.
- 소수인지 판별할 때 `i * i <= num` 하면 오버플로우가 발생하므로 제곱근 함수 `Math.sqrt(long num)`을 사용해야 한다..
<br/>
`Integer.toString(int number, int k)` : 숫자 number를 k진수로 변환해 문자열 타입으로 출력

[PGS] k진수에서 소수 개수 구하기 / 30분 / O

---

week8/BOJ_11403/경로찾기_강한주.java

- 백준 11403-경로찾기
<br/>
1. DFS알고리즘 활용
<br/>
DFS 알고리즘을 써야겠다는걸 캐치했지만 어떻게 코드를 작성한는건지 생각해내느라 시간이 좀 걸렸다(한주가 또 까먹었다)
그리고 만약 0행부터 dfs를 하면 그 행(=0)을 계속 기억하고 answer배열에 기록해야 하는데, 이걸 어떻게 하지? dfs매개변수로 선언해야 하나? 싶었는데 매개변수로는 코드가 잘 안짜져서 그냥 전역변수로 풀었더니 맞았다
하지만 내풀이 ... 마음에 들지 않는다. `Arrays.fill`로 visited배열을 채우는 것도 그렇고 뭔가 비효율적이라는 생각이 든다... 다른 사람의 풀이를 찾아봐야겠다. 
+) Arrays.fill 인텔리제이가 매개변수로 뭘 써야할지 안알려주면 2중 for문을 써서 visited를 채웠을 것 같다..... 
실제 코테 시험은 IDE없이 볼텐데 너무 IDE에 의지하지 말고 메서드좀 외워야겠다 
<br/>

[BOJ] 11403_경로찾기 / 실버1 / 50분 / O

---

week8/BOJ_1058/친구_강한주.java

- 백준 1058 - 친구
<br/>
1. <h3>플루이드 와샬</h3> 알고리즘을 사용했다
2. 2차원 배열 arr에 arr[i][j] -> i와 j가 친구면 1로 표시, 아니면 max값을 표시한다. 이때 i==j이면 어차피 친구가 아니므로 continue했다
3. 모든 배열을 돌며 2-친구 관계일 경우의 최댓값을 계산했다
<br/>
일단 3중 for문을 쓰면 풀 수 있는 문제지만, 시간초과가 날거라 생각해 시도를 안했다
나는 BFS로 풀 수 있지 않을까? 하며 코드를 작성해봤는데 2-친구 관계라는 조건을 해결 할 수 없어서 결국 다른 사람의 코드를 참고했다
플루이드-워셜 알고리즘을 처음 알게 되었다
-> 각 정점에서 다른 모~든 정점까지의 최단 경로를 찾는 알고리즘이다. 
-> 3중 for문을 사용한다
플루이드 워셜 알고리즘에서 3중 for문을 쓸 때 경유지를 첫 for문으로 두는 아이디어가 신기했다. 
<br/>
플루이드 워셜 알고리즘

[BOJ] 1058_친구 / 실버2 / 30분 / X

---

week8/BOJ_1058/친구_강아현.py

- 백준 1058 - 친구
<br/>
- graph를 1번 노드부터 N번 노드까지 거리가 2인 노드를 모두 구한다.
- friend.add를 이중 for문으로 구현하면 거리가 2인 노드까지를 구할 수 있다.
<br/>
x
<br/>
> **플로이드 워셜**
>
> '모든 지점에서 다른 모든 지점까지의 최단 경로를 모두 구해야 하는 경우' 에 사용할 수 있는 알고리즘
>
> - 단계마다 '거쳐 가는 노드'를 기준으로 알고리즘을 수행.<br>매 단계마다 방문하지 않은 노드 중에서 최단 거리를 갖는 노드를 찾을 필요가 없다.
> - 2차원 테이블에 최단 거리 정보를 저장.
>
>> **플로이드 워셜 알고리즘의 점화식**
>> $$D_{ab} = min(D_{ab}, D_{ak} + D_{kb})$$
>
>**플로이드 워셜 알고리즘 코드**
```python
import sys
input = sys.stdin.readline
INF = int(1e9)
n = int(input())
m = int(input())
graph = [[INF] * (n + 1) for _ in range(n + 1)]
for a in range(1, n + 1):
for b in range(1, n + 1):
if a == b:
graph[a][b] = 0
for _ in range(m):
a, b, c = map(int, input().split())
graph[a][b] = c
for k in range(1, n + 1):
for a in range(1, n + 1):
for b in range(1, n + 1): …
```

[BOJ] 1058_친구 / 실버2 / 60분 / O

---

week8/BOJ_1446/지름길_강아현.py

- 백준 1446 - 지름길
<br/>
> **플로이드 워셜**
- graph라는 최단거리 테이블을 생성한다.
- graph에서 graph[i-1]+1이 graph[i]보다 작다면 graph[i]를 graph[i-1]+1로 바꾼다.
- 현재 위치에 지름길이 존재한다면 `지름길이 끝나는 지점의 기존 graph 값`과 `지름길 시작 지점의 graph 값 + 지름길의 길이` 중 작은 값으로 지름길이 끝나는 지점의 graph 값을 바꾼다.
<br/>
앞서 푼 문제에서 알게된 플로이드 워셜을 사용해서 풀 수 있을 것 같았다. 0부터 D까지의 모든 수를 노드로 활용하여 풀어야겠다는 생각은 바로 했지만, 지름길의 길이를 적용하는 방법을 생각해내는데 시간이 많이 소요되었다.
<br/>
x

[BOJ] 1446_지름길 / 실버1 / 100분 / O

---

week8/BOJ_18243/SmallWorldNetwork_강아현.py

- 백준 18243 - Small World Network
<br/>
> **BFS**
>
> - distance : 노드 간의 거리
> - queue : (노드, 거리)를 하나로 묶어서 확인
> 방문하지 않은 노드까지의 거리가 최대 거리인 6을 넘지 않으면 friend 리스트에 추가한다.
- friends는 각 노드별 연결되어있는 노드의 개수를 구한 리스트.
- friends의 길이가 1이 아닌 경우는 이어져있지 않은 관계가 존재한다는 의미로 Big World이다.
- friends의 길이가 1인 경우, friends 내 원소의 값이 `전체인원수-1`이 아닌 경우는 안이어져있는 관계가 존재한다는 것으로 Big World
<br/>
x
<br/>
x

[BOJ] 18243_Small World Network / 실버1 / 60분 / O

---

week8/PGS/k진수에서소수개수구하기_강아현.py

- 프로그래머스 - k진수에서 소수 개수 구하기
<br/>
1. 10진수를 3진수로 변환한다.
2. 3진수로 변환한 수를 0을 기준으로 자른 후 리스트로 저장한다.
3. 2번 리스트 내의 소수의 개수를 구한다.
4. 1은 소수가 아니므로 1의 개수를 뺀다.
<br/>
x
<br/>
x

[PGS] k진수에서 소수 개수 구하기 / level2 / 20분 / O

---

week8/BOJ_13549/숨바꼭질3_강아현.py

- 백준 13549 - 숨바꼭질 3
<br/>
> **다익스트라**
- dist라는 리스트를 INF 100001개로 초기화한다.
- dist[N] = 수빈의 위치를 0으로 초기화
- hq에 (time, N) == (0, N)을 넣어준다.
- for 문으로 bfs와 같은 로직으로.
<br/>
다익스트라로 접근하는 방법을 생각하지 못했다. if문 만으로 풀 수 있는 방법을 생각하다가 도저히 생각이 나지 않았다. 다익스트라 알고리즘을 좀 더 공부해봐야할 것 같다.
<br/>
x

[BOJ] 13549_숨바꼭질 3 / 골드5 / 40분 / X

---

week8/BOJ_18243/SmallWorldNetwork_강한주.java

- 백준 18243-SmallWorldNetwork
<br/>
주석에 나름 꼼꼼히 작성
<br/>
처음에 문제를 보고 BFS나 어제 배운 워셜플루이든가 그거를 사용하면 되겠다고 생각했다.  그런데 뭔가 BFS에 꽂혀서 이 알고리즘으로 풀기 시작...
1. 노드가 1~n까지 있으면 1을 기준으로 이루어진 네트워크만 생각해서 bfs(1)만해서 틀림
2. bfs메서드 중 노드사이의 거리 distance를 전역변수로 두고 .. 갱신을 이상하게 해서 틀림
3. 만약 1->1로 가는 노드가 있다면 그 거리는 0으로 설정해야하는데 1로 설정하는 바람에 76%에서 계속 틀렸다
플로이드워셜 알고리즘을 활용해서도 풀어보겠다...
<br/>

[BOJ] 18243_SmallWorldNetwork / 실버1 / 60분 / X

---

week9/BOJ_1969/DNA_한의정.java

- 백준 1969 - [DNA](https://www.acmicpc.net/problem/1969)
<br/>
> 그리디
새 문자열을 구할 때 N개의 DNA의 k번째 문자들 중 가장 자주 등장한 문자를 새 문자열의 k번째 문자로 지정한다.
[출처](https://lotuslee.tistory.com/38)
<br/>
문제를 완전히 잘못 이해한 채 삽질하고 있었다.. 한 문자랑 다른 4개 문자를 비교하면서 해밍 거리를 구하는 건 줄 알았다.ㅠ
<br/>
X

[BOJ] 1969_DNA / 실버4 / 60분 / X

---

week9/BOJ_2503/숫자야구_한의정.java

- 백준 2503 - [숫자 야구](https://www.acmicpc.net/problem/2503)
<br/>
123~987 사이에 있는 숫자들 중에서 중복되는 숫자가 없고, 0을 포함하지 않은 수에 대해 스트라이크 수와 볼 수를 구한다. 
- 숫자의 스트라이크 수와 볼 수를 계산할 때는 해당 숫자를 문자열 형식으로 변환해 일치하는지 확인하면 된다.
```
private static int calBaseball() {
int result = 0;
for(int i = 123 ; i <= 987 ; i++) {
if(!isSame(i))  continue;   // 중복 숫자와 0 들어간 숫자 처리
int allTestPass = 0;  // 
for(int j = 0 ; j < N ; j++) {
int sCnt = 0;
int bCnt = 0;
Node now = arr[j];
String curStr = Integer.toString(now.num);
String myDataStr = Integer.toString(i);
// 스트라이크 확인
for(int idx = 0 ; idx < 3 ; idx++) {
if(curStr.charAt(idx) == myDataStr.charAt(idx))
sCnt++;
}
// 볼 확인
for(int b = 0 ; b < 3 ; b++) {
for(int c = 0 ; c < 3 ; c++) {
if(b == c) continue;
if(curStr.charAt(c) == myDataStr.charAt(b)) {
bCnt++;
}
} …
```

[BOJ] 2503_숫자 야구 / 실버3 / 50분 / X

---

week9/BOJ_2961/도영이가만든맛있는음식_강아현.py

- 백준 2961 - 도영이가 만든 맛있는 음식
<br/>
- 입력받은 재료의 신맛과 쓴맛 리스트로 1개의 재료를 사용하는 것부터 모든 재료를 사용하는 모든 조합을 구한다.
- 신맛과 쓴맛의 차이가 현재 정답값보다 작은 경우 이 값으로 업데이트한다.
<br/>
x
<br/>
x

[BOJ] 2961_도영이가 만든 맛있는 음식 / 실버2 / 10분 / O

---

week9/BOJ_2961/도영이가만든맛있는음식_한의정.java

- 백준 2961 - [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
<br/>
> 백트래킹
1. 1에서부터 N개까지 뽑도록 백트래킹을 진행했다. dfs 파라미터에는 신맛과 쓴맛을 포함해 갱신해서 값을 저장할 수 있도록 했다.
`DFS(재료 인덱스, 여태 사용한 재료 수, 사용할 재료 수, 신맛, 쓴맛)`
2. 원하는 재료 갯수만큼 뽑았을 때, 신맛과 쓴맛의 차이를 구하고, 이를 최솟값과 비교해 갱신한다.
<br/>
X
<br/>
- 반복문으로 1부터 N개를 모두 뽑도록 해서 dfs를 수행하도록 했는데 그렇게 작성하지 않아도 되었다! → 🔗 [참고 링크](https://jainn.tistory.com/203)
- 비트마스킹으로 푸는 방법도 찾아보았다. 다음에는 이 방법도 익혀서 시도해보는 것으로... → 🔗 [참고 링크](https://choco-fondue.tistory.com/m/73)

[BOJ] 2961_도영이가 만든 맛있는 음식 / 실버2 / 35분 / O

---

week9/BOJ_1969/DNA_강한주.java

- 백준 1969 - DNA
<br/>
1. 일단 `ArrayList<String>`을 이용해 모든 DNA를 입력받았다
2. `int[] dna = new int[4]` 배열로 각각의 DNA 원소를 count하려고 했다
3. `ArrayList<Character> answer`을 이용해 Hamming Distance DNA를 저장하려고 했다
4. 2중 for문을 활용하여 각 dna의 자릿수(0열~ m-1열)를 돌아 A,C,G,T가 얼마나 나왔는지 dna[]에 기록한다
-  dna배열을 돌아 가장 많이 나온 원소와 그 index를 기록한다
-  index = 0이면 A, 1이면 C,,,,, 이렇게 해서 answer에 기록
-  dna배열은 다시 0으로 채워준다. 
5. 2중 for문을 이용해 Hamming Distance를 구한다. 
<br/>
일단 실버4 구현 문제라 아 ㅋㅋ 20분 컷해버려야지 ㅋㅋ 했다가 .... 문제에게 뼈맞았다.....ㅎ...
처음 문제는
<h3>자료구조를 어떤걸 사용할 것인가?</h3>였다. 
DNA를 배열이나 ArrayList에 기록까진 괜찮았다. 
하지만 어떻게 각각의 DNA 자릿수(0열~m-1열)을 돌며 가장 많이 나온 DNA 원소를 기록해야 할지 몰랐다.... 
`ArrayList<Character>`과 `HashSet<Character>`, `Map`까지 고려해봤지만 코드가 써지질 않았다.....
결국 하드코딩을 하기로 마음을 먹고 dna 배열과 answer ArrayList, 엄청난 길이의 `if-else`문, 기록 해주는 변수 `max,index`를  활용해 풀었다. …

[BOJ] 1969_DNA / 실버4 / 35분 / O

---

week9/BOJ_2961/도영이가만든맛있는음식_강한주.java

- 백준 2961 - 도영이가 만든 맛있는 음식
<br/>
1. `Ingredient[][2]` 2차원 배열을 선언해서 신맛과 쓴맛을 입력받았다
2. <h3>부분집합</h3> 아이디어를 활용했다. 
`subSet(int index,int mulSour,int sumBitter)`
- index: index번째 재료를 넣을지 말지 고려한다
- mulSour: 지금까지 총 신맛
- sumBitter: 지금까지 총 쓴맛
3. 
- 재료를 넣은 경우
- 재료를 넣지 않은 경우
로 나누어 재귀함수 처리
4. `index == n`으로 모든 재료를 고려한경우를 종료 조건으로 준다. 
이때 재료를 아무것도 넣지 않은 경우, 문제의 조건에 어긋나므로 return Integer.MAX_VALUE를 주었다. 
<br/>
일단 `조합`으로 풀 수 있을 줄 알았다. 
서로다른 n개중 r개의 재료를 선택했을 때.....신맛,쓴맛을 구해서 비교하면 되지 않나 ?!
하지만 직접 코드를 작성해보려니 문제가 있었다.
5개의 재료중 1개를 선택한다 했을때 조합은 '서로 다른 5개중 1개를 선택할 수 있는 경우의 수' = 5 는 구할 수 있지만 5개 중 몇번째(index)를 고른건지는 알 수가 없었다. 
그래서 이 문제에는 적합하지 않았다..... 
'조합'과 '부분집합'의 문제를 잘 구분해야겠다 😭
<br/>
부분 집합의 코드, index를 고려했을때와 안고려했을때로 나눠 재귀함수를 호출한다.

[BOJ] 2961_도영이가만든맛있는음식 / 실버2 / 40분 / X

---

week9/BOJ_2615/오목_강한주_1.java
week9/BOJ_2615/오목_강한주_2.java

- 백준 2615 - 오목
<br/>
(방법 1 : 정석)
1. 배열을 돌며 1,2가 저장된 곳의 x,y좌표 바둑알의 갯수 cnt 변수를 이용해 탐색을 진행한다
2. 탐색은 가로,세로,대각선1,대각선2 로 총 4가지 루트가 있다
3. 이때 배열 int[][] d를 이용해서 <h3>양방향 모두 탐색</h3>을 진행한다
4. cnt == 5이면 종료한다
(방법 2: 하드코딩)
1. findRow, findCol, findRightDiag, findLeftDiag 4개의 메서드 생성
2. 각각 안에 plus와 total 변수를 선언해 양방향으로 몇 개의 똑같은 바둑 알이 나왔는지 센다. 
3. 양방향 탐색을 위해 각 메서드 안에 while문이 2개나 들어갔다 또한 plus = 1로 초기화를 해주었다. 
4. leftDiag로 탐색했을 때는 가장 왼쪽에 있는 바둑알의 위치를 출력해야 해서 
row = i+5; col = j - 3으로 따로 값을 주었다
<br/>
일단.... 저번과 똑같은 문제에서 막혔다는게 참 기분이 그렇다...하하 
문제를 풀면서 내가 저번에도 '양방향'이라는 포인트에서 막혔지 !! 라고 생각이 나서 어찌저찌 하드코딩해서 풀었지만
<h3>방향 배열</h3>을 선언하는 건 까먹어 버렸다..... 
이렇게 '방향을 정해서 탐색'하는건 dir 배열을 만드는걸 고려해봐야겠다 !!! 제발 기억해 !! 제발 생각해내 !!!!!!!!!
<br/>
틀린 문제는 다음에 또 틀린다... 복습을 하자...

[BOJ] 2615_오목 / 실버1 / 70분 / O

---

week9/BOJ_15661/링크와스타트_강한주.java

- 백준 15661 - 링크와 스타트
<br/>
1. <h3>부분집합</h3>을 활용했다. 
2. 도영이요리 어쩌구 문제와 다른 점은 `visited` 배열을 활용해야 한다는 점이다
3. `subSet(int index)`메서드를 사용해서 index번째 사람을 start 팀원으로 넣을지 link  팀원으로 넣는 경우로 나눠 재귀함수를 이용
<br/>
도영이요리 문제와 너무 비슷한 문제길래 
‼️아 부분집합을 활용하면 되겠구나 했다. 그리고 부분집합으로 접근을 했다.
하지만.... 나는 1을 알려주면... 1만 아는 사람인가?.... 조금 응용한건데 풀지못했다..........
내가 막힌건
(4명의 player: 1,2,3,4가 있다고 가정하자)
- 1번을 뽑았을때 1번과 같은 팀인 j번인 사람이 있어야 능력치를 계산할 수 있는데 이걸 어떻게 하지?....
였다. 
즉, 도영이문제는 재료가 독립적인데 이 문제는 플레이어끼리 독립적이지 않고 i번째 플레이어와 j번째 플레이어를 '같이' 고려해야 하는 문제여서 이 부분에서 막혔다.
방법은 간단했다
`visited` 배열을 사용하면 됐다. 이 배열은 내가 팀으로 뽑은 사람을  `true`로 두고 뽑지 않은 사람을 `false`로 두면 된다. 
<br/>
visited 배열을 사용하는 아이디어

[BOJ] 15661_링크와스타트 / 골드5 / 40분 / X

---

week9/BOJ_14500/테트로미노_강한주.java

- 백준 14500 - 테트로미노
<br/>
1.  <h3>DFS</h3>를 활용하는 아이디어를 생각해 내야 풀 수 있는 문제다. 
이 문제는 테트로미노의 모양에 집착할 필요가 없다. DFS를 사용해 무작위 4방향으로 뻗어나가게 두면 그게 테트로미노의 전체 모양이 된다 (ㅗ 모양은 예외다)
2. 4방향으로 뻗어나가기 위한 배열 `dx, dy`를 선언한다
3. 방문한 칸을 표시하기 위해  `visited` 배열을 선언했다
4. 2중 for문을 돌며 모든 칸에 대해 '탐색'을 시작한다. 
- `dfs(int x,int y,int depth,int sum)`으로 매개변수를 설정하는 것이 중요하다. 
- depth == 4라면 4개의 조각을 다 배치한 것이다. depth ==4 를 종료조건으로 설정한다
- 총 4개의 방향(상하좌우)를 탐색하며 유효 범위안에 들면 depth+1하고 sum을 추가로 더해줘 다시 재귀함수를 호출한다.
5. 'ㅗ' 모양의 경우  아래와 같이 depth == 2일때 '양방향'으로 갈라져야 한다. 즉 기존의 상하좌우 탐색으로는 'ㅗ'모양을 만들 수 없다. 
따라서  depth == 3일때  탐색의 시작하는 위치 를 depth == 2일때의 칸으로 지정해서  다시한번 탐색을 진행해야 한다. 
3
1 2 4
<br/>
문제에서 막힌 점은 "회전을 어떻게 해야 하는가?" 였다. 
내가 생각한 방법은 회전까지한 모든 경우의 수 (총 11가지)의 경우를 배열로 짜고 일일히 탐색하는.... 거였다
하지만 위의 방법은 코드가 200줄이 넘어갈 것 같고 문제가 의도한 방식이 아닌 것 같아 재빠르게 다른 …

[BOJ] 14500_테트로미노 / 골드4 / 40분 / X

---

week9/BOJ_14500/테트로미노_한의정.java

- 백준 14500 - [테트로미노](https://www.acmicpc.net/problem/14500)
<br/>
> DFS
필요 자료구조
- 상하좌우 방향 탐색 위한 dx/dy 배열
- 중복된 칸 뽑지 않기 위한 방문표시 배열 ⭐
1. 2차원 격자 내의 모든 점에 대해 연속된 4개의 점을 뽑도록 깊이가 4일 때 종료하는 dfs함수를 만든다. 종료 조건이 아닌 값은 상하좌우 방향을 탐색하며 격자 범위 내에 있는 방문한 적 없는 칸을 방문하며 탐색을 진행한다.
> dfs(행, 열, 뽑은 점 갯수, 합)
2. 'ㅜ'자 모양은 회전시키면 ㅓ,ㅏ,ㅗ로 만들 수 있어 해당 칸과 상하좌우로 인접한 4칸 중 3칸을 고르는 dfs를 진행한다. (조합)
<br/>
- 4방향 탐색할 때 직접 좌표 값 (0,-1), (0, +1),... 이렇게 변경하면서 dfs 돌리려고 했는데 그게 아니었다.ㅋㅋㅋㅋ
- ㅜ자 모양 처리 방법. 인자로 중심점 본인의 위치를 계속 가져가고 그 중심점에서 인접한 4칸 중 3칸을 찾는 것이었다..
<br/>
- T자형 처리를 위한 dfs 방법

[BOJ] 14500_테트로미노 / 골드4 / 50분 / X

---

week9/PGS/행렬테두리회전하기_강한주.java

-프로그래머스 - 행렬 테두리 회전하기
<br/>
1. 배열 회전 방법만 안다면 풀 수 있는 문제
<br/>
😭일단... 내가 배열 회전을 하는 방법을 ...... 까먹었다..... 12월쯔음 의정언니랑 자바에서 배열 회전하는 방법에 대해서 말하다가
1. 원소를 밀기
2. 원소를 당기기 
이 두가지 방법에 대해서 말하고 원소를 당기는게 훨씬 편하다는걸 캐치 했는데 .... 그게 기억이 안났다
그때도 분명 나는 '밀기'방법을 택해서 변수도 많아지고 로직이 많이 꼬여서 해당 문제를 어렵게 해결했다. 
그리고 '당기기'로 푸는게 훨씬 쉽다는걸 깨달았는데... 그걸 또 까먹었다.... 
결국 이번 문제도 '밀기'방법에 얽매여 있다가 로직이 계속 꼬여서 다른 사람의 풀이를 참조했다.
'당기기'로 회전한다면 매우 쉬워지는 문제였다. 
<br/>
<h3>배열의 회전은 당기기</h3>로 풀자

[PGS] 행렬테두리회전하기 / level2 / 45분 / X

---

week8/PGS/k진수에서소수개수구하기_강한주.java

- 프로그래머스 - k진수에서 소수 개수 구하기
<br/>
1.정수 n을 k진수로 변환한다.
2. 변환된 k진수 문자열에서 "0"을 기준으로 분리하여 각 부분이 소수인지 확인한다.
3. 소수가 맞다면 answer++ 
<br/>
로직 자체는 간단해서 풀이를 생각해내는데에는 어려움이 없었다.. 하지만 문제는 나의 가난한 코딩실력... 덕분에 시간이 오래 걸렸다. 
입력값이 클 수 있다는걸 고려 안하고 `Integer.parseInt(number)`를 써서  테스트 케이스 1번과 14번인가가 계속 런타임 오류가 났다. 도저히 틀린점을 못찾겠어서 반례를 찾아봤다.
`Long.parseLong(number)`을 써야 입력값이 커도 제대로 처리할 수 있었다. 
실제 코테 시험에 나왔으면 테스트케이스 1,2번만 맞을걸 보고 바로 '타입,입력값'을 고려안한채 바로 제출해서 틀렸을 것 같다.
<h3>입력값의 범위를 잘 보고 타입을 정하자!! int에 속아 long을 잊지말자</h3>
그리고 소수인지 확인할때 범위를 `Math.sqrt()`을 써야 한다. num/2 같이 썼다간 바로 시간초과가 뜬다 !! ( Math.pow()랑 Math.sqrt()를 헷갈린..)
<br/>

[PGS] k진수에서소수개수구하기 / level2 / 50분 / X

---

week9/PGS/행렬테두리회전하기_한의정.java

- 백준 10164 - 행렬테두리회전하기
<br/>
시계 방향으로 행렬을 회전하고, 회전 후의 최솟값을 반환한다. 이 때 배열들의 값을 시계 방향으로 회전할 것이지만 가져오는 값의 방향은 반시계 방향 위치의 값을 가져오는 것이므로 dx/dy 배열은 반시계 방향 순서(남동북서 순서)로 저장한다.
본인 기준 반시계 방향 위치에서 값을 가져오면서, 지정 범위를 벗어나게 되면, 방향을 전환한다.  방향을 전환하다가 dx/dy배열의 크기를 넘어가게 되면 테두리 한 바퀴 회전을 다한거니까 회전을 종료한다.
마지막에 값을 끌어오다 보면 시작 위치의 한 칸 오른쪽 값은 비게 되는데 이 값은 시작 위치의 값으로 채운다.
<br/>
값을 끌어온다는 개념은 기억해냈는데 dx/dy 배열은 그럼 어떻게 선언하고 활용해야 하는지는 잘 기억하지 못 했다.
<br/>
X

[PGS] 행렬테두리회전하기 / level2 / 40분 / X

---

week10/BOJ_10164/격자상의경로_한의정.java

- 백준 10164 - [격자상의 경로](https://www.acmicpc.net/problem/10164)
<br/>
> DP (시간 복잡도 : O(NM)
1. 2차원 배열을 1부터 증가하는 순서대로 값을 입력하고, 해당 칸의 번호가 K라면 해당 위치를 변수 ox와 oy에 저장한다.
2. 현재 칸(x,y)까지의 이동 경로의 수를 나타내는 2차원 int형 배열을 만든다. 그리고 K를 꼭 거쳐야하므로 ① (0,0)부터 K가 있는 위치 (ox, oy)까지 dp 한 번, ② K가 있는 위치부터 (N-1,M-1)까지 가는 진행하는 dp 한 번 하며 점화식을 통해 2차원 배열을 채운다.
```java
dp[i][j] = dp[i-1][j] + dp[i][j-1];  // 오른쪽과 아래쪽으로만 이동 가능하다고 했으므로
```
<br/>
X
<br/>
X

[BOJ] 10164_격자상의 경로 / 실버1 / 35분 / O

---

week10/BOJ_17213/과일서리_한의정.java

- 백준 17213 - [과일 서리](https://www.acmicpc.net/problem/17213)
<br/>
> DP
1. M*M 크기의 2차원 배열 dp를 만든다.
```java
dp[i][j] : 과일 종류 j개 중 i개를 훔치는 경우의 수
```
2. dp배열의 초기값을 채운다.
- 과일 i종 중 중 i개 훔치는 경우의 수 = 1
- 과일 1종 중 중 i개 훔치는 경우의 수 = 1
3. 나머지 원소들은 점화식을 통해 채운다.
```java
dp[i][j] = dp[i-1][j-1] + dp[i-1][j]
```
<br/>
- 처음에 모든 종류에서 한 가지씩 훔친 상태에서 남은 훔쳐야할 갯수를 마음대로 만드는 조합의 경우의 수를 만들어봐야하나 하고 고민했었다..
- 직접 경우의 수를 그려보고 나서야 dp 점화식을 만들 수 있었다..
<br/>
X

[BOJ] 17213_과일 서리 / 실버2 / 30분 / O

---

week10/BOJ_9081/단어맞추기_한의정.java

- 백준 9081 - [단어 맞추기](https://www.acmicpc.net/problem/9081)
<br/>
1. 단어 맨 뒤에서부터 처음으로 감소하는 부분의 위치 idx1를 찾는다.
```
int idx1 = -1;
for(int i = len - 1 ; i > 0 ; i--) {
if(ch[i - 1] < ch[i]) {
idx1 = i - 1;
break;
}
}
```
2. 다시 단어 맨 뒤에서부터 감소하는 부분보다 처음으로 큰 부분 idx2를 찾는다.
```
int idx2 = 0 ;
for(int i = len - 1 ; i >= 0 ; i--) {
if(ch[idx1] < ch[i]) {
idx2 = i;
break;
}
}
```
3. idx1과 idx2 위치의 값을 swap한다.
4. idx1의 뒷 부분을 오름차순으로 정렬한다.
<br/>
이런 아이디어를 생각해 내는 것...
처음에 조합으로 모든 문자 다 만들어보고 정렬해서 다음에 나오는 문자 찾도록 풀어봤었는데 이게 아니었다.. 그래서 결국 다른 사람들 풀이를 확인했다.
<br/>
이런 아이디어....?

[BOJ] 9081_단어 맞추기 / 실버1 / 50분 / X

---

week10/BOJ_15489/파스칼삼각형_강한주.java

- 백준 15489-파스칼삼각형
<br/>
1. DFS를 써서 푸는 방식이다.
2. 매개변수에 무엇을 쓸 지 생각하고 `visited`배열을 쓰는걸 떠올리면 쉬워지는 문제다. 
<br/>
하....... 이문제는 불과 2~3주전에 틀렸던 유형이다............... 🤬🤬
마지막 else 문에서
`return combination(n-1,r-1) + combination(n-1,r)`로 작성했는데 아무리 봐도 내 코드는 틀린게 없어!!!! 이러다가 결국 파스칼씨에게 지고 말았다..... 
`visited[n][r] = combination(n-1,r-1) + combintaion(n-1,r)`로 적어서 visited에 반영을 해줬어야 했는데... 어쩐지 계속 테두리만 1로 채워지길래... 계속 뭐지뭐지? 했다... 
오늘 잠을 적게 자서 수업시간에도 진짜 어이없는거 질문 하고 계속 졸았는데 잠을 적게자서 그런거라 생각하고 싶다 😭😭😭😭😭😭😭😭😭😭😭😭😭😭
+) combination 메서드를 써놓고 여기에 숫자를 어떻게 채우지?.. 를 10분동안 고민했다... 이것도 잠을 못자서 그런거라 생각하겠다.
<br/>

[BOJ] 15489_파스칼삼각형 / 실버4 / 50분 / X

---

week10/BOJ_10164/격자상의경로_강한주.java

- 백준 10164 - 격자상의 경로
<br/>
1. 점화식 `visited[r][c] = move(r,c-1) + move(r-1,c);`를 세워야 한다. 
<h3>컴퓨터 말고 사람이 먼저 어떻게 푸는지 생각해보면 점화식이 세워지는 것 같다. </h3>
2. 1에서 k가고, k에서 (n-1,m-1)까지 2차례를 거쳐서 가야 하므로 변수 startX,startY 를 사용했다
3. startX와 startY는 유효범위를 위해 사용하는 변수다. 예를들어 (3,3)에서 (5,4)로 이동할때 (4,2)같이 범위를 벗어나는 곳을 탐색하면 안된다. 
<br/>
처음에 접근법: (n-1,m-1)까지의 최소 거리는 `Math.min((n-1,m-2)까지의 최소거리 + 1, (n-2,m-1)까지의 최소거리 + 1)` 인줄 알았다. 
그런데 문제에서 k가 있으면 k를 꼭 거쳐야 하는 조건이 있어서 문제가 복잡해졌다. 
'워셜 플루이드' 문제인가? 싶었는데 워셜 플루이드 알고리즘이 내머릿속에서 거의 지워진 상태였기때문에 다른 방법은 없나 고민했다(겨우 2주지남)
계속 보다보니  초등학생때 풀었던 '길찾기'문제가 생각났다. 
생각나자마자 빠르게 점화식을 세울 수 있었다. 
그런데 이걸 코드로 옮기기 까지가 시간이 오래걸렸다. 이것도 어찌보면 combination문제인데 아직도 익숙지 않나보다.... 계속 연습해야 겠다. 
<br/>
워셜 플루이드로도 풀 수 있나요?

[BOJ] 10164_격자상의경로 / 실버1 / 45분 / O

---

week10/BOJ_9081/단어맞추기_강한주.java

- 백준 9081 - 단어맞추기 
<br/>
1. 사전순 정렬의 규칙을 찾는다
> 단어를 끝에서부터(i) 자신의 앞 알파벳과 비교를 한다(i-1)
> 비교했을 떄 자신의 앞 알파벳이 더 작으면(예: CE, AB, DE같은거) 정렬을 해야한다는 뜻이다.
> SHUTTLE에서 H뒤에있는 UTTLE에서 H 다음으로 큰 알파벳인 L을 찾는다
> 그 다음 H와 L을 swap 한다.
> 다음에 H의 인덱스였던(1) 뒤에 있는(2~6) UTTHE를 sort하면 끝이다
2. 코드로 구현
<br/>
일단 문제에서 '사전순 정렬'의 예시를 보여줬는데 이해를 못해서 10분을 소비했다.... 알파벳으로 보니까 모르겠어서 숫자로 치환해서 보니 규칙이 보였다. 
<h3>알파벳이 헷갈리면 숫자로 치환해서 보자</h3>
StringBuilder를 쓸 생각을 못해서 계속
`subString`을 쓰다보니 코드가 엄청 길어지고 나도 보는데 계속 헷갈렸다... 
String을 Char로 바꾸고 그 Char의 index를 찾고..하다보니 변수도 계속 많아져서 코드가 매우 복잡해졌다. 
결국 40분이 지났길래 그냥 다른사람의 코드를 참고했다...
개인적으로 문제 풀이는 아는데 코드로 못 옮겨 적었을때가 가장 아쉬운것 같다...흑흑...흑흑...😭😭😭
그래도 전 DP문제는 접근도 못했던 거에 비해 ... 이문제는 접근이라도 할 수 있었어서 행복합니다(?) 
<br/>
앞으로 `StringBuilder`를 사용하보자!
Arrays.sort에 3개 매개변수를 썼을때 범위를 지정해서 sort 할 수 있다 !

[BOJ] 9081_단어맞추기 / 실버1 / 40분 / X

---

week10/BOJ_1394/암호_한의정.java

- 백준 1394 - [암호](https://www.acmicpc.net/problem/1394)
<br/>
1. 해당 문자가 쓰인 첫 순서를 기록할 1차원 배열 arr을 만든다. (크기는 200)
2. 문자열 목록을 돌며 해당 문자가 처음으로 등장하는 경우에만 인덱스를 기록한다.
```
for(int i = 0 ; i < words.length() ; i++) {
int idx = words.charAt(i) - '!';    // ! : 사용될 수 있는 가장 작은 수의 문자
if(arr[idx] == 0)   // 해당 문자가 처음으로 등장하는 경우에만 인덱스 기록
arr[idx] = i + 1;
}
```
3. 컴퓨터 암호에 대해 처리한다.
```
for(int i = 0 ; i < pwd.length() ; i++) {
int idx = pwd.charAt(i) - '!';
ans *= words.length();
ans += arr[idx];
ans %= MOD;
}
```
<br/>
이런 아이디어를 생각해 내는 것...
사실 풀이를 봤음에도 이해가 제대로 되지 않았다..🤯
컴퓨터 암호 처리에 대한 식 부분이 제대로 이해가 되지 않는다,,,,
<br/>
이런 아이디어..

[BOJ] 1394_암호 / 골드5 / 50분 / X

---

week10/PGS_92341/주차요금계산_한의정.java

- 프로그래머스 92341 - [주차 요금 계산](https://school.programmers.co.kr/learn/courses/30/lessons/92341)
<br/>
필요 자료구조
> - (차량 번호, 입차시간) 저장용 Map1
> - (차량 번호, 누적 주차 시간) 저장용 Map2
> - (차량 번호, 누적 시간, 주차 요금)을 저장하는 객체 리스트 ⇒ 나중에 차량번호 작은 순으로 오름차순 정렬 가능
1. records 배열을 돌면서 IN을 입력받은 경우, 이미 맵에 해당 차량의 정보가 없고, 시간이 23:59가 아닌 경우, Map1에 해당 차량의 번호와 입차 시간을 저장한다.
2. OUT을 입력 받은 경우, Map1에 해당 차량 번호의 입차시간이 존재한다면, 누적 주차 시간을 계산해 Map2에 값을 저장하고 Map1에서는 키를 삭제한다. (빠져나갔음을 표시하기 위해 삭제)
3. Map1에 남은 주차 중인 차들을 처리한다. (23:59 - 입차시간) 계산한 값을 이용해 Map2에 누적 주차 시간을 갱신한다.)
4. 모든 차량 번호에 대한 주차 요금을 계산하여 (차량 번호, 누적 시간, 주차 요금)을 객체 리스트에 저장한다.
5. 저장한 객체 리스트를 차량 번호가 작은 순(=오름차순)으로 정렬한다.
6. 리스트의 값을 배열로 옮겨 담아 출력한다.
<br/>
- 문자열 분리할 게 많아서 좀 헷갈렸다....
- 주차 요금 계산할 때 나눗셈 할 때 자료형 주의 (정확한 나눗셈을 위해 꼭 double을 써줘야 한다..)
```
(int)Math.ceil((time - basicTime) / …
```

[PGS] 주차 요금 계산 / level2 / 70분 / O

---

week10/BOJ_1394/암호_강한주.java

- 백준 1394-암호 
<br/>
1. 사용한 자료구조,클래스
>Code 클래스: 암호 문자를 서로 비교할 수 있는 클래스 
> Code[] codes : 암호로 사용할 수 있는 문자들
> String computerCode : 맞춰야 하는 암호
2. Code 클래스에서 codes 배열을 알파벳 순으로 정렬할 수 있게 적절히 `Overriding`하는게 중요한 것 같다. 
3. 주석에 나름 꼼꼼히 적혀있다. 
<br/>
그냥 문제를 보고 어떤 자료구조를 써야할 지 감도 안온 문제다.... 골드5 문제중에 가장 골드5답지 않다고 느낀 문제였다....(골드 3정도는 되어야하는거 아닙니까?)
암호를 구하는 점화식은 도대체 어떻게 세우는건지
Code객체를 만들 생각은 어떻게 하는지..
자료구조 어떤걸 쓸 지 생각은 어떻게 하는건지...
그냥 압도적으로(?) 몰라서 다른 사람의 풀이를 보는데 풀이조차 이해하는데 시간이 오래 걸렸던 문제다. 
+) 심지어 풀이 코드도 틀려서 수정한 문제... 참고로 Code클래스의 equals는 안쓰인다. equals가 도대체 어디에 쓰이는거지?하고 한참을 고민하다가 쓰지않고 제출해봤는데 맞았다... ? 
<br/>
이런 아이디어.....

[BOJ] 1394_암호 / 골드5 / 40분 / X

---

week1/BOJ_18114/블랙프라이데이_강한주/블랙프라이데이Re_강한주_이진탐색.java
week1/BOJ_18114/블랙프라이데이_강한주/블랙프라이데이Re_강한주_조합_시간초과.java
week1/BOJ_18114/블랙프라이데이_강한주/블랙프라이데이Re_강한주_해시맵.java
week1/BOJ_18114/블랙프라이데이_강한주/블랙프라이데이_강한주.java
week1/BOJ_2548/대표자연수Re_강한주.java

- 백준 18114 - 블랙 프라이데이 
<br/>
1. 이진 탐색(HashMap 사용)
2. 이진 탐색(binarySearch 구현)
<br/>
처음에 보고 '이진 탐색'을 썼던 것이 기억 났지만 '조합'으로 풀고 싶어져서 풀었다. 
결과는... 시간초과 ‼️‼️
조합으로 푸는 경우 모~든 경우의 수를 구하기 때문에 시간복잡도는 `O(2^N)`이 된다. 여기서 N은 물건의 개수이다. 따라서 물건의 개수가 많으면 계산량이 기하급수적으로 늘어난다.
이진탐색으로 푸는 경우 시간 복잡도는 `O(logN)`이다. 
겨우 2달만인데 이진탐색이 뭐였는지 잘 기억이 나질 않았다.... 코드를 써보니까 이제서야 떠올랐다...😂😂
이 문제는 '이진 탐색'으로 푸는 건데, 자바의 `HashMap`을 사용하면 굳이 이진탐색 코드를 작성하지 않아도 `.contains`를 이용해 문제를 풀 수있다... 
이런 `HashMap`을 쓸 생각을 하다니... 나도 자료구조에 얼른 익숙해져야 겠다. 
‼️ 이진 탐색도 까먹지 말기 
<br/>

[BOJ] 18114_블랙프라이데이Re/ 골드5 / 40분 / X

---

week1/BOJ_11399/ATMRe_강한주.java
week1/BOJ_1251/단어나누기Re_강한주.java
week1/BOJ_1449/수리공항승Re_강한주.java
week1/BOJ_1931/회의실배정Re_강한주.java
week1/BOJ_2470/두 용액_강한주.java
week1/BOJ_2548/대표자연수Re_강한주.java

- 백준 11399 ATM
- 백준 1931 회의실 배정
- 백준 1449 수리공항승
- 백준 1251 단어나누기
- 백준 2470 두 용액
<br/>
- 회의실 배정에서 아이디어는 생각났지만 코드를 너무 복잡하게 짜서 계속 틀렸다. compareTo를 Overriding하는법을 다시 익혔다..(다음엔 안보고 짤수있기를!!)
- ATM : prefix Sum을 이용한 문제다. 오랫만에 다시 이 개념을 적용하게 되었다
- 두용액 : 투 포인터와 이진탐색 생각을 못하고 단지 정렬해서 양끝의 수를 더해주는 줄 알아서 시간이 좀 걸렸다
- 수리공항승: 무난
- 단어나누기:전에는 for문으로 단어 순서를 바꿨는데 이번엔 `StringBuilder`를 사용함 
<br/>

BOJ 1주차 복습 

---

week11/BOJ_1205/등수구하기_한의정.java

- 백준 1205 - [등수 구하기](https://www.acmicpc.net/problem/1205)
<br/>
> 구현
1. 1차원 int형 배열에 점수를 순서대로 입력받는다.
2. 현재 랭킹 리스트가 꽉 차있고(N==P), 태수의 새로운 점수가 최하위 점수보다 작거나 같다면 랭킹에 진입하지 못하므로 -1을 출력한다. /  랭킹 리스트가 꽉 차 있지 않은 경우에는 입력받은 숫자들과 태수의 점수를 비교하며 순위를 매긴다.
<br/>
- 코드를 보면 간단한 문제인데 오히려 어렵게 생각해서 시간을 많이 쓰게 되었다.. (Map에 점수 넣고 순위 넣고 막 이랬다..)
- N이 P보다 작다는 것을 문제에서 눈으로 보기만 하고, 실제로 그렇게 점수들을 P보다 작은 N개 입력받았을 경우를 생각하지 못 했다.
<br/>
X

[BOJ] 1205_등수 구하기 / 실버4 / 120분 / X

---

week11/BOJ_1138/한줄로서기_한의정.java

- 백준 1138 - [한 줄로 서기](https://www.acmicpc.net/problem/1138)
<br/>
> 구현 (그리디)
1. int형 1차원 배열 arr에 키들을 순서대로 입력받는다.
2. 키가 큰 순으로(=역순으로) 입력받은 키를 ArrayList에 삽입한다.
예제 1) 2 1 1 0
- 키가 4인 사람 arr[4]이 0일 때, 리스트의 0번째에 4를 삽입한다. →  list : [**4**]
- 키가 3인 사람 arr[3]이 1일 때, 리스트의 1번째에 3을 삽입한다.  → list : [4, **3**]
- 키가 2인 사람 arr[2]이 1일 때, 리스트의 1번째에 2를 삽입한다.  → list : [4, **2**, 3]
- 키가 1인 사람 arr[1]이 2일 때, 리스트의 2번째에 1을 삽입한다. →  list : [4, 2, **1**, 3]
<br/>
이 아이디어를 생각해내는 것...
코드는 초간단해서 놀랐다,,,
<br/>
**`.add(int idx, E e)`** : idx 위치에 객체 e 추가

[BOJ] 1138_한 줄로 서기 / 실버2 / 35분 / X

---

week11/BOJ_2607/비슷한단어_한의정.java

- 백준 2607 - [비슷한 단어](https://www.acmicpc.net/problem/2607)
<br/>
1. 첫 번째 문자만 따로 입력받는다.
2. 각 알파벳이 등장한 횟수를 저장하는 배열을 크기가 26인 int형 배열을 생성해 첫 번째 문자열에 나온 알파벳들의 등장 횟수를 저장한다.
```
int[] alphabet = new int[26];
for(int i = 0 ; i < first.length() ; i++) {
alphabet[first.charAt(i) - 'A']++;
}
```
3. N-1번 아래 과정을 반복한다.
- 등장횟수가 저장된 알파벳 배열을 복사한 배열을 만든다. → `int[] tmp = alphabet.clone();`
- 해당 단어를 돌면서 각 알파벳의 등장 단어 수가 0 이상이라면(= 첫 번째 단어에도 해당 알파벳이 존재한다면), 복사한 배열의 알파벳 칸의 값을 1 빼고, 같은 단어 갯수는 1 더한다. 
```
int cnt = 0;    // 같은 단어 개수
for(int i = 0 ; i < word.length() ; i++) {
if(tmp[word.charAt(i) - 'A'] > 0) {
cnt++;
tmp[word.charAt(i) - 'A']--;
}
}
```
- 기준 문자열 길이와 비교 문자열 길이를 비교해 비교 문자열의 길이가 한 글자 짧거나 긴 경우 / 길이가 같은 경우 정답에 1을 더한다.
<br/>
- 알파벳 등장횟수를 Map으로 저장해 사용하려고 했다. → 크기가 26인 알파벳 등장횟수 저장 배열을 만들어 …

[BOJ] 2607_비슷한 단어 / 실버2 / 60분 / X

---

week11/BOJ_9081/단어맞추기_한의정.java

- 백준 9081 - [단어 맞추기](https://www.acmicpc.net/problem/9081)
<br/>
1. 단어 맨 뒤에서부터 처음으로 감소하는 부분의 위치 idx1를 찾는다.
```
int idx1 = -1;
for(int i = len - 1 ; i > 0 ; i--) {
if(ch[i - 1] < ch[i]) {
idx1 = i - 1;
break;
}
}
```
2. 다시 단어 맨 뒤에서부터 감소하는 부분보다 처음으로 큰 부분 idx2를 찾는다.
```
int idx2 = 0 ;
for(int i = len - 1 ; i >= 0 ; i--) {
if(ch[idx1] < ch[i]) {
idx2 = i;
break;
}
}
```
3. idx1과 idx2 위치의 값을 swap한다.
4. idx1의 뒷 부분을 오름차순으로 정렬한다.
<br/>
저번에 푼 문제라 뭔가 풀이가 떠오를듯 말듯 하였는데..
결국 풀이를 생각해내지 못 해서 지난 번에 푼 방법을 보고 제출했다,,,
<br/>
X

[BOJ] 9081_단어 맞추기 / 실버1 / 30분 / X

---

week11/BOJ_16935/배열돌리기3_한의정.java

- 백준 16935 - [배열 돌리기 3](https://www.acmicpc.net/problem/16935)
<br/>
**1,2번 연산**
: 행과 열의 크기가 map의 크기와 같은 임시 배열을 선언하고, 임시 배열에 [상하/좌우] 반전시킨 값을 저장한다. 그리고 임시 배열의 값을 원본 배열로 복사해 저장한다.
**3, 4번 연산**
: [열의 크기][행의 크기]를 갖는 2차원 임시 배열을 생성해 [오른쪽/왼쪽]으로 90도 회전시킨 값을 저장하고, 그 배열의 값을 원본 배열로 복사해 저장한다.
**5,6번 연산**
: 행과 열의 크기가 map의 크기와 같은 임시 배열을 선언하고, 원본 배열을 4등분 해 [반시계/시계] 방향으로 회전시킨 값을 임시 배열에 저장한다. 그리고 임시 배열의 값을 원본 배열로 복사해 저장한다.
<br/>
- 처음 제출할 때 3,4번 연산에서 행과 열의 길이가 바뀔 때 처리를 제대로 하지 않아 ArrayIndexOutOf 에러가 떴다,, 
<br/>
X

[BOJ] 16935_배열 돌리기 3 / 골드5 / 60분 / O

---

week11/BOJ_2636/치즈_한의정.java

- 백준 2636 - [치즈](https://www.acmicpc.net/problem/2636)
<br/>
> BFS
- 격자에 치즈가 존재하는 한 반복문을 수행한다.
- 격자에 치즈가 존재한다면, 걸린 시간에 +1하고 BFS로 치즈를 녹인다.
- (0,0)부터 BFS를 수행한다.
- 격자 범위 내에 있고, 방문한 적 없는 치즈가 놓여있지 않은 칸이라면, 방문처리하고 큐에 추가해 마저 탐색한다.
- 격자 범위 내에 있고, 방문한 적 없는 치즈가 놓여있는 칸은 치즈를 녹인다. (= 방문 처리하고 칸의 값을 0으로 변경)
<br/>
X
<br/>
X

[BOJ] 2636_치즈 / 골드4 / 30분 / O

---

week11/PGS_72412/순위검색_한의정.java

- 프로그래머스 - [순위 검색](https://school.programmers.co.kr/learn/courses/30/lessons/72412)
<br/>
> DFS + 이분 탐색
1. info에 있는 값을 띄어쓰기 기준으로 분리하고, 만들 수 있는 모든 경우의 수 만든다. (DFS)
2. 이분탐색 위해 map의 value인 점수 리스트들 오름차순 정렬한다.
3. query의 " and "를 ""로 바꾸고, 띄어쓰기 기준으로 분리한다. 그리고 분리했을 때 0번째 값인 문자열로 map에서 값을 조회해 해당 리스트에 해당하는 값들을 가져와 정답 배열의 원소로 저장한다. (이분 탐색)
<br/>
- DFS로 모든 문자열 조합 만들 생각하는 것을 놓쳤다..
- query를 뭐 기준으로 분리해서 써야할지 고민이 되었다,,
<br/>
다...

[PGS] 순위 검색 / level2 / 60분 / X

---

week11/BOJ_1205/등수구하기_강아현.py

- 백준 1205-등수 구하기
<br/>
- N == P인 경우, 태수의 새로운 점수가 현재 점수들보다 낮은 경우에는 랭킹 리스트에 올라갈 수 없으므로 -1을 출력한다.
- 등수 변수와 점수의 개수 변수를 따로 놓고 등수를 매겼다.
- 같은 점수인 경우에는 등수 변수를 등수로 사용한다.
- 다른 점수인 경우에는 점수의 개수 변수를 등수 변수로 사용한다.
<br/>
x
<br/>
x

[BOJ]1205_등수 구하기 / 실버4 / 50분 / O

---

week11/BOJ_1138/한줄로서기_강아현.py

- 백준 1138-한 줄로 서기
<br/>
- `line` : 출력할 순서를 담은 리스트 <br> `l` : line의 인덱스를 담은 리스트
1. 키가 큰 사람이 왼쪽에 몇 명 있는지 입력받은 리스트의 요소를 l 인덱스로 활용한다.
2. 예를 들어, 1번 사람의 왼쪽에 큰 사람이 2명이라면 1번 사람은 l의 인덱스 2에 해당하는 위치에 서게 된다.
3. 1번 사람은 세우고 나서는 1번 사람이 섰던 위치는 제거하고 다시 리스트를 구성하여 나머지 사람들을 세운다.
4. 1번 사람의 위치가 지워진 리스트 l은 길이가 3인 리스트가 된다. 2번 사람의 왼쪽에 큰 사람이 1명이기 때문에 2번 사람은 l의 인덱스 1에 해당하는 위치에 서게 된다.
5. 위의 과정을 반복할 때 line 리스트에는 l리스트에 들어있는 원래 원소인 line 인덱스에 해당하는 값을 활용한다. 새로 업데이트 되는 l리스트에서의 위치를 반영할 수 있다.
<br/>
x
<br/>
x

[BOJ]1138_한 줄로 서기 / 실버2 / 10분 / O

---

week11/BOJ_9081/단어맞추기_강아현.py

- 백준 9081-단어 맞추기
<br/>
저번에 풀었던 방식이랑 거의 똑같이 풀었음.
> **next_word 함수 구현**
> 
> : 사전순으로 정렬했을 때, 주어진 단어 다음으로 오는 문자를 구하는 함수
>
>> `i = n - 2`
>> - 오른쪽 두 번째 문자부터 시작해서 i+1번째 문자보다 작은 경우의 i를 찾는다.
>
>> `i == -1`
>> - 주어진 단어가 사전순에서 마지막 단어이다.
>
>> `j = n - 1`
>> - i 이후의 문자열에서 i 위치 문자보다 큰 문자를 찾는다.
>
>> `word[i], word[j] = word[j], word[i]`
>> - i 위치와 j 위치의 문자열을 바꿔서 사전순으로 가장 큰 문자로 바꾼다.
>
>> `word[i+1:] = reversed(word[i+1:])`
>> - i 이후의 문자열을 뒤집어서 사전순으로 가장 작은 문자로 바꾼다.
<br/>
x
<br/>
x

[BOJ]9081_단어 맞추기 / 골드5 / 20분 / O

---

week11/BOJ_16935/배열돌리기3_강아현.py

- 백준 16935-배열 돌리기 3
<br/>
> 문제에 주어진 1 ~ 6번 연산을 그대로 구현했다.
- 2, 3번 연산에서는 list[::-1]을 통해 리스트를 뒤집는 방법을 사용했다.
- 5, 6번 연산에서는 1~4 그룹을 각각 구해서 이를 회전했을 때 나올 위치에 맞춰 리스트를 더해서 구했다.
<br/>
x
<br/>
x

[BOJ]16935_배열 돌리기 3 / 골드5 / 50분 / O

---

week11/BOJ_2607/비슷한단어_강아현.py

- 백준 2607-비슷한 단어
<br/>
- `t` : 처음 단어 이후의 단어들 <br> `k` : 처음 나오는 단어
1. 입력받은 단어들의 인덱스 1번부터 단어들을 순차적으로 확인한다.
2. 단어를 이루는 문자가 처음 나오는 단어에 있다면 t, k 리스트에서 해당 문자를 제거한다.
3. k의 원소가 1개이하인 경우 + t의 원소가 1개이하인 경우 :<br> 두 개의 단어가 같은 구성을 갖거나 비슷한 단어의 조건에 부합한다.
<br/>
x
<br/>
x

[BOJ]2607_비슷한 단어 / 실버2 / 30분 / O

---

week11/BOJ_2636/치즈_강아현.py

- 백준 2636-치즈
<br/>
> **bfs**
> - 상하좌우 탐색을 통해 한번 돌면 제일 바깥에 있는 치즈는 사라진다.
> - 치즈가 모두 사라질 때까지 bfs를 반복한다.
> - 없어지는 치즈의 개수를 bfs를 돌면서 기록해둔다.
> - 모두 녹기 전 치즈조각의 개수는 `cheeses`의 마지막  원소가 된다.
<br/>
bfs를 활용해야겠다는 생각을 하기까지 좀 고민을 했다.
<br/>
x

[BOJ]2636_치즈 / 골드4 / 50분 / O

---

week11/PGS_72412/순위검색_강아현.py

- 프로그래머스 - 순위 검색
<br/>
- `info_dict` <br> : 지원자 정보를 가지고 나올 수 있는 가능한 모든 조건의 조합을 저장하는 딕셔너리<br> - `key` : 조건 조합 <br> - `value` : 해당 조건 조합에 대한 점수 리스트
- `info_dict`를 조건 조합에 대한 점수 리스트를 오름차순으로 정렬
- `query`에 조건이 `info_dict`에 존재하면 점수 리스트를 이진 탐색을 통해 입력된 점수 이상인 값의 개수를 계산한다.
<br/>
효율성 문제를 해결하는데 딕셔너리를 어떻게 활용할 수 있는지 고민했다.
<br/>
x

[PGS]순위 검색 / level2 / 20분 / O

---

week12/BOJ_11055/가장큰증가하는부분수열_한의정.java

- 백준 11055 - [가장 큰 증가하는 부분 수열](https://www.acmicpc.net/problem/11055)
<br/>
1. 2개의 1차원 int형 배열 arr와 dp를 만든다. (하나는 입력받은 값 저장용, 다른 하나는 증가하는 **부분 수열의 합** 중 최댓값 저장용)
2. 기준점을 잡은 후, 기준점 이전까지의 수들과 비교하여 자신이 큰 경우만 DP 배열을 갱신한다.
```
for(int i = 1 ; i < N ; i++) {
dp[i] = cost[i];    // 일단 자신의 값을 dp에 저장
for(int j = 0 ; j < i ; j++) {
if(cost[i] > cost[j]) { // 기준값이 더 큰 경우 갱신
dp[i] = Math.max(dp[i], dp[j] + cost[i]);    // dp배열에 저장되는 값 : 부분 수열의 합
}
}
}
```
3. dp배열을 오름차순 정렬하고, 맨 뒤에 위치한 최댓값을 출력한다.
<br/>
X
<br/>
X

[BOJ] 11055_가장 큰 증가하는 부분 수열 / 실버2 / 25분 / O

---

week12/BOJ_1890/점프_한의정.java

- 백준 1890 - [점프](https://www.acmicpc.net/problem/1890)
<br/>
> DP
1. 2차원 int형 배열 board에 격자의 값을 저장한다.
2. 2차원 long형 배열 dp의 맨 왼쪽 위 값 (= 좌표 위치 (0,0))에 1을 넣는다.
> dp[i][j] : (i,j) 위치에 올 수 있는 경우의 수
3. 오른쪽 아래 있는 끝점이 아닌 격자의 모든 점에서 각 칸에 있는 값 board[i][j] 만큼 아래쪽이나 오른쪽으로 이동할 수 있다면, dp 배열을 채운다.
```
for(int i = 0 ; i < N ; i++) {
for(int j = 0 ; j < N ; j++) {
// 오른쪽 아래 있는 끝점이면 종료
if(i == N-1 && j == N-1)    continue;
int val = board[i][j];
// 오른쪽으로 이동
if(j + val < N)
dp[i][j + val] += dp[i][j];
// 아래쪽으로 이동
if(i + val < N)
dp[i + val][j] += dp[i][j];
}
}
```
4. 맨 오른쪽 아래 있는 점 dp[N-1][N-1]을 출력한다.
<br/>
- 점화식 찾기...
- dp 배열 long형으로 선언하기
<br/>
X

[BOJ] 1890_점프 / 실버1 / 50분 / X

---

week12/BOJ_9655/돌게임_강아현.py

- 백준 9655-돌 게임
<br/>
턴을 번갈아가면서 돌을 1개 또는 3개씩 가져가면 결과적으로 처음 돌의 개수가 홀수면 상근이가 이기고 짝수면 창영이가 이기게 된다.
<br/>
x
<br/>
x

[BOJ]9655_돌 게임 / 실버5 / 5분 / O

---

week12/BOJ_11055/가장큰증가하는부분수열_강아현.py

- 백준 11055-가장 큰 증가하는 부분 수열
<br/>
> **Dynamic Programming**
>
> - 인덱스 1부터 n-1까지 반복하면서 각 원소 `nums[i]`에 대해 이전 원소들과 비교한다.
> - 현재 원소 `nums[i]`가 이전 원소 `nums[j]`보다 큰 경우, `dp[i]`를 `dp[j]+nums[i]`와 비교하여 더 큰 값을 선택한다.
> - 위의 경우에 해당되지 않는다면 `dp[i]`를 `nums[i]`로 업데이트한다.
<br/>
x
<br/>
x

[BOJ]11055_가장 큰 증가하는 부분 수열 / 실버2 / 60분 / O

---

week12/BOJ_1890/점프_강아현.py

- 백준 1890 - 점프
<br/>
> **Dynamic Programming**
>
> - 격자판을 순회하면서 현재 위치에서 이동할 수 있는 만큼의 거리로 이동할 수 있는 경우, 도달 가능한 칸의 경로 수를 업데이트한다.
> - 여러 경로로 이동하는 것을 구하기 때문에 k == 0인 경우 break를 해버리면 다른 경로에서 도착점까지 도달하지 못해 이 값을 업데이트하지 못한다.<br> **따라서 continue로 처리한다.**
<br/>
x
<br/>
x

[BOJ]1890_점프 / 실버1 / 50분 / O

---

week12/BOJ_9251/LCS_강아현.py

- 백준 9251 - LCS
<br/>
> **Dynamic Programming**
> 
> **X[i] == Y[i]**
> - LCS(Xi, Yj) = LCS(Xi - 1, Yj - 1) + 1
> - 각 문자열에 X[i], Y[i]가 추가되기 이전의 LCS의 길이(=LCS(Xi - 1, Yj - 1))에 1만큼 더해주면 된다.
>
> **X[i] != Y[i]**
> - LCS(Xi, Yj) = LCS(Xi - 1, Yj - 1)
> - LCS(Xi, Yj) = max(LCS(Xi - 1, Yj), LCS(Xi, Yj - 1))
> - 각 문자열의 마지막 글자들이 따로 한 글자씩 추가되었을 때의 LCS(Xi - 1, Yj), LCS(Xi, Yj - 1) 중 큰 값을 가져와야 한다.
<br/>
이 문제는 복습을 여러번 해봐야 할 것 같다.
<br/>
이 문제 풀이 방식

[BOJ]9251_LCS / 골드5 / 60분 / X

---

week12/BOJ_18427/함께블록쌓기_강아현.py

- 백준 18427 - 함께 블록 쌓기
<br/>
> **Dynamic Programming**
>
> - 각 높이별로 가능한 경우의 수를 저장하기 위해 2차원 dp테이블을 사용한다.
> - `dp[i][j]` : i번째 줄까지 사용해서 높이 j를 만들 수 있는 경우의 수를 나타낸다.
> - 각 높이별 경우의 수를 계산하고 `dp[n][h]`가 정답값이 된다.
<br/>
- 처음에 product를 사용하니 시간 초과 문제가 계속 발생했다.
- dp를 어떻게 이용할지 고민하면서 시간을 많이 소요했다.
<br/>
x

[BOJ]18427_함께 블록 쌓기 / 골드4 / 50분 / O

---

week12/PGS_72411/메뉴리뉴얼_강아현.py

- 프로그래머스 - 메뉴 리뉴얼
<br/>
> 시간 복잡도 : `O(N^2)`
> **Combinations**
>
> - 손님이 주문한 단품메뉴 조합에서 개수별 코스 요리 조합을 구한다.
> - 코스 요리 조합을 딕셔너리로 저장한 후, 딕셔너리의 value값이 가장 크고 이 값이 2이상인 경우 해당 코스 요리를 정답값에 추가한다.
<br/>
x
<br/>
x

[PGS]메뉴 리뉴얼 / level2 / 20분 / O

---

week12/BOJ_18427/함께블록쌓기_한의정.java

- 백준 18427 - [함께 블록 쌓기](https://www.acmicpc.net/problem/18427)
<br/>
> DP
> ⇒ dp[i][j] : 1~i번 학생이 높이가 j인 탑을 만드는 경우의 수
**`dp[i][j] = dp[i-1][j]  + dp[i][j - list[i].get(k)]`**
→ `dp[i-1][j]` : i번째 학생이 블럭 사용X인 경우
→ `dp[i][j - list[i].get(k)]` : i번째 학생이 k번째 블럭 사용O인 경우
<br/>
- 점화식 생각하기... 이런 규칙은 어떻게 찾는 것인가,,,! 그림을 그려봐도 모르겠던데....ㅋㅋㅋ
<br/>
X

[BOJ] 18427_함께 블록 쌓기 / 골드4 / 40분 / X

---

week13/BOJ_1063/킹_한의정.java

- 백준 1063 - [킹](https://www.acmicpc.net/problem/1063)
<br/>
- 킹 위치와 돌 위치를 저장해둔다.
- 만약 킹을 원하는 방향으로 이동시키려고 할 때 격자 범위를 벗어난다면, 이동하지 못 하게 한다.
- 만약 킹이 이동하려는 방향에 돌이 있으면, 이 돌도 킹의 이동 방향으로 한 칸 이동시킬 수 있는지 확인한다.
- 돌을 이동시킬 수 없으면 킹도 이동시킬 수 없다.
- 돌을 이동시킬 수 있으면, 킹과 같은 방향으로 한 칸 이동시킨 후, 킹도 마저 한 칸 이동시킨다.
- 돌을 이동시킬 수 없으면, 킹도 이동시킬 수 없다는 사실을 간과했다.
<br/>
X

[BOJ] 1063_킹 / 실버3 / 60분 / O

---

week13/BOJ_1158/요세푸스문제_강아현.py

- 백준 1158 - 요세푸스 문제
<br/>
> **if len(people) >= k** 인 경우, 제거될 idx는 k-1
> 
> **else**, 제거될 idx는 (k-1) % len(people)
>
> - people은 제거되는 idx를 기준으로 `idx + 1 이후 리스트` + `idx 이전 리스트`로 업데이트된다.
<br/>
x
<br/>
x

[BOJ]1158_요세푸스 문제 / 실버4 / 25분 / O

---

week13/BOJ_1063/킹_강아현.py

- 백준 1063 - 킹
<br/>
>
> `board` : 체스판
> - `chr(int)`로 아스키코드 문자 활용
>
> `king_stone` : 킹과 돌의 위치 표시
> 
> `king` : 킹의 현재 위치 / `stone` : 돌의 현재 위치
>
> `directions` : order에 따른 이동 변수 딕셔너리
<br>
> **Function**
>
> `move(x,y,order)`
>
> 킹의 이동이 체스판 내에서 이루어지는 경우
> - 이동하는 곳에 돌이 없는 경우, 그대로 이동한다.
> - 이동하는 곳에 돌이 있는 경우, 돌을 밀어내야한다.
>   - 돌이 체스판 밖으로 나가지 않은 경우에만 밀어낸다.
>   - 돌이 체스판 밖으로 나가게 되면 킹도 이동하지 않는다.
<br/>
x
<br/>
x

[BOJ]1063_킹 / 실버3 / 25분 / O

---

week13/BOJ_21610/마법사상어와비바라기_강아현.py

- 백준 21610 - 마법사 상어와 비바라기
<br/>
> 유사 문제 : **[나무 타이쿤](https://www.codetree.ai/training-field/frequent-problems/company/samsung/problems?page=2&pageSize=20)**
<br>
<br>
> 문제에 나와있는 조건을 꼼꼼히 구현하면 풀 수 있는 문제
<br>
> 
>> `board` : 바구니가 있는 격자판
>>
>> `order` : 이동 명령을 담은 리스트
>> 
>> `directions` : ←, ↖, ↑, ↗, →, ↘, ↓, ↙ 이동 변수를 담은 리스트
>>
>> `cloud` : 현재 구름 위치 / `move_cloud` : 이동 명령 후 구름 위치
>
> **Function**
>
>> `is_valid(x,y)` : x, y가 보드판 내에 있는지 확인
>>
>> `move(x,y,d,s)`
>> - 1번 열과 N번 열 연결 & 1번 행과 N번 행 연결 <br> (x 혹은 y가 1보다 작아지면 N으로 오고 N보다 커지면 1로 오는 것을 의미)
>> - `((x or y) + s * (dx or dy)) % n` 연산으로 위의 조건에 해당되게 좌표를 구할 수 있다.
>>
>> `water_copy(x,y)` : x, y 위치를 기준으로 대각선 바구니에 물이 있으면 board[x][y] 바구니에 해당 칸 수만큼 물을 더해준다.
>
> **Main**
>
> 1. 구름을 이동 명령에 따라 이동시킨다.
> 2. 이동한 곳의 바구니에 물의 양을 + 1
> 3. 이동한 …

[BOJ]21610_마법사 상어와 비바라기 / 골드5 / 40분 / O

---

week13/BOJ_20056/마법사상어와파이어볼_강아현.py

- 백준 20056 - 마법사 상어와 파이어볼
<br/>
> **for문**
- k만큼 반복하면서 fireballs의 모든 fireball을 이동시킨다.
- board를 돌면서 길이가 2이상인 경우와 1인 경우로 나눠서 구한다.
> **길이가 2이상인 경우**
- 무게의 합, 속력의 합, 홀수, 짝수, 개수 변수 생성
- 해당 위치의 모든 fireball을 처리한다.
- 홀수 or 짝수 합 == 전체 길이인 경우, [0,2,4,8]로 direction을 추가함.
- 위의 경우가 아닌 경우, [1,3,5,7]로 direction을 추가함.
- 질량의 합 // 5  == 0이면 소멸, > 0이면 위의 direction에 따라 방향 변수를 추가한다.
> **길이가 1인 경우**
- fireballs에 그냥 추가한다. 
<br/>
조건을 고려해야하는 변수들을 어떻게 처리할 지에 대한 고민이 되었다.
<br/>
x

[BOJ]20056_마법사 상어와 파이어볼 / 골드4 / 40분 / X

---

week13/BOJ_21611/마법사상어와블리자드_강아현.py

- 백준 21611 - 마법사 상어와 블리자드
<br/>
>
>> `shark` : 상어의 위치이며 항상 보드판의 가운데
>>
>> `directions` : 명령에 해당하는 4가지 방향 이동 변수를 담은 리스트
>>
>> `move_directions` : 상어의 위치로부터 보드를 반시계 방향을로 탐색하기 위한 이동 변수를 담은 리스트
>>
>> `marbles` : 폭발한 구슬의 개수를 세기 위한 리스트
> **Function**
>
>> `destroy(d,s)` : 구슬 파괴
>>
>> `check_four(l,marbles)` : 구슬 폭발
>> - 같은 구슬이 연속해서 4개 이상인 경우 해당 구슬을 모두 0으로 바꾼다.
>> - ❗️주의❗️ 원래 리스트의 마지막 원소인 경우에도 구슬의 개수가 4이상이면 처리해줘야한다.
>> - 0이 아닌 원소들만 리스트에 담아 리턴한다.
>>
>> `add_marble(l)` : 하나의 그룹을 두 개의 구슬 A와 B로 나눈 후 처리한다.
>> - check_four 함수처럼 구슬 번호에 따른 개수를 구해서 처리한다.
>> - 이 함수에서도 원래 리스트의 마지막 원소인 경우도 항상 고려해서 처리해야한다.
>>
>> `move(board,marbles)` : 구슬 파괴 이후의 모든 과정을 처리하는 함수
>> 1. while 문으로 상어 위치부터 (0,0)까지 반시계방향으로 돌면서 2차원 보드판을 1차원 리스트로 가져온다.
>> 2. 더이상 4개 이상이 모여있는 구슬이 없을 때까지 check_four 함수를 반복하면서 1의 리스트를 …

[BOJ]21611_마법사 상어와 블리자드 / 골드1 / 120분 / O

---

week13/BOJ_21610/마법사상어와비바라기_한의정.java

- 백준 21610 - [마법사 상어와 비바라기](https://www.acmicpc.net/problem/21610)
<br/>
문제에서 말한 순서대로 구현한다.
M번 동안 아래 과정을 반복한다.
1. [1-2단계] 구름을 d 방향으로 s칸 이동시키고, 구름인 적 있다고 표시한다. (나중에 해당 위치에 구름이 또 생기지 않게 하고자) 그리고 각 구름에서 비를 내리게 한다.
```
c[0] = (N + c[0] + dx[d] * (s % N)) % N;
c[1] = (N + c[1] + dy[d] * (s % N)) % N;
visited[c[0]][c[1]] = true;  // 구름인 적 있었다고 표시
A[c[0]][c[1]]++;  // 2. 비 내리기
```
2. [3-4단계] 구름이 모두 사라질 때까지 물복사버그 마법을 진행한다. → `**큐**`를 사용해 구름 없애기
3. [5단계] 구름이었던 적 없고, 저장된 물의 양이 2 이상인 칸에 대해 새 구름 위치로 추가하고, 물의 양 2를 뺀다.
4. 마지막에 모든 배열의 합을 구해 출력한다.
<br/>
격자의 행과 열이 각각 연결되어있어 인덱스 처리하는 부분에서 헷갈렸다.
<br/>
X

[BOJ] 21610_마법사 상어와 비바라기 / 골드5 / 120분 / X

---

week13/BOJ_20056/마법사상어와파이어볼_한의정.java

- 백준 20056 - [마법사 상어와 파이어볼](https://www.acmicpc.net/problem/20056)
<br/>
> 필요 자료구조
>→ 파이어볼 객체 : 행,열,질량,속도,방향 저장
>→ 파이어볼 이동 시 정보를 저장할 **_"2차원 ArrayList 배열"_** : `List<Fireball>[][] map`
>→ 모든 파이어볼 정보를 저장할 ArrayList : `ArrayList<Fireball> list`
1. M번 간 리스트에 파이어볼 객체 정보를 저장한다.
2. K번 동안 파이어볼을 이동시키고, 분열시킨다.
2- 1) 파이어볼 이동 후, 이동한 위치의 2차원 리스트 배열 칸에 해당 객체를 저장한다.
2-2) 완전탐색을 통해 모든 리스트 배열 칸에 대해 파이어볼 갯수가 2개 미만인 경우, 해당 칸을 비운다. 하지만, 2개 이상인 경우 분열을 진행한다.
- 해당 칸에 있는 파이어볼 객체들을 반복문을 통해 탐색하며 객체들의 질량 합과 속도 합, 홀수 방향 갯수, 짝수 방향 갯수를 구하고, 파이어볼 리스트에서 분열된 해당 파이어볼 객체를 제거한다.
- 해당 칸도 비운다.
- 질량의 합/5한 값이 0이라면, 소멸되어 없어지고, 그게 아니면 분열된 질량이다.
- 속도의 합을 아까 해당 칸에 있는 파이어볼 수로 나눠 구한다.
- 만약 모든 파이어볼 방향이 짝수거나 홀수인 경우, 0,2,4,6 방향으로 분열한다. 그게 아니라면, 1,3,5,7 방향으로 분열한다.
<br/>
- 2차원 배열 칸에 여러 값을 어떻게 저장해야 할지 고민되었다.
- 파이어볼을 이동시킬 때 격자의 끝끼리 연결되도록 …

[BOJ] 20056_마법사 상어와 파이어볼 / 골드4 / 60분 / X

---

week13/BOJ_21611/마법사상어와블리자드_한의정.java

- 백준 21611 - [마법사 상어와 블리자드](https://www.acmicpc.net/problem/21611)
<br/>
1. d 방향으로 s만큼의 구슬을 제거한다.
2. 사라진 구슬들이 있으니 구슬들을 이동시킨다.
3. 4개 이상 이어지는 구슬이 있나 확인한다. 존재한다면, 구슬들을 제거하면서 sum에 더한다.
4. 구슬들이 사라지며 생긴 빈 공간을 메꾼다. 4개 이상 이어지는 구슬이 없을 때까지 3-4과정을 반복한다.
5. 연속되는 번호의 구슬, 개수에 따라 판을 재배치한다.
<br/>
- dx,dy 배열이 2개 필요한 것..
- 구현할 내용이 많은 것..
- 코드가 너무나도 길어져버린 것...
- 뇌가 돌아가지 않은 것...
<br/>
X

[BOJ] 21611_마법사 상어와 블리자드 / 골드1 / 120분 / X

---

week13/PGS_258711/도넛과막대그래프_한의정.java

- 프로그래머스 258711 - [도넛과 막대 그래프](https://school.programmers.co.kr/learn/courses/30/lessons/258711)
<br/>
> 구현 (배열 - 진입/진출 수 저장)
1. 엣지 배열을 돌며 진입 정점 수와 진출 정점 수를 저장하며, 해당 정점 중 가장 큰 값을 최대 탐색 범위로 지정한다.
2. 1에서 구한 최대 탐색 범위까지 아래 과정을 반복하며 생성된 정점 번호, 막대 모양 그래프 수, 8자 모양 그래프 수, 도넛 모양 그래프 수를 구한다.
- 생성된 정점 : 진입 간선이 없고, 진출하는 간선이 2개 이상인 경우
- 막대 모양 그래프 : 최상위 노드에서 다른 노드로 향하는 간선이 없는 경우
- 8자 모양 그래프 : 진입 간선이 2개 이상, 진출 간선이 2개 이상인 경우
- 도넛 모양 그래프의 수 : 생성된 정점 번호의 진출 간선 수에서 막대 모양 그래프 수와 8자 모양 그래프 수를 뺀 나머지
<br/>
- 처음에는 사이클 갯수로 문제를 풀어보려고 했었다. (사이클이 2개면 8자, 0개면 막대 ,...)
- 진입 진출 배열 수를 활용할 생각을 하지 못 했다.
<br/>
- 각 모양 별 특징을 파악해서 문제를 단순하게 풀자,,,
- 만약에 사이클 갯수 찾으면서 푼다 하면, 그래도 진입 진출 수 저장할 배열도 필요하고, BFS로 풀면 되더라,,

[PGS] 258711_도넛과 막대 그래프 / level2 / 30분 / X

---

week14/BOJ_14594/동방프로젝트_한의정.java

- 백준 14594 - [동방 프로젝트 (Small)](https://www.acmicpc.net/problem/14594)
<br/>
"**벽**"을 중점으로 문제를 풀었다.
방이 N개면, 벽은 N-1개이므로 **1부터 N-1번**까지의 벽의 상태를 나타내는 boolean형 배열을 만들었다.
- true : 벽 허물음 / false : 벽 안 무너짐
- 예 : O|O|O - 방 3개, 벽 2개
<br>
1. M번 동안 만약 x가 y보다 작다면, **x부터 y-1번 벽**을 허문다. (`walls[i] = true`)
2. 반복문이 끝나면, 1부터 N-1까지 벽을 돌면서 남아있는 벽(`walls[i] == false`)의 수를 구한다.
3. 2에서 구한 벽 수에 1을 더해 출력한다. (방 수 = 벽 수 + 1이므로)
<br/>
X
<br/>
X

[BOJ] 14594_동방 프로젝트 (Small) / 실버4 / 18분 / O

---

week14/BOJ_8911/거북이_한의정.java

- 백준 8911 - [거북이](https://www.acmicpc.net/problem/8911)
<br/>
- 북쪽이 0번 인덱스 위치에 오도록 방향 배열을 만들어 북서남동 순서로 저장했다.
- T번 동안 명령에 맞게 이동한다.
- 시작점 x와 y는 0, 시작 방향도 0(북쪽)으로 지정한다.
- 거북이가 이동한 가장 큰 넓이를 구하기 위해 각 명령을 수행할 때마다 가장 왼쪽 아래 있을 때의 행과 열의 위치(minX, minY), 가장 오른쪽 위에 있을 때의 행과 열의 위치(maxX, maxY)를 갱신하여 구한다.
- (maxX - minX) * (maxY - minY) 계산으로 넓이를 구해 출력한다.
<br/>
- 리스트에 거북이가 이동한 모든 점을 저장해서 그 중 가장 왼쪽 위에 있는 값과, 오른쪽 아래 있는 값을 구하려고 했다 (욕심이었다)
<br/>
- 최대/최소 행/열 인덱스 가져오는 아이디어

[BOJ] 8911_거북이 / 실버3 / 40분 / X

---

week14/BOJ_5212/지구온난화_한의정.java

- 백준 5212 - [지구 온난화](https://www.acmicpc.net/problem/5212)
<br/>
1. 2차원 격자 배열에 값을 저장한다. 이 때, 땅(X)인 칸의 위치만 따로 큐에 저장해둔다.
2. 땅의 위치가 저장된 큐를 돌면서 해당 큐가 바다에 잠기는지 확인하고, X가 위치한 최소/최대 행/열 위치를 구한다.
- 인접한 4방향 중 3방향 이상이 바다인 경우, 그 땅은 잠긴다. (. X이 아닌 다른 문자로 바꿈)
- 잠기지 않은 경우, 땅이 위치하는 행과 열의 최소 최대 위치를 구한다.
3. [최소 행, 최대 행] [최소 열, 최대 열] 위치 내에 있는 칸들의 값을 출력한다.
- 땅이거나 바다면, 바로 출력
- 매립된 땅(= . X이 아닌 다른 문자)이면 바다로 출력
<br/>
- 당연히 땅(X)인 애들만 큐에 넣었다고 생각했는데 이 조건을 빠뜨린 것 때문에 시간이 오래 걸렸다,,ㄴㅇㄱ
<br/>
X

[BOJ] 5212_지구 온난화 / 실버2 / 50분 / O

---

week13/PGS_258711/도넛과막대그래프_강아현.py

- 프로그래머스 - 도넛과 막대 그래프
<br/>
그래프 모양별로 노드에 연결된 들어오는 간선과 나가는 간선 수를 파악해서 풀었다.
- 생성된 정점 : 나가는 간선만 있고, 들어오는 간선은 없다.
- 8자 모양 그래프 : 나가는 간선과 들어오는 간선이 각각 2개 이상이다.
- 막대 모양 그래프 : 나가는 간선은 없고, 들어오는 간선이 1개 이상이다.
- 도넛 모양 그래프 : 생성된 정점에 연결된 정점의 개수에서 8자 모양, 막대 모양 그래프의 수를 빼면 계산할 수 있다.
<br/>
x
<br/>
x

[PGS]도넛과 막대 그래프 / level2 / 30분 / O

---

week14/BOJ_14594/동방프로젝트_강아현.py

- 백준 14594 - 동방 프로젝트(Small)
<br/>
> 시간 복잡도 : O(n + m)
- 벽이 뚫린 방의 경우 1로 표시한다.
- 0인 값의 개수가 방의 개수가 된다. (0번 방도 넣어서 계산을 했기 때문에 있기 때문에 -1을 해야한다.)
<br/>
- 너무 복잡하게 생각해서 기존 방의 번호와 벽이 무너진 후 방의 번호를 비교하는 식으로 했었다.
<br/>
x

[BOJ]14594_동방 프로젝트(Small) / 실버4 / 30분 / O

---

week14/BOJ_8911/거북이_강아현.py

- 백준 8911 - 거북이
<br/>
> 시간 복잡도 : O(t)
>
>> `x, y` : 거북이의 현재 위치
>>
>> `sx, sy` : 거북이가 이동한 위치 중 x, y 좌표가 각각 가장 작은 값으로 업데이트
>>
>> `bx, by` : 거북이가 이동한 위치 중 x, y 좌표가 각각 가장 큰 값으로 업데이트
>>
>> `d` : 현재 거북이의 이동 방향
>>
<br>
1. `order == "F"`인 경우, 이동 방향 그대로 한칸 이동한다.
2. `order == "B"`인 경우, 뒤로 한칸 가야하므로 현재 좌표에서 이동 방향(directions[d])에 해당하는 좌표를 각각 빼서 이동한다.
3. `order == "L"`인 경우, 왼쪽으로 90도 회전해야하므로 (d - 1) % 4로 d를 업데이트한다.
4. `order == "R"`인 경우, 오른쪽으로 90도 회전해야하므로 (d + 1) % 4로 d를 업데이트한다.
<br/>
x
<br/>
x

[BOJ]8911_거북이 / 실버3 / 25분 / O

---

week14/BOJ_5212/지구온난화_강아현.py

- 백준 10164 - 격자상의 경로
<br/>
> 시간 복잡도 : O(r * c)
1. 현재 지도를 50년 후 지도에 복사한다.
2. 현재 지도를 기준으로 인접한 세 칸 또는 네 칸에 바다가 있는 섬을 50년 후 지도에서 바다로 바꾼다. <br> 이때, 인접한 칸을 확인할 때 지도를 벗어나는 경우에는 바다로 카운트한다.
3. 섬이 있는 곳의 위치를 확인하면서 sx, sy는 x, y의 최소값으로 업데이트하고 bx, by는 x, y의 최대값으로 업데이트한다.
4. sx, sy, bx, by 내 범위의 지도만 출력한다.
<br/>
입력값과 출력값을 제대로 봐야될 것 같다. 입력값이 공백없는 문자열이었는데 이걸 input().split()으로 나눠서 계속 Index Error가 났다. 문제를 제대로 보고 풀어야겠다.
<br/>
x

[BOJ]5212_지구 온난화 / 실버2 / 40분 / O

---

week14/BOJ_1713/후보추천하기_강아현.py

- 백준 1713 - 후보 추천하기
<br/>
> 시간 복잡도 : O(m * n)
>
>> `n` : 사진틀의 개수
>>
>> `m` : 전체 학생의 총 추천 횟수
>>
>> `recommends` : 추천받은 학생들 리스트
>>
>> `candidates` : 추천받은 학생들의 추천 횟수를 담은 딕셔너리
>>
>> `pictures` : 현재 사진틀 상태(학생들이 추천받을 때마다 업데이트 된다.)
>>
<br>
1. 추천받은 학생들의 추천 횟수를 candidates에 업데이트한다.
2. 사진틀에 학생의 사진이 없는 경우, 아래 과정을 통해 사진틀을 업데이트한다.
3. 비어있는 사진틀이 있는 경우에는 사진틀에 추천 받은 학생을 추가한다.
4. 비어있는 사진틀이 없는 경우에는 추천 받은 횟수가 가장 적으면서 오래된 사진을 추천 받은 학생으로 바꾼다.
5. 초기 추천 횟수를 추천 최댓값인 1000회로 초기화한 후, 이 값과 비교하며 이 값보다 작은 경우 해당 학생의 추천 횟수로 업데이트한다.
6. 사진이 삭제되는 경우, 기존에 추천받은 횟수는 0으로 초기화한다.
7. 오래된 사진을 제거한 후, 새로운 학생을 사진틀에 추가한다.
8. 사진틀을 오름차순으로 정렬한 후, print한다.
<br/>
x
<br/>
x

[BOJ]1713_후보 추천하기 / 실버1 / 25분 / O

---

week14/BOJ_21609/상어중학교_강아현.py

- 백준 21609 - 상어 중학교
<br/>
> **Function**
>
>> `bfs(x,y,color)` : 블록 개수 및 좌표 리턴하는 함수
>>
>> `remove(block)` : 블록 제거 함수
>>
>> `gravity(board)` : 보드에서 아래 행이 비어있거나 -1이 아닌 경우 위의 숫자를 밑으로 내린다. 중력 작용 함수
>>
>> `rotate(board)` : 반시계 회전 함수
- 블록 그룹을 만들 수 있는 블록들의 일반 블록 개수, 무지개 블록 개수, 블록 좌표를 리스트로 리턴한다.
- 위 리스트를 내림차순으로 정렬하여 블록 수가 많은 그룹, 그 중 무지개 블록이 많은 그룹을 구할 수 있게 된다.
<br/>
조건에 다 맞게 구현을 했다고 생각했는데 블록 그룹을 만드는 함수를 잘못 구현해서 계속 틀렸던 것 같다.
<br/>
x

[BOJ]21609_상어 중학교 / 골드2 / 120분 / X

---

week14/PGS_67257/수식최대화_강아현.py

- 프로그래머스 - 수식 최대화
<br/>
> 시간 복잡도 : O(n * k!)
> **Parameters**
>
>> `expressions` : expression 내 숫자들만 가져온 리스트
>>
>> `operators` : expression 내 연산자만 가져온 리스트
>> - operators는 expression 리스트보다 항상 길이가 1만큼 짧다.
>>
>> `operator_set` : expression 내 연산자의 종류
1. 입력받은 expression에서 숫자와 연산자를 분리한다.
2. expression 내 연산자의 종류에 따라 permutations로 연산자 우선순위 조합을 구한다.
3. 2에서 구한 연산자 우선순위대로 계산을 하여 절댓값이 가장 큰 경우를 반환한다.
4. 3에서 연산을 할 때, operators 리스트 내 연산자의 인덱스 값을 이용해서 expressions 리스트 내 숫자 값을 업데이트하는 식으로 계산한다. <br> 연산자 인덱스가 0인 경우, 숫자 인덱스 0인 값과 1인 값의 연산 결과를 얻게 된다. 결과적으로 expressions에는 하나의 숫자만 남게 된다.
<br/>
x
<br/>
x

[PGS]수식 최대화 / level2 / 20분 / O

---

week14/BOJ_1713/후보추천하기_한의정.java

- 백준 1713 - [후보 추천하기](https://www.acmicpc.net/problem/1713)
<br/>
> 시간 복잡도 : O(M*N)
사용 자료구조
- 사진 객체 (순서, 학생 번호, 추천 수)
- 사진 객체 저장하는 사진 틀 리스트
- 정답 리스트
1. 학생들이 추천을 시작하기 전에 모든 사진틀 list은 비어있다.
2. 어떤 학생이 특정 학생을 추천하면, 추천받은 학생의 사진이 반드시 사진틀에 게시되어야 한다.
```
if(list.size() < N) {   // 빈 사진틀이 있는 경우
boolean flag = false;   // 게시된 사진인지 판별
for(Info info : list) {
if(info.num == student) { // 4. 현재 사진이 게시된 학생이 다른 학생의 추천을 횟수만 증가
info.cnt++;
flag = true;
break;
}
}
if(!flag) // 2. 사진틀에 없는 추천받은 사진을 사진틀에 게시
list.add(new Info(i, student, 1));
}
```
3. 비어있는 사진틀이 없는 경우
- 현재까지 추천 받은 횟수가 가장 적은 학생의 사진을 삭제하고, 그 자리에 새롭게 추천받은 학생의 사진을 게시한다.
- 이때, 현재까지 추천 받은 횟수가 가장 적은 학생이 두 명 이상일 경우에는 그러한 학생들 중 게시된 지 가장 오래된 사진을 삭제한다.
```
else {
Collections.sort(list); // 사진틀을 추천 수 작은 순으로 정렬
boolean flag = false;   // 게시된 사진인지 판별 …
```

[BOJ] 1713_후보 추천하기 / 실버1 / 60분 / X

---

week14/PGS_67257/수식최대화_한의정.java

- 프로그래머스 level2  [수식 최대화](https://school.programmers.co.kr/learn/courses/30/lessons/67257)
<br/>
> DFS (시간 복잡도 : O(3! * N) = O(N))
1. expression을 연산자와 숫자로 분리해서 각각 연산자 리스트와 숫자 리스트에 해당 값을 저장한다.
```
String tmp = "";    // 숫자
for(char c : expression.toCharArray()) {
if(Character.isDigit(c)) { // 숫자인 경우
tmp += c;
}
else { // 연산자인 경우
numList.add(Long.parseLong(tmp));
tmp = "";
operList.add(c);
}
}
numList.add(Long.parseLong(tmp));	// 마지막 숫자 추가
```
2. dfs(순열)로 연산자 +, -, * 의 우선순위를 만든다.
- 우선순위 1개가 완성될 때마다 해당 우선순위를 적용해 연산한다.
- 원본 숫자 리스트와 연산자 리스트를 복사한다.
- 완전탐색으로 연산자를 순서대로 돌면서, 현재 연산자와 일치한다면, 연산을 진행하고, 현재 위치의 연산자 양 옆의 숫자와 연산자를 삭제한다.
- 반복문이 끝나면, 마지막 남은 숫자 하나와 정답을 비교해 더 큰 값으로 갱신한다.
<br/>
- 분리한 숫자와 연산자를 리스트에 따로 저장해서 활용할 생각은 했는데 이제 해당 연산자를 어떻게 찾아서 연산자 양옆의 숫자를 활용하고, 해당 위치에 값을 넣지?라는 생각을 했다.
```
for(int i = …
```

[PGS] 67257_수식 최대화 / Level2 / 50분 / X

---

week15/BOJ_1012/유기농배추_한의정.java

- 백준 1012 - [유기농 배추](https://www.acmicpc.net/problem/1012)
<br/>
> BFS
1. 배추가 있는 위치를 입력받는다.
2. 방문한 적 없는 배추가 있는 칸(1)에서 bfs를 수행하면서 _총 몇 번 bfs를 해야 하는지_ 횟수를 센다. = _필요한 최소 배추흰지렁이 마리 수_
<br/>
X
<br/>
X

[BOJ] 1012_유기농 배추 / 실버2 / 13분 / O

---

week15/BOJ_14940/쉬운최단거리_한의정.java

- 백준 14940 - [쉬운 최단거리](https://www.acmicpc.net/problem/14940)
<br/>
> BFS
**목표지점 2를 기준**으로 BFS를 수행한다.
`목표지점 ~ 이동 가능한 칸 사이의 거리`는 2차원 int형 거리 배열 `dist`에 저장한다.
<br/>
1. 격자를 입력받는다.
- 목표지점 2인 경우, 해당 위치를 저장해둔다.
- 갈 수 없는 땅 0인 경우, 미리 방문 처리를 해둔다. (방문해서 거리 계산하지 못 하게)
2. 목표지점 2의 위치에서 BFS를 수행한다.
- 방문한 적 없고, 갈 수 있는 칸1에 대해 방문하러 이동한다.
- `dist[nx][ny]`(목적지점-다음 칸의 거리) 는 `dist[now[0]][now[1]]`(목적지점-현재 칸의 거리) 에 `1`을 더해 구한다.
3. 거리 배열 dist를 출력한다.
- 방문한 적 없는 칸은 갈 수 없는 칸이므로 `-1`로 출력한다.
- 그 외 나머지 칸은 거리 배열의 값 그대로 출력
<br/>
- 모든 1인 지점에 대해 목표 지점 2까지 가는 길을 매번 찾으려고 했었다...ㄴㅇㄱ
<br/>
- 목표 지점 기준으로 한 방에 bfs 하고 끝내는 아이디어

[BOJ] 14940_쉬운 최단거리 / 실버1 / 40분 / X

---

week15/BOJ_16918/봄버맨_한의정.java

- 백준 16918 - [봄버맨](https://www.acmicpc.net/problem/16918)
<br/>
> BFS
1. 격자를 입력받으면서 O인 경우 폭탄 터질 시간 timeArr에 `폭탄 터질 시간 3`을 저장한다.
2. 1초에는 변화없음, 2초에는 폭탄 설치, 3초에는 폭탄 터짐, 4초에는 폭탄 설치, 5초에는 폭탄 터짐,.. 의 반복이니까 2~N초까지 짝수 초면 `폭탄을 설치`하고, 홀수 초면 `폭탄을 터트린다`.
- 폭탄 설치 메소드 : 완전탐색으로 비어있는(.) 모든 칸에 폭탄(O)을 설치하고, 폭탄 터질 시간을 저장한다. 
```
for(int i = 0 ; i < R ; i++) {
for(int j = 0 ; j < C ; j++) {
if(board[i][j] == '.') {    // 비어있는 모든 칸에 폭탄 설치
board[i][j] = 'O';
timeArr[i][j] = time +3;    // 폭탄 터질 시간 저장 (= 현재 시간+3)
}
}
}
```
- 폭탄 터지는 메소드 : 완전탐색으로 시간이 다 된 폭탄(`timeArr[i][j] == time`)을 터트린다. 그리고 인접한 4방향의 폭탄도 터트린다. 단, 현재 시간에 터지지 않는 폭탄만 터트린다.
for(int j = 0 ; j < C ; j++) {
if(timeArr[i][j] == time) { // 시간이 다 된 폭탄 터트리기
board[i][j] = '.';
for(int d = 0 ; d < 4 ; d++) {  // 인접한 4방향 터트리기
int nx = i + dx[d];
int ny = j + …

[BOJ] 16918_봄버맨 / 실버1 / 60분 / X

---

week15/BOJ_2667/단지번호붙이기_한의정.java

- 백준 2667 - [단지번호붙이기](https://www.acmicpc.net/problem/2667)
<br/>
> BFS
1. 지도를 입력받는다.
2. 완전탐색으로 모든 집을 확인한다. 방문한 적 없는 집(`!visited[i][j] && map[i][j] == 1`)에 대해 단지수를 계산한다. (BFS)
- 해당 지점에서 방문하지 않은 집을 마저 탐색하며 단지수를 세고, 이 값을 단지수 리스트에 저장한다.
3. 총 단지수(=우선순위 큐 크기)를 출력한다.
4. 각 단지내 집 수 오름차순으로 하나씩 출력한다. = 오름차순으로 정렬된 우선순위 큐의 값을 하나씩 출력한다.
<br/>
X
<br/>
X

[BOJ] 2667_단지번호붙이기  / 실버1 / 15분 / O

---

week15/BOJ_14502/연구소_한의정.java

- 백준 14502 - 연구소
<br/>
> DFS + BFS + 완전탐색
(나중에 완전탐색으로 위치 안 찾으려고)
<br/>
1) 임시 배열에 원본 배열의 값을 복사해 두고, 1에서 선택된 칸에 벽을 세운다. 
2) 1에서 구한 바이러스 위치를 반복문으로 돌면서, 방문하지 않은 바이러스 칸에 대해 탐색 대상 큐에 추가한다.
3) BFS로 바이러스를 퍼뜨린다.
- 인접한 4방향을 탐색하며 1) 격자 범위 내에 있고, 2) 방문한 적 없고, 3) 빈 칸인 경우, 바이러스를 퍼뜨리고 마저 탐색한다.
4)  임시배열을 완전탐색하며 안전영역 수를 구하고, 이를 최댓값과 비교해 더 큰 값으로 갱신한다.
<br/>
X
<br/>
- 2차원 배열의 값을 복사할 때는 clone()을 쓰면 복사가 안 된다.

[BOJ] 14502_연구소 / 골드4 / 70분 / O

---

week15/BOJ_2206/벽부수고이동하기_한의정.java

- 백준 2206 - [벽 부수고 이동하기 ](https://www.acmicpc.net/problem/2206)
<br/>
> BFS
> : boolean형 방문 표시 배열을 3차원으로 만들어 사용한다. (충돌 여부, 행, 열 값 저장)
N과 M이 2 이상일 때 (0,0)부터 BFS 탐색을 시작한다. (큐에 저장할 값: 행, 열, 충돌 여부 - 1일 때 충돌)
인접한 4방향 좌표를 탐색하며 해당 좌표를 아래의 경우로 나눠 확인한다.
1. 해당 좌표가 부서진 적 없고, 방문한 적 없는 벽인 경우
2. 해당 좌표가 방문한 적 없는 벽이 아닌 경우
3. 해당 좌표가 도착 지점인 경우
<br/>
_벽이 부서진 걸 어떻게 나타내지..? 어느 벽이 언제 부서졌는지 어떻게 나타내지?_ 의 문제 ⇒ 3차원 방문 표시 배열을 사용해 방문 여부를 확인하고, 다음 탐색 대상 큐에도 방문 여부를 나타내는 변수를 넣어 벽이 부서졌는지 확인 가능
<br/>
3차원 배열을 사용해 벽이 부서졌는지 여부를 확인할 수 있다는 것

[BOJ] 2206_벽 부수고 이동하기 / 골드3 / 40분 / X

---

week16/BOJ_14716/현수막_한의정.java

- 백준 14716 - [현수막](https://www.acmicpc.net/problem/14716)
<br/>
> BFS
1. 격자 내 모든 점을 입력받는다.
2. 격자 내 모든 점을 탐색하면서, 방문한 적 없는 글자인 부분에서 BFS 탐색하며 BFS 수행 횟수를 구한다.
- 8방향(상하좌우+대각선 4방향) 탐색하며 방문한 적 없는 글자인 부분을 같은 글자로 인식해 이동한다.
<br/>
X
<br/>
X

[BOJ] 14716_현수막 / 실버1 / 6분 / O

---

week16/BOJ_17836/공주님을구해라_한의정.java

- 백준 17836 - [공주님을 구해라!](https://www.acmicpc.net/problem/17836)
<br/>
> BFS
(0,0)에서부터 (N-1,M-1)까지 BFS를 수행한다.
큐에는 (행, 열, **그람 유무**, 이동에 걸린 시간) 총 4가지 값을 저장해 활용한다.
1. 만약 현재 칸까지 이동하는 데 걸린 시간이 t보다 크다면, while문을 탈출하고 Fail을 출력하도록 한다.
2. 만약 현재 칸의 위치가 도착 지점이라면, 현재 칸까지 이동하는 데 걸린 시간의 값을 출력한다.
3. 1,2의 경우가 아니라면, 현재 칸에서 4방향 탐색을 통해 이동한다. 이 때 **그람의 존재 여부**를 기준으로 조건문을 나눈다!
- 그람이 없는 경우
- `방문한 적 없는 빈 공간(0)인 경우` → 해당 칸을 방문 처리하고, 다음 칸으로 이동할 때 큐에 이동 시간+1한 값을 저장한다.
- `방문한 적 없는 그람(2)인 경우` → 해당 칸을 방문 처리하고, 다음 칸으로 이동할 때 큐에 이동시간도 1 더하고, **그람 존재 여부를 나타내는 변수에도 1을 더해 그람 존재 여부도 나타낸다**.
- 그람이 있는 경우
- 이제 칸의 숫자를 신경쓰지 않아도 된다. 방문한 적 없는 칸에 대해서만 방문 처리하고, 이동 시간+1한 값을 큐에 저장해 이동한다.
<br/>
- 3차원 방문 배열 사용해서 그람 존재 여부도 함께 판단할 생각은 했는데 조건문을 제대로 나누지 않아 틀렸다.
- 처음에 (0,0)부터 검의 위치까지의 최단 거리 + 검의 위치부터공주까지의 최단 거리 이 두 가지 값을 더한 1번 값과, (0,0)~공주까지의 …

[BOJ] 17836_공주님을 구해라! / 골드5 / 80분 / X

---

week15/BOJ_1012/유기농배추_강아현.py

- 백준 1012 - 유기농 배추
<br/>
> 시간 복잡도 : O(n×m)
> **BFS**
>
> - bfs 탐색으로 인접해있는 배추들을 묶는다.
> - 이중for문으로 board값이 1일 때 bfs 함수를 실행하게 해서 bfs 함수에서 board값을 0으로 처리하는 코드를 넣었다.
> - 이중for문에서 board[i][j] == 1 and not visited[i][j]로 처리하면 굳이 0을 처리하지 않아도 될 것 같기도 하다.
<br/>
x
<br/>
x

[BOJ] 1012_유기농 배추 / 실버2 / 40분 / O

---

week15/BOJ_14940/쉬운최단거리_강아현.py

- 백준 14940 - 쉬운 최단거리
<br/>
> 시간 복잡도 : O(N*M)
> 갈 수 있는 땅과 갈 수 없는 땅을 잘 구분해서 visited에 기록해주고 목표지점인 2를 만났을 때 bfs를 실행한다.
> 
> 1. visited를 생성하여 방문 여부를 추적한다. '-1'로 초기화되어 있으며, 방문하지 않은 칸은 '-1'로 표시된다. <br> visited는 해당 칸까지의 최단 거리를 담고있다.
> 2. 'BFS' 함수를 호출하여 모든 빈 칸에 대해 최단 거리를 계산한다.
> 3. 이후에는 최단 거리를 출력하되, 미로의 각 칸에 대해 벽이면 0을 출력하고, 빈 칸이면 해당 칸까지의 최단 거리를 출력한다.
<br/>
visited로 각 위치의 최단 거리를 계산할 생각을 하지 못했다.
<br/>
visited 리스트가 꼭 방문 여부만을 확인하는데 사용된다는 생각을 집어 던져야겠다.

[BOJ] 14940_쉬운 최단거리 / 실버1 / 60분 / X

---

week15/BOJ_16918/봄버맨_강아현.py

- 백준 16918 - 봄버맨
<br/>
> **Functions**
>
>> **first_bomb(board)**
>> - 3초 전에 설치된 폭탄이 폭발할 수 있도록 현재 폭탄이 설치된 위치를 2로 초기화한다.
>>
>> **bomb_second(board)**
>> - 현재 위치에 폭탄이 설치되어 있으며 폭탄이 터지기 0초 이상인 경우 이 값에 -1 해준다.
>>
>> **bomb_all(board)**
>> - 1초 동안 폭탄이 설치되어 있지 않은 모든 칸에 폭탄을 설치한다.
>>
>> **bomb(board)**
>> - 3초 전에 설치된 폭탄이 모두 폭발한다.
>> - 상하좌우에 인접한 칸을 모두 빈 칸으로 표시한다.
<br/>
x
<br/>
x

[BOJ] 16918_봄버맨 / 실버1 / 50분 / O

---

week16/BOJ_1726/로봇_한의정.java

- 백준 1726 - [로봇](https://www.acmicpc.net/problem/1726)
<br/>
> 방문 표시 배열에 좌표와 해당 방향의 값을 모두 저장할 수 있도록 **3차원 배열**을 활용하는 것이 포인트!!
1. 격자를 입력받는다.
2. 시작점 위치&방향과 도착점 위치&방향을 입력받는다.
3. 시작점에서부터 BFS를 수행한다.
- 종료 조건 : 도착점 도착 시
- 명령1) Go k : 현재 바라보는 방향으로 1~3칸 이동한다. (대신 중간에 벽 있으면 바로 종료)
```
for(int i = 1 ; i <= 3 ; i++) {
int nr = now.r + dr[now.d]*i;
int nc = now.c + dc[now.d]*i;
if(nr < 0 || nr >= M || nc < 0 || nc >= N)  continue;
// 중간에 벽이 있으면 아예 끝
if(map[nr][nc] == 1) break;
if(!visited[nr][nc][now.d]) {
visited[nr][nc][now.d] = true;
q.add(new Robot(nr, nc, now.d, now.cnt +1));
}
}
```
- 명령2) Turn dir : 현재 방향을 전환한다.
```
int left = 0;   // 왼쪽   90도 회전: 동0 > 북3> 서1> 남2
int right = 0;  // 오른쪽 90도 회전: 동0 > 남2 > 서1> 북3
switch(now.d) {
case 0: left = 3; right = 2; break;
case 1: left = 2; right = 3; …
```

[BOJ] 1726_로봇 / 골드3 / 50분 / X

---

week15/BOJ_2667/단지번호붙이기_강아현.py

- 백준 2667 - 단지번호붙이기
<br/>
> bfs(x,y,cnt)
>
> - board 값이 1인 경우 상하좌우로 인접한 칸을 탐색하면서 단지내 집의 수를 apart 리스트에 추가한다.
> - 총 단지수는 apart의 길이가 된다.
> - apart를 오름차순으로 정렬한 후 한 줄씩 출력한다.
<br/>
x
<br/>
x

[BOJ] 2667_단지번호붙이기 / 실버1 / 10분 / O

---

week15/BOJ_14502/연구소_강아현.py

- 백준 14502 - 연구소
<br/>
> 벽을 먼저 세우고 안전 영역의 크기를 구하여 최대 크기를 구한다.
1. wall(cnt)는 현재까지 세운 벽의 수를 나타내는 `cnt`를 인자로 받는다. `cnt`가 3이 될 때까지 반복하며, 가능한 모든 벽의 조합을 시도한다.
2. 벽을 세운 후에는 `bfs()`로 바이러스가 퍼지는 상황을 시뮬레이션한다. 바이러스의 위치에서 상하좌우로 퍼져나가면서 빈 칸(0)을 바이러스(2)로 바꾼다.
3. 바이러스가 퍼진 후 보드에서 0의 개수를 구한다.
4. 모든 벽의 조합에 대해 3에서 구한 개수의 최대 개수를 구한다.
<br/>
x
<br/>
x

[BOJ] 14502_연구소 / 골드4 / 100분 / O

---

week17/BOJ_1455/뒤집기2_한의정.java

- 백준 1455 - [뒤집기2](https://www.acmicpc.net/problem/1455)
<br/>
> 그리디 (O(NM))
1. 격자를 입력받는다.
2. (i,j) 위치의 점 기준으로 뒤집히는 부분은 해당 점의 `왼쪽`과 `위쪽` 부분인데 이걸 고려하면, 오른쪽 아래에서부터 왼쪽 위까지 **_오른쪽에서 왼쪽으로, 아래에서 위쪽으로 올라오면서_** 격자가 1인 칸을 만났을 때 뒤집어준다.
```
for(int i = M-1 ; i >= 0 ; i--) {  // 열
for(int j = N-1 ; j >= 0 ; j--) {  // 행
// 1 만나면 axb만큼 뒤집기
if(board[j][i] == 1) {
flip(j, i);
answer++;
}
}
}
```
<br/>
오른쪽 아래에서 왼쪽 위까지 올라가면서 뒤집는 아이디어를 생각해 내는 것,,,
<br/>
뭔가 최적화를 하고 나서 최선의 값을 구해야 한다고 생각했는데 주유소 문제도 그렇고 그냥 완전탐색하면서 조건에 맞게 값을 변경시켜주어야 겠다고 생각했다.

[BOJ] 1455_뒤집기2 / 실버1 / 30분 / X

---

week17/BOJ_2141/우체국_한의정.java

- 백준 2141 - [우체국](https://www.acmicpc.net/problem/2141)
<br/>
1. 마을 위치 X와 마을에 사는 사람 수 A를 저장하는 객체 Node를 생성한다.
```
class Node implements Comparable<Node> {
long x, a;
public Node(long x, long a) {
this.x = x;
this.a = a;
}
@Override
public int compareTo(Node n) {
if(this.x == n.x)   return (int)(this.a - n.a); // 서로 거리가 같은 경우, 마을 인원 수 기준 오름차순 정렬
return (int)(this.x - n.x); // 서로 거리가 다르다면, 거리 기준 오름차순 정렬
}
}
```
2. X와 A를 입력받아 객체 배열에 저장하고, 해당 객체 배열을 마을 위치 X 기준으로 오름차순 정렬한다.
```
for(int i = 0 ; i < N ; i++) {
st = new StringTokenizer(br.readLine(), " ");
long X = Long.parseLong(st.nextToken());
long A = Long.parseLong(st.nextToken());
arr[i] = new Node(X, A);
sum += A;
}
Arrays.sort(arr);
```
4. 정렬한 객체 배열을 순차적으로 탐색하면서 현재 값들의 합이 모든 값들의 합의 중간값과 가장 근접해졌을 때 현재 위치의 마을의 위치 X를 출력하고 …

[BOJ] 2141_우체국 / 골드4 / 40분 / X

---

week17/BOJ_8980/택배_한의정.java

- 백준 8980 - [택배](https://www.acmicpc.net/problem/8980)
<br/>
> 시간 복잡도 : O(M)
1. M개의 박스 정보를 입력받고, 객체 배열에 저장 후 정렬한다.
- 정렬 기준 : 박스 받는 마을 번호 기준 오름차순 정렬. 받는 마을 번호가 같다면, 보내는 마을 번호 기준 오름차순 정렬
2. 처음엔 택배가 아무 박스도 싣지 않았으므로, 마을들에 실을 수 있는 택배 용량을 C만큼 기록한다.
```
capacities = new int[N + 1];
for(int i = 1 ; i < N ; i++) {
capacities[i] = C;
}
```
4. 마을에 도착하면, 해당 마을에서 박스를 실을 용량이 있는지 확인 후, 보낼 수 있는 최대 한도만큼 박스를 싣는다.
```
int maxCapacity = Integer.MAX_VALUE;
for(int j = now.from ; j < now.to ; j++) {
maxCapacity = Math.min(maxCapacity, capacities[j]);
}
```
6. 박스를 싣고 난 후, 실어준 박스의 목표 마을 전까지 용량을 줄인다.
```
for(int j = now.from ; j < now.to ; j++) {
capacities[j] -= Math.min(maxCapacity, now.box);
}
answer += Math.min(maxCapacity, now.box);
```
<br/>
- 배열,객체 인덱스 처리에서 자꾸 에러가 나서 좀 헷갈렸다,,
- 1번부터 N번 마을까지 돌면서 박스를 보내고-싣고 …

[BOJ] 8980_택배 / 골드1 / 50분 / X

---

week18/BOJ_11727/타일링2_한의정.java

- 백준 11727 - [2xn 타일링 2](https://www.acmicpc.net/problem/11727)
<br/>
그림을 그리면서 규칙을 찾다보면 아래와 같은 점화식이 발견된다.. 고 한다. ([출처1](https://dev01.tistory.com/70), [출처2](https://girawhale.tistory.com/34))
```
dp[i] = dp[i-1] + 2*dp[i-2]
```
<br/>
점화식 찾기,,,
<br/>
X

[BOJ] 11727_2xn 타일링 2 / 실버3 / 30분 / X

---

week18/BOJ_11052/카드구매하기_한의정.java

- 백준 11052 - [카드 구매하기](https://www.acmicpc.net/problem/11052)
<br/>
카드 i개를 구매하는 방법은 카드 **j개가 들어있는 카드팩 `P[j]`를 구매하고, `(i-j)` 개의 카드를 구매하는 것**이다.
<br/>
예를 들어 카드 4개를 구매하는 방법의 경우,
- 카드 1개가 들어있는 카드팩 `P[1]`을 구매하고, 카드 3개(`dp[4-1]`)를 구매한다.
- 카드 2개가 들어있는 카드팩 `P[2`]를 구매하고, 카드 2개(`dp[4-2]`)를 구매한다.
- 카드 3개가 들어있는 카드팩 `P[3]`을 구매하고, 카드 1개(`dp[4-3]`)를 구매한다.
<br/>
이걸 일반화한 점화식은 아래와 같다.
```
dp[i] = P[n] + dp[i - n]
```
<br/>
1부터 N개의 카드를 뽑으면서, 카드 N개를 구매하는 데 드는 최대 비용을 구한다.
```
for(int i = 1 ; i <= N ; i++) {
for(int j = 1 ; j <= i ; j++) {
dp[i] = Math.max(dp[i], P[j] + dp[i-j]);
}
}
```
<br/>
점화식에서 카드팩 j개 `P[j]`를 구매하고,  (i-j)개의 카드 `dp[i - j]`를 구매하는 것인데
둘다 그냥 카드팩으로 생각하고 점화식 계산했었다,,,
<br/>
카드팩과 카드를 구매하는 방법

[BOJ] 11052_카드 구매하기 / 실버1 / 30분 / X

---

week18/BOJ_15990/더하기5_한의정.java

- 백준 15990 - [1, 2, 3 더하기 5](https://www.acmicpc.net/problem/15990)
<br/>
> DP → 시간 복잡도 : O(T)
같은 숫자가 2번 이상 연달아 나오면 안 되므로, dp를 **2차원 배열**로 만들어 dp[n]의 마지막 숫자를 기준으로 갯수를 세는 방법을 사용한다. ([점화식 구하는 과정 참고](https://lotuslee.tistory.com/44))
```
dp[n][1] = dp[n-1][2] + dp[n-1][3]   // 1로 끝나지 않으면서, 합이 n-1이 되는 경우
dp[n][2] = dp[n-2][1] + dp[n-2][3]   // 2로 끝나지 않으면서, 합이 n-2가 되는 경우
dp[n][3] = dp[n-3][1] + dp[n-3][2]   // 3으로 끝나지 않으면서, 합이 n-3이 되는 경우
```
<br/>
점화식 찾기,,,
<br/>
2차원 배열을 사용해 dp 문제를 해결하는 풀이,,

[BOJ] 15990_1, 2, 3 더하기 5 / 실버2 / 30분 / X

---

week18/BOJ_2225/합분해_한의정.java

- 백준 10164 - [합분해](https://www.acmicpc.net/problem/2225)
<br/>
> DP → 시간 복잡도 : O(NK)
`DP[N][K] : 숫자 K개로 N을 만들 수 있는 경우의 수`
그림을 그려서 점화식을 세우다 보면, `dp[N][K] = dp[N-1][K] + dp[N][K-1]` 라는 점화식이 나온다.
<br/>
- dp 2차원 격자 배열을 채울 때 범위를 잘못 설정해서 틀리고 있었다,, 숫자 범위에 유의하기,,
<br/>
X

[BOJ] 2225_합분해 / 골드5 / 40분 / X

---

week18/BOJ_11066/파일합치기_한의정.java

- 백준 11066 - [파일 합치기](https://www.acmicpc.net/problem/11066)
<br/>
> 누적합+ DP
<br/>
필요 자료구조
- 파일 비용 합 저장 배열 (누적합)
- 파일 최소 비용 저장 배열
<br/>
```
dp[i][j] : j번째 챕터부터 i번째 챕터를 합쳤을 때의 최솟값
```
예를 들어 `A1, A2 ,A3, A4` 존재 시
`DP[1][2]`는 A1,A2를 합쳤을 때 최소비용
`DP[1][3]`은 A1, A2, A3를 합쳤을 때 최소비용
`DP[2][4]`는 A2, A3, A4를 합쳤을 때 최소비용
최소비용을 구할 시 `A1, A2, A3`가 존재하면 챕터를 합칠 수 있는 경우의 수는
1. (A1, A2), A3 : A1과 A2를 먼저 합친 후 A3와 합치기
2. A1, (A2, A3) : A2와 A3를 먼저 합친 후 A1과 합치기
<br/>
1번에서 (A1, A2)는 DP[1][2]로 표현하고 A3은 DP[3][3]으로 표현한 뒤
A1, A2, A3는 무조건 한 번씩 합쳐지므로 1~3까지의 비용값을 모두 더해줘야 한다.
그럼 1번에서 이렇게 식이 나온다. → `DP[1][2] + DP[3][3] + sum[3] - sum[0]`
2번에서는 이렇게 식이 나온다. → `DP[1][1] + DP[2][3] + sum[3] - sum[0]`
<br/>
이처럼 구하다 보면 아래와 같은 점화식을 발견할 수 있다.
```
dp[from][to] = dp[from][s] + dp[s+1][to] + (sum[to] - sum[from-1])
```
<br/>
- 규칙 …

[BOJ] 11066_파일 합치기 / 골드3 / 30분 / X

---

week19/BOJ_16937/두스티커_한의정.java

- 백준 16937 - [두 스티커](https://www.acmicpc.net/problem/16937)
<br/>
> 브루트포스
1. 스티커 객체 리스트에 스티커의 위치를 저장한다.
2. 스티커 리스트를 돌며 모든 스티커를 붙인다.
1. 1번 스티커 붙이기
-  (0,0) 기준으로 붙이기를 시작한다. (그래야 스티커 붙이고 나서 제일 많은 칸을 남길 수 있으므로)
- 1번 스티커를 붙여보고, 붙이기 성공 시 2번 스티커를 붙인다.
- 1번 스티커를 **회전해서** 붙여보고, 붙이기 성공 시 2번 스티커를 붙인다.
3. 2번 스티커 붙이기 (second 메소드)
- 모눈종이에 2번 스티커를 그대로 / 회전해서 붙여본다.
- 2번째 스티커 붙이기 성공 시, 최대 넓이와 비교해 더 큰 값으로 정답을 갱신한다.
<br/>
- 회전해서 어디에 어떻게 붙이지,,,
- 스티커 붙이고 나서 좌표는 어떻게 잡지,,,
<br/>
- 해결 아이디어,,, 
- 스티커 회전해서 붙이는 방법,,

[BOJ] 16937_두 스티커 / 실버3 / 30분 / X

---

week19/BOJ_3019/테트리스_한의정.java

- 백준 3019 - [테트리스](https://www.acmicpc.net/problem/3019)
<br/>
> 구현, 브루트포스 
1. 블록 모양에 따라 **올라와야 하는 바닥면의 높이**를 저장한다.
```
// 빈 공간 갯수만 세어 타일 저장
static int[][][] shape = {{{0}, {0,0,0,0}},
{{0,0}},
{{0,0,1}, {1,0}},
{{1,0,0}, {0,1}},
{{0,0,0}, {0,1}, {1,0,1}, {1,0}},
{{0,0,0}, {0,0}, {0,1,1}, {2,0}},
{{0,0,0}, {0,0}, {1,1,0}, {0,2}}
```
2. 바닥면에 대해 블록을 끝까지 내릴 수 있는지 반복문을 통해 검사한다.
- 블록 놓을 수 있는 자리 : 각 번호에 맞는 빈 공간 수를 뺐을 때 모두 같은 값이 나오는 경우
<br/>
- 배열 인덱스 처리하는 부분,,,,
<br/>
다아아ㅏ,,
🔗  참고 : https://lovelyunsh.tistory.com/101

[BOJ] 3019_테트리스 / 실버1 / 30분 / X

---

week19/BOJ_16938/캠프준비_한의정.java

- 백준 16938 - [캠프 준비](https://www.acmicpc.net/problem/16938)
<br/>
> DFS + 브루트포스
1. 인덱스와 난이도를 저장하는 객체 배열을 만들고, 숫자를 N개 입력 받아 객체 배열을 채운다.
2. 객체 배열을 난이도 기준 오름차순 정렬한다. (나중에 난이도 가장 작은 애랑 큰 애 비교하기 위해서)
3. DFS로 2~N개까지 캠프에 사용할 문제를 고르고, 원하는 갯수만큼 골랐을 때 1, 2번 조건을 만족하는지 확인하고 정답을 갱신한다.
```
for(int i = 2 ; i <= N ; i++) {
      visited = new boolean[N];
      dfs(i, 0);
}
```
```
private static void dfs(int target, int cnt) { // 목표 갯수, 현재 뽑은 갯수
    // 목표 갯수만큼 뽑았으면 조건 만족하는지 확인하고 방법 수 갱신
    if(cnt == target) {
        int sum = 0;
        
        List<Integer> list = new ArrayList<>();
        for(int i = 0 ; i < N ; i++) {
            if(visited[i]) {
                list.add(i);
                sum += arr[i].lv;
            }
        }
         …
```

[BOJ] 16938_캠프 준비 / 골드5 / 35분 / O

---

week15/BOJ_2206/벽부수고이동하기_강아현.py

- 백준 2206 - 벽 부수고 이동하기
<br/>
> 각 위치까지의 최단 이동 횟수를 기록하기 위해 3차원 배열 `visit`를 사용한다.
> - (행, 열, 벽을 부순 횟수)로 이루어져있다.
1. 큐에 현재 위치와 이동 횟수를 저장한다.
2. BFS 함수 : 시작점(0,0) / 시작 횟수(0)
- 큐에서 현재 위치와 이동 횟수를 가져온다.
- 만약 현재 위치가 목적지인 경우, 해당 위치의 이동 횟수를 반환한다.
- 현재 위치에서 네 방향으로 이동가능한지 확인한다.
- 이동할 때 벽을 부술 수 있는 경우 `cnt == 0` 이면 벽을 부순 상태로 큐에 추가한다.
- 벽이 없으며 이동한 적이 없는 경우, 이동한 횟수를 기록하고 큐에 위치를 추가한다.
3. 목적지에 도달하지 못했을 경우에는 -1을 반환한다.
<br/>
bfs 탐색할 때 cnt를 같이 고려하는 방법에 대한 구현이 아직은 부족한 것 같다.
<br/>
x

[BOJ] 2206_벽 부수고 이동하기 / 골드3 / 60분 / X

---

week15/BOJ_22946/원이동하기1_강아현.py

- 백준 22946 - 원 이동하기 1
<br/>
> 시간 복잡도 : O(n^2)
> **dfs(x)**
>
> - DFS를 수행한다.
> - 두 원 중심 사이의 거리를 계산하여 하나의 원이 다른 원 안에 있는지 확인한다.
> - 만약 한 원이 다른 원 안에 있다면, 두 원을 그래프로 연결한다.
> **lfs(L,x)**
>
> - LFS를 수행한다.
> - 시작 지점부터 그래프를 따라 이동하면서 최장 경로의 길이를 찾는다.
> **main**
>
> - dfs 함수로 그래프를 구성하고, 그래프를 통해 연결된 원들 간의 최장 경로를 lfs 함수로 찾는다.
<br/>
원들 간의 관계를 트리 구조로 나타내서 풀이하려고 했는데 계속 시간초과가 났다. <br> 임의의 원 두 개를 combinations로 선택한 뒤 이 두 원의 거리를 계산하려고 나니 계속 시간초과가 난 것이었다. lfs로 해결할 수 있었다.
<br/>
LFS를 이렇게도 쓸 수 있다는 것을 알게 되었다. 여러 알고리즘의 기본을 알아야 여기저기 적용할 수 있다는 것을 느끼게 되었다.

[BOJ] 22946_원 이동하기 1 / 골드2 / 120분 / X

---

week16/BOJ_4963/섬의개수_강아현.py

- 백준 4963 - 섬의 개수
<br/>
> 시간 복잡도 : O(w * h * k)
> **search(x,y)**
>
> - 땅인 지점에서 상하좌우대각선을 확인하며 이어져있는 땅을 찾는다.
> - 위에서 찾은 땅을 모두 바다(0)로 바꾼다.
>
> **main**
>
> - w == h == 0인 경우, while문 탈출
> - board를 돌면서 값이 1인 경우 search(x,y)를 실행한다.
> - search를 실행할 때마다 cnt에 +1을 해서 섬의 개수를 구한다.
<br/>
x
<br/>
x

[BOJ] 4963_섬의 개수 / 실버2 / 20분 / O

---

week16/BOJ_14716/현수막_강아현.py

- 백준 14716 - 현수막
<br/>
> 시간 복잡도 : O(w * h * k)
> - banner를 순회하며 1인 경우 search_letter로 한 개의 글자를 찾아낸다.
> - search_letter로 방문한 곳은 모두 값을 0으로 변경한다.
> - search_letter가 호출되는 횟수를 글자의 개수로 반환한다.
<br/>
x
<br/>
x

[BOJ] 14716_현수막 / 실버1 / 10분 / O

---

week16/BOJ_17836/공주님을구해라_강아현.py

- 백준 17836 - 공주님을 구해라!
<br/>
> 칼을 사용하지 않는 경우의 최단시간과 사용하는 경우의 최단시간을 구해서 최솟값을 찾아 출력한다.
1. 칼이 있다면 칼의 위치를 리스트에 저장해둔다.
2. 칼을 사용하지 않는 경우
- bfs에 출발지인 (0,0)과 목적지인 (n-1,m-1), 시간0을 넘겨준다.
- 상하좌우로 탐색하다가 목적지에 도달하면 현재까지의 시간을 리턴하고, 목표지점에 도달하지 못하면 INF를 리턴한다.
3. 칼을 사용하는 경우
- 이 경우 최단시간 = 칼까지 도달하는 최단시간 + 칼 위치와 목적지 위치 사이 거리
- 칼까지 도달하는 최단시간을 구하기 위해 bfs에 출발지인 (0,0)과 칼 위치인 (knife[0], knife[1]), 시간0을 넘겨준다.
- 칼까지 도달할 수 없을 경우 bfs에서 INF가 리턴되고, 칼을 사용하지 못하는 것이기 때문에 최단시간을 그냥 INF로 넣어준다.
- 그 외에는 칼까지 도달할 수 있는 것이므로 최단시간을 (칼까지 도달하는 최단시간 + 칼 위치와 목적지 위치 사이 거리)로 만들어준다.
<br/>
이 문제 풀이 방식을 생각해내는 거 자체가 어려웠다..
<br/>
x

[BOJ] 17836_공주님을 구해라! / 골드5 / 120분 / X

---

week19/BOJ_17406/배열돌리기4_한의정.java

- 백준 17406 - [배열 돌리기 4](https://www.acmicpc.net/problem/17406)
<br/>
> 백트래킹 + 브루트포스
> ㄴ 시간 복잡도 : O(K!×N×M) ▷ 순열 생성 O(K!) * 배열 회전 O(NM)
1. 회전 연산의 순서를 정하는 순열을 진행한다.
2. K개 뽑아서 순열을 완성했을 때, 배열을 회전시킨다.
1. 원본 배열을 복사한 배열을 생성한다.
2. 범위 내의 값들을 위쪽, 아래쪽, 왼쪽, 오른쪽으로 4등분하고 이동시키면서 회전시킨다.
3. 회전 완료 후, 행들의 합 중 최솟값을 구한다.
<br/>
배열 회전시키는 것,, 4방향을 while문을 활용해 회전시키려고 했는데 구현하진 못 했다.
<br/>
회전하는 방법을 다시 되새기다,,,
[회전하는 다른 방법](https://velog.io/@gandi0330/Java-%EB%B0%B1%EC%A4%80-%EB%B0%B0%EC%97%B4-%EB%8F%8C%EB%A6%AC%EA%B8%B0-4-17406%EB%B2%88)도 함께 첨부한다..

[BOJ] 17406_배열 돌리기 4 / 골드4 / 60분 / X

---

week19/BOJ_9944/NxM보드완주하기_한의정.java

- 백준 9944 - [NxM 보드 완주하기](https://www.acmicpc.net/problem/9944)
<br/>
> 백트래킹 ▷ 시간 복잡도 : O(NM)
<br/>
필요 자료구조
- 상하좌우 탐색용 dx/dy 배열
- 보드 정보 저장용 배열
- 방문 표시용 boolean형 배열
- 이동 횟수(방향 트는 횟수) 저장용 변수 result
- 방문한 칸 갯수 나타내는 변수 cnt
1. N과 M을 입력받고, 격자를 입력받는다. 이 때 장애물인 경우, 미리 방문 처리하고 방문한 칸 갯수도 1 증가시켜준다.
2. 만약 한 칸만 빈 칸인 경우 (`cnt == N*M`), 해당 케이스의 정답은 0이다.
3. 그게 아닌 경우, 모든 격자를 돌며 빈 칸(=방문하지 않은 칸)에서 4방향 탐색을 통해 이동 가능한 칸에 대해 다음 칸으로 이동한다.
```
for(int i = 0 ; i < N ; i++) {
for(int j = 0 ; j < M ; j++) {
if(visited[i][j])   continue; // 장애물인 경우, pass
for(int d = 0 ; d < 4 ; d++) { // 빈 칸(.)인 경우, 4방향 탐색
if(!isValid(i + dx[d], j + dy[d])) continue;
visited[i][j] = true;
search(i, j, result, d, cnt);  // (i,j)에서 d 방향으로 이동하겠단 의미
visited[i][j] = false; // 지나온 길 되돌아가기
}
}
}
```
<br/>
- 종료 조건 : 모든 빈 칸을 방문한 경우(`cnt == …

[BOJ] 9944_NxM 보드 완주하기 / 골드3 / 40분 / X

---

week19/BOJ_16637/괄호추가하기_한의정.java

- 백준 16637 - [괄호 추가하기](https://www.acmicpc.net/problem/16637)
<br/>
> 백트래킹
1. 입력받은 문자열을 숫자와 연산자로 나눠 리스트에 따로 저장한다.
2. 해당 위치에서 괄호로 묶을지 말지를 백트래킹으로 판단하며 정답을 구한다.
- <인자> 현재 위치의 숫자 `num`, 숫자 인덱스 `depth`
- <종료 조건> 주어진 연산자 갯수만큼 뽑았으면 정답과 계산 결과 중 더 큰 값으로 정답을 갱신한다.
- 그게 아니라면 아래 두 경우로 나눠 계산한다.
1. 현재 위치에서 괄호를 안 치고 넘기는 경우 > 현재 숫자 num과 다음 숫자를 계산한다. (예: a+b-c에서 a+b를 먼저 계산)
2. 괄호를 치고 넘기는 경우, 마지막 숫자가 아니라면, 현재 위치 다음의 숫자 n1와 현재 위치 다음다음의 숫자 n2를 먼저 계산한다. (예 : a+b-c 에서 a+(b-c) 이렇게 계산)
<br/>
- 백트래킹 문제란 생각은 했는데 괄호를 치고, 안 치고 하는 경우의 수를 어떻게 나눠서 계산하고 결과를 구해야 할지 몰랐다,,
<br/>
- 해당 위치에서 괄호를 치느냐/ 안 치느냐를 처리하는 방법

[BOJ] 16637_괄호 추가하기 / 골드3 / 50분 / X

---

week19/PGS_60058/괄호변환_한의정.java

- 백준 60058 - [괄호 변환](https://school.programmers.co.kr/learn/courses/30/lessons/60058)
<br/>
> 재귀 -> 시간 복잡도 : O(N)
문제에서 말한 순서대로 구현하면 된다,,
1. 입력이 빈 문자열인 경우, 빈 문자열을 출력한다.
2. 올바른 괄호 문자열인 경우, 문자열을 그대로 출력한다.
```
// 올바른 괄호 문자열인지 판단하는 메소드
private static boolean isValid(String str) {
int cnt = 0;
for(char c : str.toCharArray()) {
if(c == '(') {
cnt++;
}
else {
cnt--;
if(cnt < 0)
return false;
}
}
return true;
}
```
3. 올바른 괄호 문자열이 아닌 경우, 균형잡힌 괄호 문자열을 올바른 괄호 문자열로 바꾸는 변환 작업을 진행한다. (재귀)
- 과정2) 문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리한다. ⇒ _열린 괄호 갯수 = 닫힌 괄호 갯수가 같은 인덱스 위치에서 분리한다._
```
for(int i = 0 ; i < w.length() ; i++) {
if(w.charAt(i) == '(')  openCnt++;
else                    openCnt--;
if(openCnt == 0) {  // 균형잡힌 괄호 문자열인 경우
// 2. 문자열 w를 균형잡힌 괄호 문자열 u와 v로 분리
u.append(w.substring(0, i+1)); …
```

[PGS] 60058_괄호 변환 / level2 / 50분 / X

---

week20/BOJ_16956/늑대와양_한의정.java

- 백준 16956 - [늑대와 양](https://www.acmicpc.net/problem/16956)
<br/>
> BFS → 시간 복잡도 : O(RC)
**_늑대(W)의 인접한 빈 칸(.)들에 모두 울타리를 설치하면 된다._**
1. 격자를 입력받을 때, 큐에 늑대 위치를 저장한다.
2. BFS를 수행한다.
- 늑대가 인접한 칸(상하좌우)으로 이동하게 한다.
- 만약 이동하려는 칸이 빈 칸(.)이라면, 해당 칸에 울타리 D를 설치한다.
- 이동하려는 칸이 양(W)이라면, 늑대가 양에게 도달했으므로 BFS 함수를 종료한다.
3. 결과 출력
- 늑대가 양이 있는 칸으로 갈 수 있다면, 0을 출력하고 종료한다.
- 갈 수 없다면, 1을 출력하고, 울타리를 설치한 결과가 포함된 목장 상태를 출력한다.
<br/>
- 문제를 풀었을 때 테스트케이스랑 정답이 다르길래 쫄아있었다. 
<br/>
- 백준 스페셜저지 문제는 예제 문제의 답과 달라도 정답 처리가 될 수 있다고 한다,,,
- 그냥 늑대랑 인접한 빈 칸에 모두 울타리를 설치해주면 되는 문제였다. (설치해야 하는 최소 울타리 갯수 구하는 문제가 아니라)

[BOJ] 16956_늑대와 양 / 실버3 / 30분 / X

---

week20/BOJ_17086/아기상어2_한의정.java

- 백준 17086 - [아기 상어 2](https://www.acmicpc.net/problem/17086)
<br/>
> 브루트포스 + BFS ⇒ 시간 복잡도 : O(NM)
<br/>
**_1이 아닌 모든 점에서 BFS를 수행하고, 이동 거리의 최댓값을 구해 갱신한다._** 
- 방문 표시 배열은 BFS 실행할 때마다 ⭐매번⭐ 초기화한다.  
- 해당 점에서 8방향 탐색을 진행한다.
1. 격자 범위를 벗어나고, 방문한 적 있는 좌표라면 패스한다.
2. 격자 범위를 벗어나지 않고, 방문한 적 없는 좌표의 경우
- 다음 이동할 칸의 점이 1이라면, 거리를 출력하고 종료한다.
- 다음 이동할 칸의 점이 0이라면, 다음 좌표를 방문 처리하고, 큐에 이동할 위치와 거리값 + 1을 추가해 마저 이동한다.
<br/>
- 1인 칸에서 BFS를 수행할 생각을 했었다,, > 0인 칸에서 BFS를 수행해야 했다.
- 모든 점에서 특정 좌표까지 도달하는 거리를 구해서, 이 중 최댓값을 구해야 하나? 라는 생각을 했다.
<br/>
- 0인 칸에서 BFS 수행하기
- 매 칸마다 BFS할 때 방문 표시 배열 새로 초기화해서 사용하기

[BOJ] 17086_아기 상어 2 / 실버2 / 30분 / X

---

week20/BOJ_5014/스타트링크_한의정.java

- 백준 5014 - [스타트링크](https://www.acmicpc.net/problem/5014)
<br/>
> BFS ⇒ 시간 복잡도 : O(F)
<br/>
x층까지 도달하기 위해 버튼을 누른 횟수를 저장하는 int형 배열을 활용한다.
1. 강호가 있는 S층에 가려면 1번 눌러야 하므로 `arr[S] = 1`로 저장한다.
2. 위쪽으로 U칸 이동했을 때 최고층보다 아래에 있고, 누른 적 없는 칸이라면 해당 칸을 누르고, 버튼 누른 횟수를 갱신해 저장한다.
```
if(now + U <= F) {  // 최고층 F층 아래에 있고
if(arr[now + U] == 0) { // 방문한 적 없는 경우
arr[now + U] = arr[now] + 1;
q.add(now + U);
}
}
```
3. 아래쪽으로 D칸 이동했을 때 최저층보다 위에 있고, 누른 적 없는 칸이라면 해당 칸을 누르고, 버튼 누른 횟수를 갱신해 저장한다.
```
if(now - D >= 1) {  // 최저층 1층 이상에 있고
if(arr[now - D] == 0) { // 방문한 적 없는 경우
arr[now - D] = arr[now] + 1;
q.add(now - D);
}
}
```
<br/>
- 누른 적 없는 칸으로 이동해야 하는 처리를 빠뜨려서 정답이 출력되지 않았었다,,
<br/>
X

[BOJ] 5014_스타트링크 / 실버1 / 40분 / X

---

week20/BOJ_2251/물통_한의정.java

- 백준 2251 - [물통](https://www.acmicpc.net/problem/2251)
<br/>
> BFS
필요 자료구조
- 물을 보내고 받을 수 있는 6가지 경우를 나타내는 배열 ⇒ 물을 보내는 물통 from / 물을 받는 물통 to
- 물을 옮길 수 있는지 나타내는 2차원 방문 표시 배열 (visited[i][j] : i에서 j 물통으로 보낼 수 있다는 의미)
- 3번째 물통에 담을 수 있는 양을 나타내는 리스트
6가지 경우의 수를 돌며 물을 주고 받는다.
- BFS로 물 주고 받기
```
static void bfs() {
Queue<int[]> q = new ArrayDeque<>();
q.add(new int[] {0,0});   // 일단 0→0 추가
visited[0][0] = true;   // 일단 0→0 방문 표시
while(!q.isEmpty()) {
int[] now = q.poll();  // 현재 상태
int a = now[0];
int b = now[1];
int c = arr[2] - a - b;
for(int i = 0 ; i < 6 ; i++) {  // 물 주고받는 6가지 상황 돌려보기
int[] next = {a,b,c};  // 물 주고받은 후 다음 상태
next[to[i]] += next[from[i]];  // 물 받은 병은 양을 채우고,
next[from[i]] = 0;  // 물 준 병에 남은 양은 0이 됨
if(next[to[i]] > arr[to[i]]) {  // 물 옮겼을 때 넘치는 경우 조절하기
next[from[i]] = …
```

[BOJ] 2251_물통 / 골드5 / 50분 / X
